### ISSUE TITLE
EnderIO Crash

### ISSUE THREAD

**Issue by ferrari314** [SleepyTrousers/EnderIO#1369]
Hello.
Ender IO it's very good mod. But now I can't use it at my game.
After install EnderIO-1.7.10-2.2.2.285 I have crash, when game loading main menu and initialising mods. 
Without EIO game working good.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 08.12.14 21:16
Description: Initializing game

java.lang.IllegalArgumentException: ID is already registered: 3
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
    at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:107)
    at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:251)
    at com.draco18s.artifacts.DragonArtifacts.preInit(DragonArtifacts.java:471)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
    at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:107)
    at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:251)
    at com.draco18s.artifacts.DragonArtifacts.preInit(DragonArtifacts.java:471)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 362651472 bytes (345 MB) / 1665138688 bytes (1588 MB) up to 3780640768 bytes (3605 MB)
    Mod Pack: ~~ERROR~~ NullPointerException: null
    LiteLoader Mods: ~~ERROR~~ NullPointerException: null
    LaunchWrapper: 37 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: com.rebelkeithy.dualhotbar.DualHotbarTransformer
          - Transformer: mariculture.fishery.VanillaOverride
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: mariculture.core.AccessTransformers
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: shadersmodcore.transform.SMCClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 1 total; -Xmx4056M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_A4 54 mods loaded, 54 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.3.23} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.56} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.601-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.601-experimental.jar) Unloaded->Constructed->Pre-initialized
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.0.18} [BuildCraft](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.7.3} [BiblioCraft](BiblioCraft-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.0.18} [BC Transport](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.0.18} [BC Silicon](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.0.18} [BC Builders](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.0.18} [BC Factory](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.0.18} [BC Energy](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.6b} [Chisel](Chisel-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    props{1.10} [Decocraft](Decocraft-1.10_1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized
    dualhotbar{1.5} [Dual Hotbar](Dual-Hotbars-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.2.2.285} [Ender IO](EnderIO-1.7.10-2.2.2.285.jar) Unloaded->Constructed->Pre-initialized
    EE3{0.2.234} [Equivalent Exchange 3](Equivalent-Exchange-3-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    exnihilo{1.34} [Ex Nihilo](Ex-Nihilo-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.0.0.136} [Forestry for Minecraft](forestry_1.7.10-3.0.0.136.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.56.739} [Iron Chest](ironchest-1.7.10-6.0.56.739-universal.jar) Unloaded->Constructed->Pre-initialized
    lycanitesmobs{1.10.0c - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    arcticmobs{1.10.0c - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    demonmobs{1.10.0c - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    desertmobs{1.10.0c - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    forestmobs{1.10.0c - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    freshwatermobs{1.10.0c - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    infernomobs{1.10.0c - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    junglemobs{1.10.0c - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    mountainmobs{1.10.0c - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    plainsmobs{1.10.0c - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    saltwatermobs{1.10.0c - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    swampmobs{1.10.0c - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.10.0c [1.7.10].jar) Unloaded->Constructed->Pre-initialized
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized
    MapWriter{2.1.2} [MapWriter](MapWriter-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized
    Mariculture{1.2.3d} [Mariculture](Mariculture-1.7.10-1.2.3d.jar) Unloaded->Constructed->Pre-initialized
    MorePistons{1.7.10-1.5.1.3} [More Pistons](More-Pistons-Mod-by-Jiraiyah-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    neiintegration{1.0.2} [NEI Integration](NEIIntegration-MC1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.4.0.0} [Railcraft](Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
    AS_Ruins{13.4} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.10} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.10.jar) Unloaded->Constructed->Pre-initialized
    Treecapitator{1.7.2} [Treecapitator](Tree-Capitator-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Artifacts{1.0.4} [Artifacts](Unique-Artifacts-Mod-1.7.10.jar) Unloaded->Constructed->Errored
    wildcaves3{0.4.3.6} [Wild Caves 3](Wild-Caves-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Launched Version: Forge 1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 570/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: Русский (Россия)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by alpharulesirulee** [comment]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/19/14 6:06 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at net.minecraft.world.biome.BiomeGenMutated.func_150558_b(SourceFile:71)
at net.minecraft.block.BlockGrass.func_149720_d(BlockGrass.java:135)
at CustomColorizer.getColorMultiplier(CustomColorizer.java:492)
at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4691)
at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:318)
at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2232)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1500)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1299)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at net.minecraft.world.biome.BiomeGenMutated.func_150558_b(SourceFile:71)
at net.minecraft.block.BlockGrass.func_149720_d(BlockGrass.java:135)
at CustomColorizer.getColorMultiplier(CustomColorizer.java:492)
at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4691)
at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:318)
at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2232)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1500)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP['highway95'/228, l='MpServer', x=43.58, y=128.09, z=300.07]]
Chunk stats: MultiplayerChunkCache: 130, 139
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (30,64,-104), Chunk: (at 14,4,8 in 1,-7; contains blocks 16,0,-112 to 31,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Level time: 1792 game time, 1792 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 99 total; [EntityZombie['Zombie'/531, l='MpServer', x=66.50, y=44.00, z=229.50], EntitySkeleton['Skeleton'/538, l='MpServer', x=-20.50, y=41.00, z=248.50], EntityClientPlayerMP['highway95'/228, l='MpServer', x=43.58, y=128.09, z=300.07], EntityCreeper['Creeper'/302, l='MpServer', x=-17.28, y=66.00, z=240.50], EntityZombie['Zombie'/303, l='MpServer', x=-16.50, y=66.00, z=247.50], EntityFallingBlock['Falling Block'/559, l='MpServer', x=79.50, y=38.49, z=301.50], EntityCow['Cow'/304, l='MpServer', x=-21.50, y=76.00, z=293.50], EntityCow['Cow'/305, l='MpServer', x=-22.50, y=76.00, z=295.50], EntityCow['Cow'/306, l='MpServer', x=-19.22, y=77.00, z=295.78], EntityCow['Cow'/307, l='MpServer', x=-17.31, y=77.00, z=295.69], EntityFallingBlock['Falling Block'/563, l='MpServer', x=79.50, y=38.49, z=302.50], EntityZombie['Zombie'/308, l='MpServer', x=-8.50, y=42.00, z=245.50], EntityZombie['Zombie'/309, l='MpServer', x=-8.50, y=42.00, z=243.34], EntityZombie['Zombie'/310, l='MpServer', x=-8.50, y=66.00, z=245.50], EntitySquid['Squid'/311, l='MpServer', x=-5.50, y=58.00, z=341.47], EntitySquid['Squid'/312, l='MpServer', x=-7.61, y=58.95, z=342.03], EntitySquid['Squid'/313, l='MpServer', x=-16.83, y=58.37, z=341.47], EntityFallingBlock['Falling Block'/570, l='MpServer', x=78.50, y=38.49, z=301.50], EntityCreeper['Creeper'/316, l='MpServer', x=7.04, y=26.00, z=226.32], EntityCow['Cow'/317, l='MpServer', x=7.78, y=77.00, z=237.69], EntityFallingBlock['Falling Block'/573, l='MpServer', x=78.50, y=38.49, z=302.50], EntityCow['Cow'/318, l='MpServer', x=7.50, y=78.00, z=236.47], EntityFallingBlock['Falling Block'/574, l='MpServer', x=79.50, y=38.49, z=300.50], EntityCow['Cow'/319, l='MpServer', x=6.16, y=77.00, z=238.47], EntityFallingBlock['Falling Block'/575, l='MpServer', x=79.50, y=38.49, z=303.50], EntityCow['Cow'/320, l='MpServer', x=6.50, y=76.00, z=239.97], EntityChicken['Chicken'/321, l='MpServer', x=15.50, y=80.00, z=318.50], EntityChicken['Chicken'/322, l='MpServer', x=15.50, y=80.00, z=321.50], EntitySquid['Squid'/323, l='MpServer', x=15.56, y=59.82, z=341.47], EntitySquid['Squid'/324, l='MpServer', x=16.94, y=60.51, z=346.47], EntityFallingBlock['Falling Block'/589, l='MpServer', x=78.50, y=38.49, z=300.50], EntityFallingBlock['Falling Block'/590, l='MpServer', x=78.50, y=38.49, z=303.50], EntityCow['Cow'/336, l='MpServer', x=16.50, y=87.00, z=255.50], EntitySkeleton['Skeleton'/337, l='MpServer', x=17.50, y=36.00, z=265.50], EntityChicken['Chicken'/338, l='MpServer', x=29.50, y=77.00, z=329.50], EntityChicken['Chicken'/339, l='MpServer', x=29.50, y=76.00, z=330.50], EntityChicken['Chicken'/340, l='MpServer', x=28.50, y=76.00, z=331.50], EntityChicken['Chicken'/341, l='MpServer', x=29.50, y=76.00, z=331.50], EntityChicken['Chicken'/342, l='MpServer', x=18.50, y=80.00, z=321.50], EntityFallingBlock['Falling Block'/598, l='MpServer', x=77.50, y=38.49, z=301.50], EntityChicken['Chicken'/343, l='MpServer', x=16.50, y=80.00, z=321.50], EntityFallingBlock['Falling Block'/599, l='MpServer', x=77.50, y=38.49, z=300.50], EntitySquid['Squid'/344, l='MpServer', x=20.53, y=60.00, z=339.47], EntitySquid['Squid'/345, l='MpServer', x=15.47, y=61.70, z=339.47], EntityCow['Cow'/346, l='MpServer', x=30.50, y=67.00, z=338.50], EntityBat['Bat'/351, l='MpServer', x=43.94, y=36.00, z=219.25], EntityWitch['Witch'/352, l='MpServer', x=47.50, y=25.00, z=246.50], EntityZombie['Zombie'/353, l='MpServer', x=45.41, y=37.00, z=247.06], EntityCow['Cow'/354, l='MpServer', x=47.06, y=88.00, z=253.72], EntityCow['Cow'/355, l='MpServer', x=40.44, y=92.00, z=240.25], EntityZombie['Zombie'/356, l='MpServer', x=44.50, y=13.00, z=263.50], EntityCreeper['Creeper'/357, l='MpServer', x=40.50, y=13.00, z=264.50], EntitySkeleton['Skeleton'/358, l='MpServer', x=47.50, y=13.00, z=294.50], EntitySkeleton['Skeleton'/359, l='MpServer', x=46.50, y=13.00, z=294.50], EntityCreeper['Creeper'/360, l='MpServer', x=46.50, y=14.00, z=308.50], EntityCow['Cow'/361, l='MpServer', x=33.50, y=69.00, z=335.50], EntityCow['Cow'/362, l='MpServer', x=33.78, y=65.00, z=338.50], EntityCow['Cow'/363, l='MpServer', x=32.47, y=66.00, z=338.50], EntityZombie['Zombie'/364, l='MpServer', x=42.50, y=62.00, z=356.50], EntityBat['Bat'/367, l='MpServer', x=62.47, y=35.10, z=212.75], EntityCow['Cow'/368, l='MpServer', x=58.78, y=91.00, z=211.78], EntityCow['Cow'/369, l='MpServer', x=57.03, y=91.00, z=210.31], EntityCow['Cow'/370, l='MpServer', x=58.56, y=91.00, z=209.47], EntityCow['Cow'/371, l='MpServer', x=59.66, y=91.00, z=208.25], EntityBat['Bat'/372, l='MpServer', x=53.06, y=39.00, z=225.50], EntityBat['Bat'/373, l='MpServer', x=51.00, y=38.00, z=226.63], EntityCow['Cow'/374, l='MpServer', x=50.81, y=90.00, z=249.63], EntityCow['Cow'/375, l='MpServer', x=50.66, y=91.00, z=248.16], EntityCreeper['Creeper'/377, l='MpServer', x=58.50, y=17.00, z=287.50], EntitySkeleton['Skeleton'/378, l='MpServer', x=48.50, y=13.00, z=295.50], EntityCreeper['Creeper'/379, l='MpServer', x=59.50, y=17.00, z=288.50], EntityZombie['Zombie'/381, l='MpServer', x=78.31, y=48.00, z=210.25], EntitySpider['Spider'/382, l='MpServer', x=78.72, y=47.00, z=212.56], EntitySkeleton['Skeleton'/383, l='MpServer', x=79.50, y=42.00, z=224.50], EntitySpider['Spider'/384, l='MpServer', x=79.59, y=25.00, z=241.28], EntityCow['Cow'/385, l='MpServer', x=77.50, y=79.00, z=251.50], EntityCow['Cow'/386, l='MpServer', x=78.50, y=72.00, z=254.50], EntityCow['Cow'/387, l='MpServer', x=77.50, y=74.00, z=254.50], EntitySkeleton['Skeleton'/388, l='MpServer', x=72.50, y=21.00, z=256.50], EntitySkeleton['Skeleton'/398, l='MpServer', x=83.50, y=48.00, z=209.50], EntitySkeleton['Skeleton'/399, l='MpServer', x=81.69, y=42.00, z=225.69], EntityZombie['Zombie'/400, l='MpServer', x=89.68, y=42.00, z=229.06], EntityZombie['Zombie'/401, l='MpServer', x=81.69, y=42.00, z=223.41], EntitySkeleton['Skeleton'/402, l='MpServer', x=88.50, y=42.00, z=227.50], EntitySkeleton['Skeleton'/403, l='MpServer', x=89.50, y=42.00, z=227.50], EntityBat['Bat'/404, l='MpServer', x=81.09, y=24.00, z=252.25], EntityCow['Cow'/405, l='MpServer', x=80.50, y=68.00, z=254.50], EntityFallingBlock['Falling Block'/665, l='MpServer', x=58.50, y=3.49, z=279.50], EntityBat['Bat'/412, l='MpServer', x=125.38, y=45.00, z=226.94], EntityCow['Cow'/413, l='MpServer', x=116.50, y=103.00, z=225.50], EntityCow['Cow'/414, l='MpServer', x=119.50, y=115.00, z=230.22], EntityCow['Cow'/415, l='MpServer', x=117.19, y=114.00, z=232.50], EntityCow['Cow'/416, l='MpServer', x=117.03, y=114.00, z=228.91], EntityFallingBlock['Falling Block'/681, l='MpServer', x=55.50, y=4.49, z=279.50], EntityFallingBlock['Falling Block'/682, l='MpServer', x=56.50, y=5.49, z=279.50], EntityFallingBlock['Falling Block'/683, l='MpServer', x=54.50, y=4.49, z=279.50], EntityFallingBlock['Falling Block'/684, l='MpServer', x=54.50, y=4.49, z=278.50], EntityZombie['Zombie'/451, l='MpServer', x=107.50, y=21.00, z=306.50], EntityCreeper['Creeper'/253, l='MpServer', x=43.50, y=15.00, z=287.50]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

mods:

Mo Villages
Optifine
Village Info
Too many items
