### ISSUE TITLE
Crash on enderIo when starting up Minecraft

### ISSUE THREAD

**Issue by builderbrick** [SleepyTrousers/EnderIO#1370]
Heres the log:

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/8/14 2:23 PM
Description: Initializing game

java.lang.IllegalArgumentException: ID is already registered: 3
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
    at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
    at enviromine.handlers.ObjectHandler.registerEntities(ObjectHandler.java:177)
    at enviromine.core.EnviroMine.preInit(EnviroMine.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
    at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
    at enviromine.handlers.ObjectHandler.registerEntities(ObjectHandler.java:177)
    at enviromine.core.EnviroMine.preInit(EnviroMine.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 228441992 bytes (217 MB) / 731906048 bytes (698 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_U_B1 88 mods loaded, 88 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized
    AppleCore{1.0.1} [AppleCore](AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16 %283%29.jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.0rc8} [Big Reactors](BigReactors-0.4.0rc8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{5.0.7} [BuildCraft](buildcraft-5.0.7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{5.0.7} [BC Builders](buildcraft-5.0.7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{5.0.7} [BC Energy](buildcraft-5.0.7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{5.0.7} [BC Factory](buildcraft-5.0.7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{5.0.7} [BC Transport](buildcraft-5.0.7.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{5.0.7} [BC Silicon](buildcraft-5.0.7.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized
    ElementalCreepers{4.2.4} [Elemental Creepers](Elemental Creepers-universal_1.7.10-4.2.4.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC5} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.2.1.276} [Ender IO](EnderIO-1.7.10-2.2.1.276 %281%29.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.628-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.2.0.5} [Forestry for Minecraft](forestry_1.7.10-3.2.0.5.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.4.0.0} [Railcraft](Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
    emashercore{1.3.0.0} [ET Resources](EngineersToolbox-1.2.0.0-BETA.jar) Unloaded->Constructed->Pre-initialized
    emasherdefense{1.3.0.0} [ET Defense](EngineersToolbox-1.2.0.0-BETA.jar) Unloaded->Constructed->Pre-initialized
    eng_toolbox{1.2.0.0} [Engineer's Toolbox](EngineersToolbox-1.2.0.0-BETA.jar) Unloaded->Constructed->Pre-initialized
    gascraft{2.1.0.0} [GasCraft](EngineersToolbox-1.2.0.0-BETA.jar) Unloaded->Constructed->Pre-initialized
    enviromine{1.3.60} [EnviroMine](EnviroMine-v1.3.60.jar) Unloaded->Constructed->Errored
    exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
    flansmod{4.8.0} [Flan's Mod](Flans Mod-1.7.10-4.8.0.jar) Unloaded->Constructed->Pre-initialized
    FoodPlus{3.0rS} [§bFood Plus](Food-Plus-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized
    HungerOverhaul{1.7.10-beta.2.jenkins30} [Hunger Overhaul](HungerOverhaul-1.7.10-beta.2.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    Mekanism{7.1.1} [Mekanism](Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
    MekanismGenerators{7.1.1} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
    MekanismTools{7.1.1} [MekanismTools](MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC5} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC4} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC5} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC4} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC4} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC5} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC4} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC4} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC4} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC4} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC4} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC4} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC4} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC5} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC4} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC5} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC5} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-512.jar) Unloaded->Constructed->Pre-initialized
    PneumaticCraft{1.2.6} [PneumaticCraft](PneumaticCraft-1.2.6.jar) Unloaded->Constructed->Pre-initialized
    PowerConverters{1.7.10-3.0.2.38} [Power Converters](PowerConverters-1.7.10-3.0.2.38.jar) Unloaded->Constructed->Pre-initialized
    ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    SpecialMobs{3.0.3} [Special Mobs](SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized
    SpiceOfLife{1.2.2} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed->Pre-initialized
    UtilityMobs{3.1.1} [Utility Mobs](UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 650/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by kaylojames** [comment]
Actually it's just an entity ID conflict. Either delete the enviromine.cfg and let it regenerate, or scroll down to [I:"EntityPhysicsBlock ID"=] and change it to a number that isn't taken. Try 5.

**Comment by tterrag1098** [comment]
Entity IDs are dynamic and should not be config options. Unnecessary.

**Comment by tterrag1098** [comment]
Not saying you don't have to do it, just saying the author of Enviromine should change how he does things.
