### ISSUE TITLE
Dark Steel Axe - Causes server crash if shift-click on invalid items

### ISSUE THREAD

**Issue by morgue888** [SleepyTrousers/EnderIO#1978]
It seems whenever you shift-click something that was not intended to be "axed" it will crash the server.
One example is a bibliocraft tool rack. Crash report below.
Another example was when I made a wood stack 4 high in my base cobblestone(chisel 2 chiseled) above and below. Shift-clicking the wood crashed the server as well.

My best guess is some sort of a handler for when an item is not valid for the "activated mode" of the axe isn't working or isn't present. 

Description: Exception in server tick loop

java.lang.NoSuchMethodError: crazypants.enderio.item.darksteel.ItemDarkSteelPickaxe.doRightClickItemPlace(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;IIIIFFF)Z
	at crazypants.enderio.item.darksteel.ItemDarkSteelAxe.func_77648_a(ItemDarkSteelAxe.java:178)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by morgue888** [comment]
Possibly related?
#1972

**Comment by Didr** [comment]
I get this too, using FTB Infinity. I've had it happening with the axe and the pickaxe, usually while rightclicking a piston but also Carpenter's Door. To my knowledge I am not using Cauldron, though.

**Comment by HenryLoenwind** [comment]
fixed in #1895
