### ISSUE TITLE
(Wither) Skeleton spawner spawns "infinite wither skeletons"

### ISSUE THREAD

**Issue by Lunatrius** [SleepyTrousers/EnderIO#2027]
http://puu.sh/ggYlZ.mp4

Steps to reproduce (on 1.7.10-2.2.8.352):
 * grab a vanilla skeleton spawner (the wither skeleton spawner from NEI is not affected)
 * place it down inside a nether fortress
 * watch the entity count rise 20/second, until Minecraft can't handle it anymore

**Comment by tterrag1098** [comment]
Apparently the entity inside the spawner actually fires an EntityJoinWorldEvent on the client *every tick*. I probably shouldn't have been reacting on the client anyways, but still seems like stupid behavior by vanilla (not really surprised).

**Comment by Lunatrius** [comment]
Interesting. Could be that caused by the fact that `AllowDespawn` extends `LivingSpawnEvent`? That event is fired every tick for living entities. Not sure if the monster in the spawner counts as one.

**Comment by tterrag1098** [comment]
Nope, I never got that event. Only the EntityJoinWorldEvent

**Comment by tterrag1098** [comment]
Probably lazy mojang code constructing a new entity every frame for the render

**Comment by tterrag1098** [comment]
`Entity entity = EntityList.createEntityByName(this.getEntityNameToSpawn(), (World)null);` on line 355 of MobSpawnerBaseLogic

**Comment by Jkysler** [comment]
![2015-03-01_00 50 54](https://cloud.githubusercontent.com/assets/7318007/6432784/78b8686a-c023-11e4-83fe-57bec1acb366.png)
This is just having the chunk loaded because of a pump. Damn Nether Fortresses...

**Comment by MastaC729** [comment]
So to clarify, is there no way of fixing this issue? I am getting the same problem, and when I go to disable the creation of a unique entity ID for wither skeletons, it screws with the entity list and corrupts the spawning of blizzes. This is what my stacktrace looks like in the server console:

[20:57:08] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:2]
        at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(Entity]
        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:6]
        at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.cla]
        at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) []
        at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.cl]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIO]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIO]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(Asynch]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(Asy]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(Chun]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderS]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProvid]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProvid]
        at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
        at net.minecraft.world.SpawnerAnimals.func_151350_a(SpawnerAnimals.java]
        at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161) []
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.ja]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicate]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.ja]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) []
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:1]
        ... 24 more

**Comment by Namikon** [comment]
I also want to ask about this, as Ender IO won't receive any updates soon (Or is 2.3 already "ready to go soon" ?), is there a jenkins build that includes this fix? 
At the moment it's impossible to raid any dungeons in the nether.
