### ISSUE TITLE
Capacitor Bank crash - Exception while updating neighbours

### ISSUE THREAD

**Issue by Kellador** [SleepyTrousers/EnderIO#2070]
Encountered the following exception when a Capacitor Bank was placed directly adjacent to rails, as soon as a cart enters the adjacent rail this exception is thrown, this has been replicable and we've been using version 2.2.8.349 on the Infinity pack version 1.2.1.
```
Time: 10/03/15 16:45
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.block.BlockRail.func_150048_a(SourceFile:31)
	at net.minecraft.block.BlockRailBase.func_149695_a(BlockRailBase.java:154)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at crazypants.enderio.machine.capbank.TileCapBank.setIoMode(TileCapBank.java:286)
	at crazypants.enderio.machine.capbank.TileCapBank.validateModeForReceptor(TileCapBank.java:579)
	at crazypants.enderio.machine.capbank.TileCapBank.updateReceptors(TileCapBank.java:534)
	at crazypants.enderio.machine.capbank.TileCapBank.getReceptors(TileCapBank.java:517)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.addMember(CapBankNetwork.java:167)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.setNetwork(CapBankNetwork.java:112)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.init(CapBankNetwork.java:96)
	at crazypants.enderio.machine.capbank.network.NetworkUtil.ensureValidNetwork(NetworkUtil.java:27)
	at crazypants.enderio.machine.capbank.TileCapBank.updateNetwork(TileCapBank.java:219)
	at crazypants.enderio.machine.capbank.TileCapBank.func_145845_h(TileCapBank.java:183)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.BlockRail.func_150048_a(SourceFile:31)
	at net.minecraft.block.BlockRailBase.func_149695_a(BlockRailBase.java:154)

-- Block being updated --
Details:
	Source block type: ID #-1
	Block type: ID #66 (tile.rail // net.minecraft.block.BlockRail)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-263,125,-549), Chunk: (at 9,7,11 in -17,-35; contains blocks -272,0,-560 to -257,255,-545), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at crazypants.enderio.machine.capbank.TileCapBank.setIoMode(TileCapBank.java:286)
	at crazypants.enderio.machine.capbank.TileCapBank.validateModeForReceptor(TileCapBank.java:579)
	at crazypants.enderio.machine.capbank.TileCapBank.updateReceptors(TileCapBank.java:534)
	at crazypants.enderio.machine.capbank.TileCapBank.getReceptors(TileCapBank.java:517)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.addMember(CapBankNetwork.java:167)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.setNetwork(CapBankNetwork.java:112)
	at crazypants.enderio.machine.capbank.network.CapBankNetwork.init(CapBankNetwork.java:96)
	at crazypants.enderio.machine.capbank.network.NetworkUtil.ensureValidNetwork(NetworkUtil.java:27)
	at crazypants.enderio.machine.capbank.TileCapBank.updateNetwork(TileCapBank.java:219)
	at crazypants.enderio.machine.capbank.TileCapBank.func_145845_h(TileCapBank.java:183)

-- Block entity being ticked --
Details:
	Name: blockCapBankTileEntity // crazypants.enderio.machine.capbank.TileCapBank
	Block type: ID #1554 (tile.blockCapBank // crazypants.enderio.machine.capbank.BlockCapBank)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-263,125,-548), Chunk: (at 9,7,12 in -17,-35; contains blocks -272,0,-560 to -257,255,-545), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Actual block type: ID #1554 (tile.blockCapBank // crazypants.enderio.machine.capbank.BlockCapBank)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world_server
	All players: 3 total; [EntityPlayerMP['II_Casp_II'/71184, l='world_server', x=-261.49, y=125.20, z=-541.37], EntityPlayerMP['acialwip'/114930, l='world_server', x=-47.70, y=94.00, z=-29.71], EntityPlayerMP['Alcatsa'/863, l='world_server', x=-262.56, y=125.20, z=-544.89]]
	Chunk stats: ServerChunkCache: 635 Drop: 0
	Level seed: -1121425043727637773
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by hron84** [comment]
Do you have Railcraft installed?

**Comment by tterrag1098** [comment]
I second @hron84's question, a modlist would be nice.

**Comment by tterrag1098** [comment]
Nevermind, found the issue.
