### ISSUE TITLE
Upon installing the newest update, I recieve a crash.

### ISSUE THREAD

**Issue by dogman035** [SleepyTrousers/EnderIO#2085]
I keep getting a crash, upon attempting to load the game... Something about conduit bundles...

And it doesn't happen, when I don't have the mod installed... so...

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/13/15 12:57 AM
Description: Initializing game

java.lang.NoClassDefFoundError: Lcrazypants/enderio/conduit/BlockConduitBundle;
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
    at java.lang.Class.getDeclaredField(Class.java:2060)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduit.BlockConduitBundle
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
Caused by: java.lang.NoClassDefFoundError: powercrystals/minefactoryreloaded/api/rednet/IRedNetOmniNode
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
Caused by: java.lang.ClassNotFoundException: powercrystals.minefactoryreloaded.api.rednet.IRedNetOmniNode
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
    at java.lang.Class.getDeclaredField(Class.java:2060)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:43)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 142938224 bytes (136 MB) / 366231552 bytes (349 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1272 Minecraft Forge 10.13.2.1272 Optifine OptiFine_1.7.10_HD_B1 128 mods loaded, 128 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.85.1272} [Forge Mod Loader](forge-1.7.10-10.13.2.1272.jar) Unloaded->Constructed
    Forge{10.13.2.1272} [Minecraft Forge](forge-1.7.10-10.13.2.1272.jar) Unloaded->Constructed
    appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed
    battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
    StartingInventory{1.7.10.r03} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r03.jar) Unloaded->Constructed
    Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed
    AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed
    arsmagica2{1.4.0.005} [Ars Magica 2](AM2-1.4.0.006.jar) Unloaded->Constructed
    appliedenergistics2{rv2-beta-8} [Applied Energistics 2](appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed
    BattleTowers{1.5.1} [Battle Towers](BattleTowers-1.7.10.jar) Unloaded->Constructed
    BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed
    AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0b-3.jar) Unloaded->Constructed
    WaslieCore{1.1} [WaslieCore](WaslieCore-1.1_B44.jar) Unloaded->Constructed
    BloodUtils{1.4} [BloodUtils](BloodUtils-1.4_B0.jar) Unloaded->Constructed
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
    Thaumcraft{4.2.3.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.4.jar) Unloaded->Constructed
    Botania{r1.4-155} [Botania](Botania r1.4-155.jar) Unloaded->Constructed
    BuildCraft|Core{5.0.7} [BuildCraft](buildcraft-5.0.7.jar) Unloaded->Constructed
    BuildCraft|Builders{5.0.7} [BC Builders](buildcraft-5.0.7.jar) Unloaded->Constructed
    BuildCraft|Energy{5.0.7} [BC Energy](buildcraft-5.0.7.jar) Unloaded->Constructed
    BuildCraft|Factory{5.0.7} [BC Factory](buildcraft-5.0.7.jar) Unloaded->Constructed
    BuildCraft|Transport{5.0.7} [BC Transport](buildcraft-5.0.7.jar) Unloaded->Constructed
    BuildCraft|Silicon{5.0.7} [BC Silicon](buildcraft-5.0.7.jar) Unloaded->Constructed
    CarpentersBlocks{3.3.4} [Carpenter's Blocks](Carpenter's Blocks v3.3.4 - MC 1.7.10.jar) Unloaded->Constructed
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
    chisel{2.3.5.31} [Chisel 2](Chisel2-2.3.5.31.jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.0RC5} [CoFH Core](CoFHCore-[1.7.10]3.0.0RC5-207.jar) Unloaded->Errored
    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed
    MineFactoryReloaded{1.7.10R2.8.0RC8} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Errored
    EnderIO{1.7.10-2.2.8.349} [Ender IO](EnderIO-1.7.10-2.2.8.349.jar) Unloaded
    EnderStorage{1.4.5.27} [EnderStorage](EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded
    EnderZoo{1.7.10-1.0.9.18} [Ender Zoo](EnderZoo-1.7.10-1.0.9.18.jar) Unloaded
    exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded
    ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded
    ThermalExpansion{1.7.10R4.0.0RC6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0RC6-138.jar) Unloaded
    Waila{1.5.8} [Waila](Waila-1.5.8a_1.7.10.jar) Unloaded
    TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct](TConstruct-1.7.10-1.8.2a.jar) Unloaded
    Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) Unloaded
    IC2{2.2.668-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.668-experimental.jar) Unloaded
    RedstoneArsenal{1.7.10R1.1.0RC4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0RC4-54.jar) Unloaded
    exastris{1.15} [Ex Astris](Ex-Astris-1.15.jar) Unloaded
    ExtrabiomesXL{3.16.0} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.0.jar) Unloaded
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded
    ForbiddenMagic{1.7.10-0.552} [Forbidden Magic](Forbidden Magic-1.7.10-0.552.jar) Unloaded
    GalacticraftCore{3.0.9} [Galacticraft Core](GalacticraftCore-1.7-3.0.9.294.jar) Unloaded
    GalacticraftMars{3.0.9} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.9.294.jar) Unloaded
    HardcoreEnderExpansion{1.6.7} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.6.7.jar) Unloaded
    iChunUtil{4.1.3} [iChunUtil](iChunUtil-4.1.3.jar) Unloaded
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded
    JABBA{1.2.0a} [JABBA](Jabba-1.2.0a_1.7.10.jar) Unloaded
    lycanitesmobs{1.10.10.1 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    arcticmobs{1.10.10.1 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    demonmobs{1.10.10.1 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    desertmobs{1.10.10.1 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    forestmobs{1.10.10.1 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    freshwatermobs{1.10.10.1 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    infernomobs{1.10.10.1 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    junglemobs{1.10.10.1 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    mountainmobs{1.10.10.1 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    plainsmobs{1.10.10.1 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    saltwatermobs{1.10.10.1 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    shadowmobs{1.10.10.1 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    swampmobs{1.10.10.1 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.10.10.1 [1.7.10].jar) Unloaded
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC8} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC8} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC8} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC8} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC8} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC8} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC8} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC8} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC8} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC8} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MrTJPCoreMod{1.0} [MrTJPCoreMod](MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded
    ProjRed|Core{4.5.8.59} [ProjectRed](ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded
    ProjRed|Exploration{4.5.8.59} [ProjectRed-Exploration](ProjectRed-1.7.10-4.5.8.59-World.jar) Unloaded
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC8} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC8} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC8} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC8} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC8} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC8} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC8} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC8} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC8} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded
    bettercraft{2.7.2} [MoreCraft](MoreCraft-1.7.10-2.7.2.jar) Unloaded
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded
    mowziesmobs{Alpha v0.1} [Mowzie's Mobs](Mowzie’s Mobs-1.0.0.jar) Unloaded
    cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) Unloaded
    MSM3{3.0.0d} [More Swords 3](MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) Unloaded
    notenoughkeys{@MOD_VERSION@} [NotEnoughKEys](NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6.jar) Unloaded
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3.jar) Unloaded
    ProjRed|Transmission{4.5.8.59} [ProjectRed-Transmission](ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded
    ProjRed|Transportation{4.5.8.59} [ProjectRed-Transportation](ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded
    ProjRed|Compatibility{4.5.8.59} [ProjectRed-Compatibility](ProjectRed-1.7.10-4.5.8.59-Compat.jar) Unloaded
    ProjRed|Integration{4.5.8.59} [ProjectRed-Integration](ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded
    ProjRed|Illumination{4.5.8.59} [ProjectRed-Illumination](ProjectRed-1.7.10-4.5.8.59-Lighting.jar) Unloaded
    ProjRed|Expansion{4.5.8.59} [ProjectRed-Expansion](ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded
    quartznsteel{2.0} [Quartz 'N' Steel](QuartzAndSteel-2.12.jar) Unloaded
    telepads{1.6.4 v5} [Teleportation Pads](Telepads-1.7.2_1.7.jar) Unloaded
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded
    thaumicenergistics{0.8.9.0b-rv2} [Thaumic Energistics](thaumicenergistics-0.8.9.0b-rv2.jar) Unloaded
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-34.jar) Unloaded
    thaumicinfusion{3.8.1} [Thaumic Infusion](ThaumicInfusion-1.7.10-3.83.jar) Unloaded
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded
    tinkersdefense{1.0} [Tinkers' Defense](Tinkers-Defense-1.1.jar) Unloaded
    TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.10.jar) Unloaded
    Torched{4.0.0} [Torched](Torched-4.0.0.jar) Unloaded
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded
    VersionChecker{1.1.8} [Version Checker](VersionChecker-1.1.8.jar) Unloaded
    wawla{1.1.1} [What Are We Looking At](Wawla-1.1.1_1.7.10.jar) Unloaded
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
    AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    CoFHCore: -[1.7.10]3.0.0RC5-207
    Launched Version: 1.7.10-Forge10.13.2.1272
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3412, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by dogman035** [comment]
Five years later lol

I don't even remember opening this...
