### ISSUE TITLE
gas conduits

### ISSUE THREAD

**Issue by Cracks777** [SleepyTrousers/EnderIO#2141]
Time: 3/21/15 12:28 PM
Description: Ticking block entity

java.lang.AbstractMethodError: crazypants.enderio.conduit.TileConduitBundle.receiveGas(Lnet/minecraftforge/common/util/ForgeDirection;Lmekanism/api/gas/GasStack;Z)I
	at mekanism.common.tile.TileEntityGasTank.onUpdate(TileEntityGasTank.java:84)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.tile.TileEntityGasTank.onUpdate(TileEntityGasTank.java:84)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)

-- Block entity being ticked --
Details:
	Name: GasTank // mekanism.common.tile.TileEntityGasTank
	Block type: ID #815 (tile.GasTank // mekanism.common.block.BlockGasTank)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (227,80,251), Chunk: (at 3,5,11 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #815 (tile.GasTank // mekanism.common.block.BlockGasTank)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by 6210classick** [comment]
are you using the new version of mekanism ? if so then wait for EIO update becuase as of the new update they do not work

**Comment by Cracks777** [comment]
yes it is the new version, do you have an eta on the update?

**Comment by 6210classick** [comment]
nope just "coming soon"
 you can downgrade to pre-8 Mekansim ,use mekansim cables until then it's not a high priority now so don't get your hopes up in the new 2.3 update the gas conduit  might be remove temporarily

**Comment by unpairedbracket** [comment]
I've added backwards-compatibility to our gas interfaces, which should stop these crashes unil you can update.

**Comment by Cracks777** [comment]
thank you

**Comment by Cracks777** [comment]
where can i find dev versions of ender io?

**Comment by 6210classick** [comment]
http://ci.tterrag.com/job/EnderIO/ ,, while it's relatively stable it's not recommended that you use dev versions in your serversor in your main SP world TAKE A BACKUP

**Comment by tterrag1098** [comment]
See #2110
