### ISSUE TITLE
Crash EnderIO-1.7.10-2.2.8.364

### ISSUE THREAD

**Issue by Pilad** [SleepyTrousers/EnderIO#2150]
[20:21:26] [Client thread/ERROR] [FML]: Caught exception from EnderIO
java.lang.NoClassDefFoundError: crazypants/enderio/conduit/IConduitBundle
	at crazypants.enderio.EnderIO.preInit(EnderIO.java:372) ~[EnderIO.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduit.IConduitBundle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	... 37 more
Caused by: java.lang.NoClassDefFoundError: mekanism/api/gas/IGasHandler
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	... 37 more
Caused by: java.lang.ClassNotFoundException: mekanism.api.gas.IGasHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	... 37 more
[20:21:27] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 23.03.15 20:21
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: crazypants/enderio/conduit/IConduitBundle
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: crazypants/enderio/conduit/IConduitBundle
	at crazypants.enderio.EnderIO.preInit(EnderIO.java:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.conduit.IConduitBundle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: mekanism/api/gas/IGasHandler
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: mekanism.api.gas.IGasHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more

**Comment by Cracks777** [comment]
Mine dont crash anymore but gas condiuts are not in the creative menu or in nei, but i had one in my inventory and this is that happens when i put them down.

http://www.mediafire.com/view/v985a0sy7jz69t7/gas_texture.jpg

**Comment by Cracks777** [comment]
i think they may have removed gas condiuts in this version.

**Comment by Cracks777** [comment]
6210classick commented a day ago
nope just "coming soon"
you can downgrade to pre-8 Mekansim ,use mekansim cables until then it's not a high priority now so don't get your hopes up in the new 2.3 update the gas conduit might be removed temporarily

**Comment by Cracks777** [comment]
![image](https://cloud.githubusercontent.com/assets/10608111/6782244/de68e40e-d140-11e4-86b2-0ebe6b375863.png)

**Comment by Cracks777** [comment]
its still works if you take a wrench and it it a bunch of times. lol

**Comment by Cracks777** [comment]
![image](https://cloud.githubusercontent.com/assets/10608111/6782297/3267568a-d141-11e4-8602-9c1edbf7d24c.png)

**Comment by Cracks777** [comment]
Pilad use the latest version of mek, i think thats your problem

**Comment by Pilad** [comment]
I have not installed this mod )))

**Comment by Cracks777** [comment]
the problem is if you dont have mek installed alongside enderio you get that crash? no clue.

**Comment by Brycey92** [comment]
Where do you even get EnderIO-1.7.10-2.2.8.364? The latest I can find is 349 on Curse.

**Comment by Cracks777** [comment]
http://ci.tterrag.com/job/EnderIO/

**Comment by BillH1949** [comment]
I don't have Mekanism installed and upon updating from 363 to 364 the game crashes immediately. Time to revert to 363 for the time being.

**Comment by tterrag1098** [comment]
See #2110
