### ISSUE TITLE
EnderIO Dimensional Transceiver error causes server crash/cant restart

### ISSUE THREAD

**Issue by cocopuffs99** [SleepyTrousers/EnderIO#2217]
In game sessions sometimes the server closes and goes to the MC menu screen, but when trying to restart the world from the menu screen it just resets back to the menu screen after clicking the save.  Please let me know if you find out how to fix! Thx.  So far the only way I found a workaround is restarting the whole MC game (another 10 min wait each time for loadup).

Server log:  http://paste.atlauncher.com/view/a6ac9716

 <spoiler>
    Error: [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue

[Server thread/ERROR] [FML]: The following problems were captured during this phase
[03/4/2015 10:03:13 AM] [Server thread/ERROR] [FML]: Caught exception from neresources
[03/4/2015 10:03:13 AM] java.lang.NullPointerException
[03/4/2015 10:03:13 AM]         at neresources.compatibility.Compatibility.init(Compatibility.java:25) ~[Compatibility.class:?]
[03/4/2015 10:03:13 AM]         at neresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:19) ~[CommonProxy.class:?]
[03/4/2015 10:03:13 AM] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
[03/4/2015 10:03:13 AM] java.lang.NullPointerException
[03/4/2015 10:03:13 AM]         at neresources.compatibility.Compatibility.init(Compatibility.java:25) ~[Compatibility.class:?]
[03/4/2015 10:03:13 AM]         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[03/4/2015 10:03:13 AM]         at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
[03/4/2015 10:03:13 AM] [Server thread/INFO] [FML]: Applying holder lookups
[03/4/2015 10:03:13 AM] [Server thread/INFO] [FML]: Holder lookups applied
[03/4/2015 10:03:13 AM] [10:03:13] [pool-5-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Trasciever data saved to **USERSDIR**\Instances\ResonantRise\saves\Milk and Cookies\enderio\dimensionalTransceiver.json
[03/4/2015 10:03:13 AM] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[03/4/2015 10:03:13 AM] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
  </spoiler>

**Comment by HenryLoenwind** [comment]
That is not an error, that is the normal shutdown message of the Transceiver. This is your erro:

[03/4/2015 10:03:13 AM] java.lang.NullPointerException
[03/4/2015 10:03:13 AM] at neresources.compatibility.Compatibility.init(Compatibility.java:25) ~[Compatibility.class:?]

**Comment by cocopuffs99** [comment]
Yes but when I try to restart it cycles that error over and over again and wont let me start MC.  Not sure  I understand.  Is there any way to turn off the error forcing shutdown and not letting me start a game? Thanks

**Comment by XFactHD** [comment]
No, you can't turn this off, it's a vanilla minecraft/jvm mechanic.
Your actual problem is an incompatibility.

**Comment by cocopuffs99** [comment]
Is there an incompatibility with EnderIO Dim Transceiver and something else? What might be the problem? Thats why I listed it here as a bug. Thanks guys

**Comment by XFactHD** [comment]
There is nothing wrong with the dimensional transceiver, the message in the log only tells you that all of the transceiver settings have been successfully saved, it's the same massage as in the forge log when closing Minecraft in a normal way.

**Comment by tterrag1098** [comment]
>[03/4/2015 10:03:13 AM] [Server thread/ERROR] [FML]: Caught exception from neresources
[03/4/2015 10:03:13 AM] java.lang.NullPointerException
[03/4/2015 10:03:13 AM] at neresources.compatibility.Compatibility.init(Compatibility.java:25) ~[Compatibility.class:?]
[03/4/2015 10:03:13 AM] at neresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:19) ~[CommonProxy.class:?]
[03/4/2015 10:03:13 AM] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
[03/4/2015 10:03:13 AM] java.lang.NullPointerException
[03/4/2015 10:03:13 AM] at neresources.compatibility.Compatibility.init(Compatibility.java:25) ~[Compatibility.class:?]
[03/4/2015 10:03:13 AM] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[03/4/2015 10:03:13 AM] at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]

You should probably look to NER as the source of the issue, the dim trans logging is completely normal.
