### ISSUE TITLE
Client disconnects when replaceWitherSkeletons is turned on on the server but not on the client

### ISSUE THREAD

**Issue by Thurion** [SleepyTrousers/EnderIO#2258]
When the option replaceWitherSkeletons is set to true and Botania's hard mode Gaia spirit is summoned, the client disconnects from the server as soon as the boss spawns wither skeletons.

Versions used: 
* EnderIO: 1.7.10-2.2.8.367
* Botania: r1.6-174

Got this from the client output:
```
[Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel FML
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 28 at ( 964.46875,68.0, 940.53125) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

**Comment by MatthiasMann** [comment]
Is there more in the log?

**Comment by Thurion** [comment]
Yes there are a few other exceptions. I attached all thrown exceptions of the client and the entry of the FML server log when I tried to reconnect.

### Client
````
01:46:05] [Client thread/ERROR] [FML]: EntitySpawnHandler exception
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 28 at ( 963.53125,71.5, 945.8125) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[01:46:05] [Client thread/ERROR] [FML]: OpenGuiHandler exception
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 28 at ( 963.53125,71.5, 945.8125) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[01:46:05] [Client thread/ERROR] [FML]: HandshakeCompletionHandler exception
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 28 at ( 963.53125,71.5, 945.8125) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[01:46:05] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel FML
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 28 at ( 963.53125,71.5, 945.8125) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

´´´´

### Server
´´´´
[01:49:58] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[01:50:18] [Netty IO #3/TRACE] [FML/]: $ClientHello->FMLHandshakeServerState$2:HELLO
[01:50:18] [Netty IO #3/INFO] [FML/]: Client protocol version 2
[01:50:18] [Netty IO #3/TRACE] [FML/]: $ModList:150 mods->FMLHandshakeServerState$2:HELLO
[01:50:18] [Netty IO #3/INFO] [FML/]: Client attempting to join with 150 mods : MineFactoryReloaded|CompatExtraBiomes@1.7.10R2.8.0RC8,BuildCraft|Silicon@6.4.5,ForgeMicroblock@1.1.1.324,iChunUtil@4.1.3,ExtraBees@2.0-pre8,ThaumicExploration@0.6.0,EnderZoo@1.7.10-1.0.10.25,MineFactoryReloaded|CompatTwilightForest@1.7.10R2.8.0RC8,MagicBees@1.7.10-2.1.31,InfiniBows@1.3.0 build 20,Botany@2.0-pre8,ProjRed|Integration@4.5.15.75,GardenContainers@1.7.10-1.5.6,Mystcraft@0.11.3.00,bspkrsCore@6.16,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.0RC8,McMultipart@1.1.1.324,BiomesOPlenty@2.1.0,ExtraUtilities@1.2.3,Railcraft@9.5.0.0,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.0RC8,WR-CBE|Addons@1.4.1.9,MineFactoryReloaded|CompatForestry@1.7.10R2.8.0RC8,IC2NuclearControl@2.1.2a,ThermalFoundation@1.7.10R1.0.0RC7,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.0RC8,ForgeMultipart@1.1.1.324,StevesCarts@2.0.0.b18,RedstoneArsenal@1.7.10R1.1.0RC7,CoFHCore@1.7.10R3.0.0RC7,powersuits@0.11.0.178,BiblioWoodsForestry@1.7,FastCraft@1.21,OpenPeripheral@0.3,Forge@10.13.3.1355,ExtraTrees@2.0-pre8,GardenTrees@1.7.10-1.5.6,StorageDrawers@1.7.10-1.3.6,ThaumicTinkerer@unspecified,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.0RC8,BuildCraft|Energy@6.4.5,IC2@2.2.695-experimental,JABBA@1.2.1,MineFactoryReloaded|CompatMystcraft@1.7.10R2.8.0RC8,MineFactoryReloaded|CompatIC2@1.7.10R2.8.0RC8,minechem@5.0.5.394,IguanaTweaksTConstruct@1.7.10-2.1.4.132,FML@7.10.103.1355,Natura@2.2.0,NEIAddons|Forestry@1.12.5.17,TiCTooltips@1.2.3,magicalcrops@1.7.2 - 0.1 ALPHA,NotEnoughCodecs@0.3,BiblioWoodsNatura@1.5,<CoFH ASM>@000,NEIAddons|CraftingTables@1.12.5.17,NEIAddons|ExNihilo@1.12.5.17,ArmorStatusHUD@1.28,WailaHarvestability@1.1.2,ThermalDynamics@1.7.10R1.0.0RC8,ProjRed|Illumination@4.5.15.75,TMechworks@0.2.14.100,Botania@r1.6-174,NotEnoughItems@1.0.4.90,Thaumcraft@4.2.3.5,Waila@1.5.10,ProjRed|Compatibility@4.5.15.75,TConstruct@1.7.10-1.8.3.build919,StatusEffectHUD@1.27,StevesFactoryManager@A93,appliedenergistics2-core@rv2-beta-24,NEIAddons@1.12.5.17,BinnieCore@2.0-pre8,inpure|core@1.7.10R1.0.0B9,OpenEye@0.6,BiblioCraft@1.10.2,BuildCraft|Core@6.4.5,OpenModsCore@0.7,act@0.0.2a_1.7.10,notenoughkeys@@MOD_VERSION@,Genetics@2.0-pre8,mcp@9.05,FlatSigns@2.1.0.19,Mantle@1.7.10-0.3.2.jenkins184,ProjRed|Transmission@4.5.15.75,GardenCore@1.7.10-1.5.6,GardenStuff@1.7.10-1.5.6,journeymap@5.0.1,appliedenergistics2@rv2-beta-24,thaumcraftneiplugin@1.7.10-1.7,WR-CBE|Logic@1.4.1.9,MineFactoryReloaded|CompatAtum@1.7.10R2.8.0RC8,OpenPeripheralIntegration@0.2,MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.0RC8,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.0RC8,DraconicEvolution@1.0.0e,WR-CBE|Core@1.4.1.9,MobiusCore@1.2.3,inventorytweaks@1.59-dev-156-af3bc68,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.0RC8,Morpheus@1.7.10-1.5.26,ThermalExpansion@1.7.10R4.0.0RC7,CompactSolars@4.4.39.315,TwilightForest@2.3.5,BuildCraft|Factory@6.4.5,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.0RC8,AgriCraft@1.7.10-1.3.1,OpenPeripheralCore@1.0,OpenBlocks@1.4,PowerConverters@1.7.10-3.0.4.47,EnderStorage@1.4.5.27,ForbiddenMagic@1.7.10-0.562,EnderTech@1.7.10-0.3.0.364,MineFactoryReloaded|CompatSufficientBiomes@1.7.10R2.8.0RC8,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.0RC8,CarpentersBlocks@3.3.5,MineFactoryReloaded@1.7.10R2.8.0RC8,EnderIO@1.7.10-2.2.8.367,BuildCraft|Compat@6.4.0,Translocator@1.1.1.14,ComputerCraft@1.73,HelpFixer@1.0.7,funkylocomotion@1.0,neiintegration@1.0.7,AWWayofTime@v1.3.1,MrTJPCoreMod@1.0.5.11,IronChest@6.0.62.742,NEIAddons|Botany@1.12.5.17,MineFactoryReloaded|CompatThermalExpansion@1.7.10R2.8.0RC8,numina@0.4.0.100,CodeChickenCore@1.0.4.35,BigReactors@0.4.2A2,ChickenChunks@1.3.4.17,MineTweaker3@3.0.9B,ThaumicTinkerer-preloader@0.1,aobd@2.5.0,MineMenu@1.2.0,BuildCraft|Transport@6.4.5,chisel@2.3.7.34,Baubles@1.0.1.10,BetterTitleScreen@1.7.10-1.1,ProjRed|Core@4.5.15.75,MineFactoryReloaded|CompatRP2@1.7.10R2.8.0RC8,ProjRed|Exploration@4.5.15.75,Forestry@3.5.0.8,OpenMods@0.7,BiblioWoodsBoP@1.9,BuildCraft|Builders@6.4.5,MineFactoryReloaded|CompatBackTools@1.7.10R2.8.0RC8,ObsidiPlates@3.0.0.18
[01:50:18] [Netty IO #3/INFO] [FML/]: Attempting connection with missing mods [JourneyMapServer] at CLIENT
[01:50:18] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{2}->FMLHandshakeServerState$3:WAITINGCACK
[01:50:18] [Netty IO #3/INFO] [OpenMods/]: openmods.network.IdSyncManager$InboundHandler.userEventTriggered(IdSyncManager.java:50): Sending id data for player: EntityPlayerMP['<PLAYER>'/5004, l='world', x=991.50, y=63.00, z=1032.50]
[01:50:19] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{3}->FMLHandshakeServerState$4:COMPLETE
[01:50:19] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{4}->FMLHandshakeServerState$5:DONE
[01:50:19] [Server thread/INFO] [FML/]: [Server thread] Server side modded connection established
[01:50:19] [Server thread/INFO] [MineMenu/]: SERVER: MineMenu is installed. Sending server response packet
[01:50:19] [Server thread/DEBUG] [NotEnoughItems/]: Loading Player: <PLAYER>
[01:50:19] [Server thread/DEBUG] [NotEnoughItems/]: Sending serverside check to: <PLAYER>
[01:50:19] [Server thread/INFO] [Waila/]: Player EntityPlayerMP['<PLAYER>'/5004, l='world', x=956.33, y=68.00, z=945.34] connected. Sending ping
[01:50:19] [Netty IO #3/TRACE] [FML/]: $HandshakeAck:{5}->FMLHandshakeServerState$5:DONE
[01:50:20] [Thread-10/INFO] [JourneyMapServer/]: Login: Sending WorldID Packet to <PLAYER>
[01:50:21] [Server thread/INFO] [JourneyMapServer/]: On Request: Sending WorldID packet to: <PLAYER>
[01:50:21] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: <PLAYER>
````

**Comment by Thurion** [comment]
I found the source of the problem:
I switched the option replaceWitherSkeletons on on the server but not on the client.

Is it possible to check if there is a configuration mismatch before connecting?

**Comment by tterrag1098** [comment]
No, not really. Also, not a bug, configs must be synced.
