### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by a810587921** [SleepyTrousers/EnderIO#2265]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 15-4-9 上午1:40
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
at cofh.thermalexpansion.block.device.TileActivator.getNextStackIndex(TileActivator.java:249)
at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:209)
at cofh.thermalexpansion.block.device.TileActivator.onRedstoneUpdate(TileActivator.java:155)
at cofh.thermalexpansion.block.TileRSControl.onNeighborBlockChange(TileRSControl.java:37)
at cofh.core.block.BlockCoFHBase.func_149695_a(BlockCoFHBase.java:180)
at net.minecraft.world.World.func_147460_e(World.java:1073)
at net.minecraft.world.World.func_147459_d(World.java:1010)
at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyConduitNeighbours(RedstoneConduitNetwork.java:186)
at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyNeigborsOfSignalUpdate(RedstoneConduitNetwork.java:174)
at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.destroyNetwork(RedstoneConduitNetwork.java:51)
at crazypants.enderio.conduit.AbstractConduit.onChunkUnload(AbstractConduit.java:373)
at crazypants.enderio.conduit.TileConduitBundle.onChunkUnload(TileConduitBundle.java:221)
at net.minecraft.world.World.func_72939_s(World.java:2462)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Unknown Source)

EnderIO Version: 2.2.8.367

**Comment by TheJulianJES** [comment]
Update Thermal Expansion

**Comment by tterrag1098** [comment]
#2166
