### ISSUE TITLE
Vat crashes with  EnderIO-1.7.10-2.3.0.372

### ISSUE THREAD

**Issue by OldOpa** [SleepyTrousers/EnderIO#2305]
Since I don't have a other way to show the crash report:

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at crazypants.enderio.machine.vat.PacketVatProgress.<init>(PacketVatProgress.java:43)
	at crazypants.enderio.machine.vat.TileVat.sendTaskProgressPacket(TileVat.java:196)
	at crazypants.enderio.TileEntityEio.func_145845_h(TileEntityEio.java:42)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at crazypants.enderio.machine.vat.PacketVatProgress.<init>(PacketVatProgress.java:43)
	at crazypants.enderio.machine.vat.TileVat.sendTaskProgressPacket(TileVat.java:196)
	at crazypants.enderio.TileEntityEio.func_145845_h(TileEntityEio.java:42)

-- Block entity being ticked --
Details:
	Name: blockVatTileEntity // crazypants.enderio.machine.vat.TileVat
	Block type: ID #602 (tile.blockVat // crazypants.enderio.machine.vat.BlockVat)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (243,96,-117), Chunk: (at 3,6,11 in 15,-8; contains blocks 240,0,-128 to 255,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #602 (tile.blockVat // crazypants.enderio.machine.vat.BlockVat)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['PROF_Opa'/256, l='MpServer', x=242,01, y=105,04, z=-123,01]]
	Chunk stats: MultiplayerChunkCache: 15, 15
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (254,103,-122), Chunk: (at 14,6,6 in 15,-8; contains blocks 240,0,-128 to 255,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 52516879 game time, 52814186 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntityXPOrb['Experience Orb'/128, l='MpServer', x=240,69, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/129, l='MpServer', x=241,02, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/130, l='MpServer', x=240,75, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/131, l='MpServer', x=240,59, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/132, l='MpServer', x=240,49, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/133, l='MpServer', x=240,71, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/134, l='MpServer', x=240,61, y=96,04, z=-125,75], EntityAspectOrb['Aspect Orb'/135, l='MpServer', x=243,41, y=96,06, z=-127,94], EntityPigZombie['Zombie Pigman'/263, l='MpServer', x=243,36, y=97,52, z=-124,42], EntityAspectOrb['Aspect Orb'/136, l='MpServer', x=241,94, y=96,06, z=-127,94], EntityItem['item.tile.tsteelworks.blocks.charcoal'/264, l='MpServer', x=242,50, y=132,10, z=-117,50], EntityWitch['Witch'/137, l='MpServer', x=240,31, y=96,06, z=-127,69], EntityWitch['Witch'/138, l='MpServer', x=242,31, y=96,00, z=-123,96], EntityWitch['Witch'/267, l='MpServer', x=242,31, y=97,52, z=-124,71], EntityAspectOrb['Aspect Orb'/140, l='MpServer', x=241,07, y=96,06, z=-126,50], EntityWitch['Witch'/268, l='MpServer', x=242,00, y=96,00, z=-125,56], EntityAspectOrb['Aspect Orb'/141, l='MpServer', x=240,94, y=97,88, z=-126,06], EntityClientPlayerMP['PROF_Opa'/256, l='MpServer', x=242,01, y=105,04, z=-123,01], EntityItem['item.tile.tsteelworks.blocks.charcoal'/145, l='MpServer', x=242,50, y=111,14, z=-117,50], EntityItem['item.tile.tsteelworks.blocks.charcoal'/147, l='MpServer', x=242,50, y=125,07, z=-117,50], EntityPig['Pig'/160, l='MpServer', x=257,28, y=75,00, z=-133,19], EntitySkeleton['Skeleton'/161, l='MpServer', x=257,50, y=75,00, z=-131,50], EntitySkeleton['Skeleton'/162, l='MpServer', x=265,50, y=72,00, z=-91,50], EntityChicken['Chicken'/99, l='MpServer', x=228,47, y=72,00, z=-134,69], EntityItem['item.item.feather'/100, l='MpServer', x=227,94, y=67,13, z=-138,88], EntityItem['item.item.egg'/101, l='MpServer', x=234,78, y=78,13, z=-135,38], EntityChicken['Chicken'/102, l='MpServer', x=234,81, y=83,00, z=-130,56], EntityChicken['Chicken'/103, l='MpServer', x=234,19, y=83,00, z=-130,25], EntityPigZombie['Zombie Pigman'/104, l='MpServer', x=238,69, y=94,00, z=-130,31], EntityWitch['Witch'/105, l='MpServer', x=232,13, y=83,00, z=-129,78], EntityPigZombie['Zombie Pigman'/106, l='MpServer', x=236,69, y=86,00, z=-130,31], EntityPigZombie['Zombie Pigman'/107, l='MpServer', x=237,69, y=87,00, z=-130,34], EntityPigZombie['Zombie Pigman'/108, l='MpServer', x=237,69, y=85,00, z=-131,31], EntityItem['item.tile.sapling.oak'/109, l='MpServer', x=239,13, y=108,13, z=-111,13], EntityCreeper['Creeper'/117, l='MpServer', x=252,50, y=75,00, z=-133,69], EntityPech['Pech Forager'/118, l='MpServer', x=249,47, y=75,00, z=-131,75], EntityPig['Pig'/119, l='MpServer', x=253,13, y=77,00, z=-132,66], EntityCow['Cow'/120, l='MpServer', x=250,78, y=75,00, z=-131,66], EntityPig['Pig'/121, l='MpServer', x=254,53, y=75,00, z=-130,63], EntityCreeper['Creeper'/122, l='MpServer', x=249,50, y=75,00, z=-124,78], EntityPech['Grim Pech Forager'/123, l='MpServer', x=250,47, y=75,00, z=-123,47], EntityPig['Pig'/124, l='MpServer', x=254,41, y=75,00, z=-127,16], EntityXPOrb['Experience Orb'/125, l='MpServer', x=240,93, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/126, l='MpServer', x=240,54, y=96,04, z=-125,75], EntityXPOrb['Experience Orb'/127, l='MpServer', x=240,75, y=96,04, z=-125,75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by OldOpa** [comment]
Closed due dupe with issue #2302
