### ISSUE TITLE
Crash with Mekanism after placing Gas Conduit

### ISSUE THREAD

**Issue by Pctg-x8** [SleepyTrousers/EnderIO#2348]
Crash Report:

    Description: Ticking block entity
    
    java.lang.AbstractMethodError: crazypants.enderio.conduit.TileConduitBundle.receiveGas(Lnet/minecraftforge/common/util/ForgeDirection;Lmekanism/api/gas/GasStack;Z)I
    	at  mekanism.common.tile.TileEntityElectrolyticSeparator.onUpdate(TileEntityElectrolyticSeparator.java:227)
    	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
    	at net.minecraft.world.World.func_72939_s(World.java:1939)
    	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- Head --
    Stacktrace:
    	at mekanism.common.tile.TileEntityElectrolyticSeparator.onUpdate(TileEntityElectrolyticSeparator.java:227)
    	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
    
    -- Block entity being ticked --
    Details:
    	Name: ElectrolyticSeparator // mekanism.common.tile.TileEntityElectrolyticSeparator
    	Block type: ID #855 (tile.MachineBlock2 // mekanism.common.block.BlockMachine)
    	Block data value: 4 / 0x4 / 0b0100
    	Block location: World: (188,65,1011), Chunk: (at 12,4,3 in 11,63; contains blocks 176,0,1008 to 191,255,1023), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    	Actual block type: ID #855 (tile.MachineBlock2 // mekanism.common.block.BlockMachine)
    	Actual block data value: 4 / 0x4 / 0b0100
    Stacktrace:
    	at net.minecraft.world.World.func_72939_s(World.java:1939)
    	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

EnderIO version: 2.2.8.367
Mekanism version: 8.1.1.228

**Comment by HenryLoenwind** [comment]
Mekanism changed their API in version 8 and are no longer compatible with Ender IO 2.2.8.

Use Mekanism 7 or a current 2.3-dev version of Ender IO (be aware of bugs).
