### ISSUE TITLE
crash after killerjoe receive an weapon the mod metallurgy, enchanted

### ISSUE THREAD

**Issue by N3UTr4L** [SleepyTrousers/EnderIO#2420]
---- Minecraft Crash Report ----
// Oops.

Time: 04/05/15 03:52
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:891)
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:642)
	at com.teammetallurgy.metallurgy.tools.Sword.applyEffects(Sword.java:113)
	at com.teammetallurgy.metallurgy.tools.Sword.func_77644_a(Sword.java:132)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:299)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1282)
	at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java)
	at crazypants.enderio.machine.killera.TileKillerJoe.processTasks(TileKillerJoe.java:179)
	at crazypants.enderio.machine.AbstractMachineEntity.func_145845_h(AbstractMachineEntity.java:276)
	at crazypants.enderio.machine.killera.TileKillerJoe.func_145845_h(TileKillerJoe.java:116)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by MatthiasMann** [comment]
Which EnderIO version?

**Comment by HenryLoenwind** [comment]
Could be the same problem as #2351

**Comment by tterrag1098** [comment]
No, but it was fixed here https://github.com/SleepyTrousers/EnderIO/commit/739d235b668816099996b16905db7f9e3d0e25f6#diff-acbfe65b3f111186d77b64091142a504R543

**Comment by N3UTr4L** [comment]
hi,
minecraft 1.7.10
minecraft Forge10.13.2.1291
EnderIO-1.7.10-2.2.8.367
Metallurgy-1.7.10-4.0.8.97

sword of Kalendrite.
ps: this sword already comes with a kind of enchant  when craft, this is regeneration.
