### ISSUE TITLE
Crashed by putting reservoir

### ISSUE THREAD

**Issue by armariris** [SleepyTrousers/EnderIO#2453]
When I place reservoir , Minecraft will crash.
Operating environments is as follows:
Minecraft-1.7.10
MinecraftForge-10.13.3.1355
EnderIO-1.7.10-2.2.8.367

**Comment by tterrag1098** [comment]
Please post the crash log...

**Comment by armariris** [comment]
Sorry,crash report is as follows:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15/05/09 23:53
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidRegistry.getFluidName(I)Ljava/lang/String;
	at crazypants.enderio.machine.reservoir.TileReservoir.writeCustomNBT(TileReservoir.java:300)
	at crazypants.enderio.TileEntityEio.func_145844_m(TileEntityEio.java:29)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at crazypants.enderio.machine.reservoir.TileReservoir.writeCustomNBT(TileReservoir.java:300)
	at crazypants.enderio.TileEntityEio.func_145844_m(TileEntityEio.java:29)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)

-- Affected level --
Details:
	Level name: test2
	All players: 1 total; [EntityPlayerMP['armariris154'/23, l='test2', x=720.50, y=4.00, z=-1240.50]]
	Chunk stats: ServerChunkCache: 353 Drop: 0
	Level seed: 8593986694891605059
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (727,4,-1234), Chunk: (at 7,0,14 in 45,-78; contains blocks 720,0,-1248 to 735,255,-1233), Region: (1,-3; contains chunks 32,-96 to 63,-65, blocks 512,0,-1536 to 1023,255,-1025)
	Level time: 584 game time, 584 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 119198 (now: false), thunder time: 12559 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 243438696 bytes (232 MB) / 451321856 bytes (430 MB) up to 1046937600 bytes (998 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.103.1355 Minecraft Forge 10.13.3.1355 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.103.1355} [Forge Mod Loader] (forge-1.7.10-10.13.3.1355-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1355} [Minecraft Forge] (forge-1.7.10-10.13.3.1355-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['armariris154'/23, l='test2', x=720.50, y=4.00, z=-1240.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by armariris** [comment]
Thanks to solve the problem.It has been resolved by updating the forge to the latest version.
