### ISSUE TITLE
Crash when walking on machines with conduits

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#2536]
I frequently get a crash when walking on machines, such as the Zombie Generator and Combustion Generator that have item or fluid conduits on top of them (no conduit facades on the conduits).  I'm not exactly sure if I'm standing on the conduit or on the machine when it happens.  

Here is the top of a couple of error logs.  I could post the whole log if it would be helpful.

---- Minecraft Crash Report ----
// My bad.

Time: 6/2/15 7:35 PM
Description: Ticking entity

java.lang.ClassCastException: crazypants.enderio.machine.generator.zombie.TileZombieGenerator cannot be cast to crazypants.enderio.conduit.TileConduitBundle
	at crazypants.enderio.conduit.BlockConduitBundle.onPlaySoundAtEntity(BlockConduitBundle.java:227)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_BlockConduitBundle_onPlaySoundAtEntity_PlaySoundAtEntityEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 6/1/15 11:48 PM
Description: Ticking entity

java.lang.ClassCastException: crazypants.enderio.machine.generator.combustion.TileCombustionGenerator cannot be cast to crazypants.enderio.conduit.TileConduitBundle
	at crazypants.enderio.conduit.BlockConduitBundle.onPlaySoundAtEntity(BlockConduitBundle.java:227)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_BlockConduitBundle_onPlaySoundAtEntity_PlaySoundAtEntityEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

**Comment by tterrag1098** [comment]
#2535
