### ISSUE TITLE
Crash when walking on machines with conduits

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderIO#2537]
I frequently get a crash when walking on machines such as the zombie generator and combustion generator that have conduits on top of them (no facades on the conduits).  I'm not sure if I'm on the machine or the conduit when it happens.  

Here are the top lines of a couple of crash logs.  I can post the whole logs if that would be more helpful.

---- Minecraft Crash Report ----
// My bad.

Time: 6/2/15 7:35 PM
Description: Ticking entity

java.lang.ClassCastException: crazypants.enderio.machine.generator.zombie.TileZombieGenerator cannot be cast to crazypants.enderio.conduit.TileConduitBundle
	at crazypants.enderio.conduit.BlockConduitBundle.onPlaySoundAtEntity(BlockConduitBundle.java:227)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_BlockConduitBundle_onPlaySoundAtEntity_PlaySoundAtEntityEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 6/1/15 11:48 PM
Description: Ticking entity

java.lang.ClassCastException: crazypants.enderio.machine.generator.combustion.TileCombustionGenerator cannot be cast to crazypants.enderio.conduit.TileConduitBundle
	at crazypants.enderio.conduit.BlockConduitBundle.onPlaySoundAtEntity(BlockConduitBundle.java:227)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_BlockConduitBundle_onPlaySoundAtEntity_PlaySoundAtEntityEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

**Comment by tterrag1098** [comment]
Why did you do that? I just closed your last one. Don't open any more issues.

**Comment by rrongol** [comment]
I'm sorry!  I thought my browser had messed up and it didn't submit.  I didn't mean to be rude.

**Comment by tterrag1098** [comment]
It's fine
