### ISSUE TITLE
Critical Bug: craftRecipe forces Server to Freeze-State

### ISSUE THREAD

**Issue by NitroxydeX** [SleepyTrousers/EnderIO#2552]
Hey Guys,

EnderIO seems to have a critical bug in craftRecipe:

``` 
"Server thread" #34 prio=5
RUNNABLE
	at net.minecraft.item.Item.getMaxDamage(Item.java:1213)
	at net.minecraft.item.ItemStack.func_77984_f(ItemStack.java:197)
	at crazypants.enderio.machine.crafter.TileCrafter.eatOneItemForCrafting(TileCrafter.java:222)
	at crazypants.enderio.machine.crafter.TileCrafter.craftRecipe(TileCrafter.java:178)
	at crazypants.enderio.machine.crafter.TileCrafter.processTasks(TileCrafter.java:109)
	at crazypants.enderio.machine.AbstractMachineEntity.func_145845_h(AbstractMachineEntity.java:276)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.func_145845_h(AbstractPoweredMachineEntity.java:31)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Problem is verified via jdb.

**Comment by MatthiasMann** [comment]
Which item did you craft and what are the items you had in the inventory of the crafter?

**Comment by NitroxydeX** [comment]
Via jdb I got this: com.pam.harvestcraft.ItemPamPotionFood

I dont know if its right, because this was a problem caused by a user of a modpack-server. So I can just tell what jdb told me.

**Comment by MatthiasMann** [comment]
do you also have the meta data for that?

**Comment by NitroxydeX** [comment]
Maybe this item.raspberryjuiceItem@0? More we don't have.

**Comment by sfPlayer1** [comment]
I've been investigating this, the raspberry juice is the recipe output.  If I followed jdb's output correctly, the stack never left craftRecipe(). The recipe involves a juicer, which is a container item that yields itself (no damage). The inventory is unknown.

**Comment by MatthiasMann** [comment]
I can reproduce the issue and I'm looking into it.

**Comment by NitroxydeX** [comment]
Thanks MatthiasMann :)

**Comment by MatthiasMann** [comment]
@NitroxydeX can you try EnderIO 2.3 beta build 390 ?

**Comment by NitroxydeX** [comment]
Where can I download the Beta builds?

**Comment by NitroxydeX** [comment]
found it!

**Comment by NitroxydeX** [comment]
Worked! Thanks a lot @MatthiasMann!! Great fix :3 :+1:
