### ISSUE TITLE
Ticking Block Entity | Farmer keeps crashing the Server

### ISSUE THREAD

**Issue by NitroxydeX** [SleepyTrousers/EnderIO#2575]
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12.06.15 19:29
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:380)
	at crazypants.enderio.machine.farm.farmers.PickableFarmer.harvestBlock(PickableFarmer.java:40)
	at crazypants.enderio.machine.farm.farmers.NaturaBerryFarmer.harvestBlock(NaturaBerryFarmer.java:38)
	at crazypants.enderio.machine.farm.farmers.FarmersCommune.harvestBlock(FarmersCommune.java:54)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:444)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:378)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:93)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:258)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:38)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:366)
	at crazypants.enderio.TileEntityEio.func_145845_h(TileEntityEio.java:42)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at fastcraft.c.p.a(F:19)
	at fastcraft.Hooks.aq(F:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:380)
	at crazypants.enderio.machine.farm.farmers.PickableFarmer.harvestBlock(PickableFarmer.java:40)
	at crazypants.enderio.machine.farm.farmers.NaturaBerryFarmer.harvestBlock(NaturaBerryFarmer.java:38)
	at crazypants.enderio.machine.farm.farmers.FarmersCommune.harvestBlock(FarmersCommune.java:54)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:444)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:378)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:93)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:258)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:38)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:366)
	at crazypants.enderio.TileEntityEio.func_145845_h(TileEntityEio.java:42)

-- Block entity being ticked --
Details:
	Name: blockFarmStationTileEntity // crazypants.enderio.machine.farm.TileFarmStation
	Block type: ID #1567 (tile.blockFarmStation // crazypants.enderio.machine.farm.BlockFarmStation)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-369,75,1551), Chunk: (at 15,4,15 in -24,96; contains blocks -384,0,1536 to -369,255,1551), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
	Actual block type: ID #1567 (tile.blockFarmStation // crazypants.enderio.machine.farm.BlockFarmStation)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
```

**Comment by tterrag1098** [comment]
Found to not be our fault

**Comment by olee** [comment]
Hi there, @NitroxydeX reported this problem on our tracker as well and I took my time to further investigate this issue (see ForgeEssentials/ForgeEssentialsMain#1578).

This seems to be an issue with forge itself which is unable to handle cancelled PlayerInteractEvents in `activateBlockOrUseItem` with FakePlayers, because `fakePlayer.playerNetServerHandler == null`.
I suggest making a PR to forge and would like you guys to take care of it if possible (currently don't have much time to do this). You also might want to reopen this issue until it is fixed, as it is not necessarily related to FE, but any possible permission mod (including sponge etc.).
