### ISSUE TITLE
ender IO doesn't work whit mekanism

### ISSUE THREAD

**Issue by vovavalter** [SleepyTrousers/EnderIO#2647]
my game crashes if i want to play whit mekanism and ender IO

**Comment by MatthiasMann** [comment]
Well - in order to give you any useful answer - try making a useful bug report first - or even better - search the existing issues first.

A good bug report requires at lest the versions of the affected mods - and in case of a crash also a crash report.

**Comment by vovavalter** [comment]
my apologies that it isn't an actual bug but i don't know what to do anymore and here is the crash file (sorry that it isn't the text file this is all what i could do) :

---- Minecraft Crash Report ----
// Sorry :(

Time: 10/07/15 17:26
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: crazypants/enderio/teleport/ItemTravelStaff
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:523)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: crazypants/enderio/teleport/ItemTravelStaff
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:512)
	... 10 more
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.teleport.ItemTravelStaff
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: crazypants/enderio/teleport/IItemOfTravel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: crazypants.enderio.teleport.IItemOfTravel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 96159328 bytes (91 MB) / 270041088 bytes (257 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1428 29 mods loaded, 29 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed
	Forge{10.13.3.1428} [Minecraft Forge] (forge-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.5.111} [Not Enough Items] (NOTENOUGHITEMS-1.7.10-1.0.5.111-UNIVERSAL.jar) Unloaded->Constructed
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ARMORSTATUSHUD-CLIENT-1.28.jar) Unloaded->Constructed
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DAMAGEINDICATORSMOD-3.2.3.jar) Unloaded->Constructed
	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed
	chisel{2.3.10.37} [Chisel 2] (CHISEL2-2.3.10.37.jar) Unloaded->Constructed
	Mekanism{8.1.5} [Mekanism] (MEKANISM-1.7.10-8.1.5.240.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.1.7.254} [Ender IO] (EnderIO-1.7.10-2.1.7.254.jar) Unloaded->Errored
	EnderStorage{1.4.7.36} [EnderStorage] (ENDERSTORAGE-1.7.10-1.4.7.36-UNIVERSAL.jar) Unloaded->Constructed
	ExtraUtilities{1.2.6} [Extra Utilities] (EXTRAUTILITIES-1.2.6.jar) Unloaded->Constructed
	malisiscore{1.7.10-0.12.2} [MalisisCore] (MALISISCORE-1.7.10-0.12.2.jar) Unloaded->Constructed
	malisisdoors{1.7.10-1.8.2} [Malisis' Doors] (MALISISDOORS-1.7.10-1.8.2.jar) Unloaded->Constructed
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NOTENOUGHKEYS-1.7.10-1.0.0B29.jar) Unloaded->Constructed
	neresources{0.1.0.95} [Not Enough Resources] (NOTENOUGHRESOURCES-1.7.10-0.1.0.95.jar) Unloaded->Constructed
	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.0.8.16-universal.jar) Unloaded->Constructed
	ProjRed|Core{4.6.2.82} [ProjectRed] (PROJECTRED-1.7.10-4.6.2.82-BASE.jar) Unloaded->Constructed
	ProjRed|Transmission{4.6.2.82} [ProjectRed-Transmission] (PROJECTRED-1.7.10-4.6.2.82-INTEGRATION.jar) Unloaded->Constructed
	ProjRed|Transportation{4.6.2.82} [ProjectRed-Transportation] (PROJECTRED-1.7.10-4.6.2.82-MECHANICAL_BETA.jar) Unloaded->Constructed
	ProjRed|Exploration{4.6.2.82} [ProjectRed-Exploration]

**Comment by MatthiasMann** [comment]
This is caused by Mekanism and how it handles the RF API.

**Comment by b0bst3r** [comment]
Just add cofhcore to your pack and problem solved.

**Comment by vovavalter** [comment]
thx 4 helping me out
