### ISSUE TITLE
Wireless Charger Crashed Game

### ISSUE THREAD

**Issue by zombie1234565** [SleepyTrousers/EnderIO#2656]
---- Minecraft Crash Report ----
// My bad.

Time: 7/15/15 10:49 AM
Description: Unexpected error

java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145)
	at crazypants.enderio.machine.wireless.TileWirelessCharger.<init>(TileWirelessCharger.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at crazypants.enderio.BlockEio.createTileEntity(BlockEio.java:47)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145)
	at crazypants.enderio.machine.wireless.TileWirelessCharger.<init>(TileWirelessCharger.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at crazypants.enderio.BlockEio.createTileEntity(BlockEio.java:47)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Zombie1234565'/112, l='MpServer', x=-204.30, y=238.62, z=-11.52]]
	Chunk stats: MultiplayerChunkCache: 225, 234
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,4,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 690592 game time, 2880 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityItem['item.item.rottenFlesh'/18572, l='MpServer', x=-176.50, y=227.13, z=-63.75], EntityItem['item.item.rottenFlesh'/15, l='MpServer', x=-185.13, y=227.13, z=-62.69], EntityCreeper['Creeper'/16, l='MpServer', x=-187.31, y=235.00, z=3.31], EntityCreeper['Creeper'/159, l='MpServer', x=-266.50, y=237.00, z=6.50], EntityItem['item.item.arrow'/19382, l='MpServer', x=-195.84, y=227.13, z=-60.78], EntityBlock['unknown'/186, l='MpServer', x=-189.75, y=234.00, z=4.25], EntityBlock['unknown'/187, l='MpServer', x=-183.75, y=234.00, z=8.25], EntityCreeper['Creeper'/193, l='MpServer', x=-189.69, y=235.75, z=-7.50], EntitySpider['Spider'/196, l='MpServer', x=-236.50, y=237.00, z=62.50], EntityCreeper['Creeper'/7109, l='MpServer', x=-239.50, y=237.00, z=-21.50], EntityCreeper['Creeper'/203, l='MpServer', x=-187.69, y=235.00, z=4.16], EntitySpider['Spider'/9177, l='MpServer', x=-256.50, y=237.00, z=-38.50], EntityItem['item.item.bone'/19549, l='MpServer', x=-175.94, y=227.13, z=-64.09], EntityMechanicalArm['unknown'/233, l='MpServer', x=-234.00, y=237.00, z=-43.00], EntityBlock['unknown'/234, l='MpServer', x=-233.25, y=253.25, z=-73.22], EntityBlock['unknown'/235, l='MpServer', x=-215.75, y=229.00, z=-73.22], EntityCreeper['Creeper'/108, l='MpServer', x=-207.00, y=233.00, z=-12.63], EntityBlock['unknown'/236, l='MpServer', x=-215.75, y=253.25, z=-106.25], EntitySkeleton['Skeleton'/109, l='MpServer', x=-208.16, y=233.00, z=-12.56], EntityBlock['unknown'/237, l='MpServer', x=-215.60, y=228.00, z=-73.07], EntityItem['item.item.arrow'/19310, l='MpServer', x=-186.50, y=227.13, z=-73.03], EntityItem['item.item.bone'/19311, l='MpServer', x=-186.03, y=227.13, z=-73.22], EntityClientPlayerMP['Zombie1234565'/112, l='MpServer', x=-204.30, y=238.62, z=-11.52], EntityItem['item.item.arrow'/19451, l='MpServer', x=-143.09, y=237.13, z=-49.06], EntityItem['item.item.bone'/19452, l='MpServer', x=-142.50, y=237.13, z=-48.34]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360025248 bytes (343 MB) / 663093248 bytes (632 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_C1 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	AppliedEnergistics2-Core{rv0-stable-8} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	BuildCraft|Core{6.4.16} [BuildCraft] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	appliedenergistics2{rv0-stable-8} [Applied Energistics 2] (appliedenergistics2-rv0-stable-8.jar) 
	UCHIJAAAA	BuildCraft|Builders{6.4.16} [BC Builders] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Energy{6.4.16} [BC Energy] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Factory{6.4.16} [BC Factory] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Transport{6.4.16} [BC Transport] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	BuildCraft|Silicon{6.4.16} [BC Silicon] (buildcraft-6.4.16.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.0.0.191} [Ender IO] (EnderIO-1.7.10-2.0.0.191.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 4200 Series'
	AE2 Version: stable rv0-stable-8 for Forge 10.13.0.1152
	AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:ON, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, FMP:OFF
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Mobility Radeon HD 4200 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MatthiasMann** [comment]
This looks more like an MJ API issue - which shouldn't exist anymore. Also your version of EnderIO is very old and no longer supported.
