### ISSUE TITLE
Crash - Telepad Block

### ISSUE THREAD

**Issue by louismiller** [SleepyTrousers/EnderIO#2729]
When trying to shift-click any Capacitor into the Telepad Block Multistructure, the game crashes.

Only happens when you are on the Travel Settings page (the ones with the coords), not the Telepad Settings page.

Mods installed:

* EnderCore-1.7.10-0.0.1.17_alpha
* EnderIO-1.7.10-2.3.0.407_beta
* EnderZoo-1.7.10-1.0.15.32

```
Details:
        Screen name: crazypants.enderio.teleport.telepad.GuiTelePad
Stacktrace:
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
        at org.multimc.EntryPoint.listen(EntryPoint.java:170)
        at org.multimc.EntryPoint.main(EntryPoint.java:54)
```
Crash report: http://pastebin.com/ywRUTtMR

**Comment by tterrag1098** [comment]
#2724
