### ISSUE TITLE
Game crashes when placing alloy smelter

### ISSUE THREAD

**Issue by saplays** [SleepyTrousers/EnderIO#2734]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/23/15 1:00 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145)
	at crazypants.enderio.power.PowerHandlerUtil.createHandler(PowerHandlerUtil.java:62)
	at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:86)
	at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:185)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.<init>(AbstractPoweredTaskEntity.java:26)
	at crazypants.enderio.machine.alloy.TileAlloySmelter.<init>(TileAlloySmelter.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at crazypants.enderio.machine.AbstractMachineBlock.func_149915_a(AbstractMachineBlock.java:89)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:242)
	at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:223)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159)
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145)
	at crazypants.enderio.power.PowerHandlerUtil.createHandler(PowerHandlerUtil.java:62)
	at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:86)
	at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:185)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.<init>(AbstractPoweredTaskEntity.java:26)
	at crazypants.enderio.machine.alloy.TileAlloySmelter.<init>(TileAlloySmelter.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at crazypants.enderio.machine.AbstractMachineBlock.func_149915_a(AbstractMachineBlock.java:89)
	at net.minecraft.block.Block.createTileEntity(Block.java:1446)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850)
	at net.minecraft.world.World.func_147438_o(World.java:2540)
	at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:242)
	at com.rwtema.extrautils.tileentity.generators.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:223)

-- Block entity being ticked --
Details:
	Name: extrautils:generatorstone // com.rwtema.extrautils.tileentity.generators.TileEntityGeneratorFurnaceSurvival
	Block type: ID #886 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generators.BlockGenerator)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-501,68,1130), Chunk: (at 11,4,10 in -32,70; contains blocks -512,0,1120 to -497,255,1135), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Actual block type: ID #886 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generators.BlockGenerator)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: 1.7.10 modded
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 8589603769502566616
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-531,64,1129), Chunk: (at 13,4,9 in -34,70; contains blocks -544,0,1120 to -529,255,1135), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 434880 game time, 460537 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 53932 (now: false), thunder time: 54309 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 284716696 bytes (271 MB) / 843055104 bytes (804 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 46, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.6][MC1.7.10].jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.0.19} [BuildCraft] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.0.19} [BC Silicon] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.0.19} [BC Transport] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.0.19} [BC Builders] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.0.19} [BC Robotics] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.0.19} [BC Energy] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.0.19} [BC Factory] (buildcraft-7.0.19.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.0.5.214} [Ender IO] (EnderIO-1.7.10-2.0.5.214.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.0} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0-176.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.10} [Extra Utilities] (extrautilities-1.2.10.jar) 
	UCHIJAAAA	IC2{2.2.765-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.765-experimental.jar) 
	UCHIJAAAA	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8-snapshot-390.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4-snapshot-658.jar) 
	UCHIJAAAA	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-universal.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.0-176
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by tterrag1098** [comment]
You are extremely outdated.

**Comment by saplays** [comment]
sorry for asking I guess I'm still learning, but what is outdated? all the mods I installed are the latest, am I overlooking one?

**Comment by MatthiasMann** [comment]
@saplays You have EnderIO 2.0.x - the current released version is EnderIO 2.2.8 and the current development is in EnderIO 2.3 beta.

**Comment by saplays** [comment]
@MatthiasMann Thanks, that did the trick :D I need to pay more attention thanks again for the help guys
