### ISSUE TITLE
Server Crash loading old world

### ISSUE THREAD

**Issue by MrNuggelz** [SleepyTrousers/EnderIO#2854]
I tried to load a world i startet with "EnderIO-1.7.10-2.3.0.414_beta" and got the error.
The error is:

java.lang.NoClassDefFoundError: com/enderio/core/client/gui/GuiContainerBase
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at crazypants.enderio.conduit.item.FilterRegister.loadFilterFromNbt(FilterRegister.java:67)
	at crazypants.enderio.conduit.item.FilterRegister.loadFilterFromNbt(FilterRegister.java:59)
	at crazypants.enderio.conduit.item.ItemConduit.readFromNBT(ItemConduit.java:831)
	at crazypants.enderio.conduit.ConduitUtil.readConduitFromNBT(ConduitUtil.java:349)
	at crazypants.enderio.conduit.TileConduitBundle.readCustomNBT(TileConduitBundle.java:141)
	at com.enderio.core.common.TileEntityEnder.func_145839_a(TileEntityEnder.java:84)
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: com.enderio.core.client.gui.GuiContainerBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 28 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.inventory.GuiContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

**Comment by HenryLoenwind** [comment]
Is that really a crash? Or is it just an error message and the game goes on?

**Comment by MrNuggelz** [comment]
It's a crash when i start the server. I would attach the full crashreport, but for some reason github has problems with me attaching a text file.
Also when i create a new world the server starts fine
