### ISSUE TITLE
Crash when looking at a travel anchor

### ISSUE THREAD

**Issue by BrokenHearted2** [SleepyTrousers/EnderIO#2894]
I am using 2.3.0.416 tried to place a travel anchor, and WAILA did not like it.

java.lang.NullPointerException: Unexpected error
	at crazypants.enderio.waila.WailaCompat.getWailaStack(WailaCompat.java:145)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:156)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:97)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:66)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_785_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at crazypants.enderio.waila.WailaCompat.getWailaStack(WailaCompat.java:145)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:156)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:97)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:66)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_785_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

**Comment by wlhlm** [comment]
#2879, #2877
