### ISSUE TITLE
Conflicting Classes, Crash on Startup

### ISSUE THREAD

**Issue by Swordsyke** [SleepyTrousers/EnderIO#3020]
Getting a crash report and I don't know how to fix it. EnderIO is incorrectly casting one class onto another. Any ideas on how to fix?

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/20/15 12:50 PM
Description: Exception in server tick loop

java.lang.ClassCastException: crazypants.enderio.conduit.TileConduitBundle cannot be cast to crazypants.enderio.teleport.telepad.TileTelePad
	at crazypants.enderio.teleport.telepad.BlockTelePad.onNeighborChange(BlockTelePad.java:105)
	at net.minecraft.world.World.func_147453_f(World.java:4567)
	at net.minecraft.world.World.func_147455_a(World.java:3189)
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:926)
	at net.minecraft.world.World.func_147438_o(World.java:3126)
	at appeng.me.GridNode.findGridHost(GridNode.java:496)
	at appeng.me.GridNode.FindConnections(GridNode.java:403)
	at appeng.me.GridNode.updateState(GridNode.java:217)
	at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:150)
	at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:141)
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:309)
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605)
	at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_655_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Swordsyke** [comment]
This is a server crash log, btw. Forgot to mention that.

**Comment by XFactHD** [comment]
Which version of EnderIO are you using?

**Comment by Swordsyke** [comment]
EnderIO-1.7.10-2.3.0.415_beta

**Comment by Swordsyke** [comment]
I just need a fix for this so I can get my server up and running.

**Comment by HenryLoenwind** [comment]
Your world got damaged. Use mcedit to remove the damaged area.

This is not a bug in Ender IO, but we'd really like to find out what is causing these corruptions. They are happening very often lately...
