### ISSUE TITLE
Could not spawn mod entity ModID: EnderIO EntityID: 30

### ISSUE THREAD

**Issue by Dream-Master** [SleepyTrousers/EnderIO#3039]
On my private Server one Player get the following Problem. Every time he log in he get kicked and this is written in the fml log.

https://gist.github.com/Dream-Master/a7a43970c401a8717a9d#file-ender-io

**Comment by HenryLoenwind** [comment]
His enderio.conf differs from the server's. I'd guess(!) he has "replace wither skeletons" disabled but the server want to send him one. (I might be wrong, but I think that is the only entity left in Ender IO, all others were moved to Ender Zoo.)

**Comment by Dream-Master** [comment]
we have ender zoo too

**Comment by Dream-Master** [comment]
config is the same i compare it.

Wither skelteon is enabled. Schould i set this to false and try ?

**Comment by HenryLoenwind** [comment]
No, that would create bigger problems.

Is there more to this error? It basically says that an error has happened, which is not very helpful without some information about the error that happened...

**Comment by Dream-Master** [comment]
Ok what you need. Server log?

Here the Mods are in the Pack:

https://github.com/GTNewHorizons/NewHorizons

**Comment by Dream-Master** [comment]
Here is a Entity Dump with nei.
[neiintegration_entity.txt](https://github.com/SleepyTrousers/EnderIO/files/44213/neiintegration_entity.txt)

**Comment by Dream-Master** [comment]
@HenryLoenwind  So any solution what we can do or you what kind of information you need ?

**Comment by Dream-Master** [comment]
30,LavaMonsters.LavaMonster,toast.lavaMonsters.EntityLavaMonster

Could it be Lava Monsters from Father Toast?

**Comment by Badcholo** [comment]
Yes, lava monsters has crashed me many times. It would have been cool but i removed it right away.

**Comment by tterrag1098** [comment]
Is this actually a crash? the error you posted is harmless.

**Comment by Dream-Master** [comment]
Lava Monsters was the Problem. Not sure why dispay Ender IO ??????

**Comment by Dream-Master** [comment]
One time i not have a crash but now i crash again. In my Data Dump there is no Entity with ID 30 any more ????

**Comment by Dream-Master** [comment]
[neiintegration_entity.txt](https://github.com/SleepyTrousers/EnderIO/files/44762/neiintegration_entity.txt)

**Comment by Badcholo** [comment]
Lava monsters may have corrupted your world. I had to delete my world folder. suxs.
good luck. Save your world folder and have it make a new one. Then see if it crashes again.

**Comment by Dream-Master** [comment]
No delelte my world impossible! Cutting out this chuncks are more realistic.

**Comment by Dream-Master** [comment]
After a bit investigation i find out i get this error when i spawned on a Portal to the  Dark Dimension from Extra Utilities. (1.2.12 and player api 1.4)

**Comment by HenryLoenwind** [comment]
You still haven't posted a **crash log**. The message you posted in itself is harmless.

**Comment by Dream-Master** [comment]
It is not a crash it is a kick from the Server.

Server Error log (part)

`````
[20:47:34] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:234) [mn.class:?]
	at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:404) [EntityRegistry.class:1.7.10-1492.150]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:62) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:28) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1832) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1086) [mt.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3964) [ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1020) [apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [ChunkIOProvider.class:1.7.10-1492.150]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1492.150]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1492.150]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1492.150]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1492.150]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:198) ~[mn.class:?]
	... 17 more
`````

fml log (part)

``````
[20:34:05] [Client thread/ERROR] [FML/]: HandshakeCompletionHandler exception
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 30 at ( 749.625,84.0, -275.75) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:34:05] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML

```
It not crash the Game so no crash Log available sorry

**Comment by Dream-Master** [comment]
With and with out Lava Monster the same kick and error message.
Remove The Portal Blocks from the Dark Dimesnion (Extra Utilities 1.2.12) helps because when the Player spawns on top the Portal Block or entering the Chunk where this block is ged kicked.

**Comment by Dream-Master** [comment]
So any news here any thing i can test or any Info log you need ?

**Comment by Badcholo** [comment]
it's the holidays, you might get a slow response time. Have you tried an issue with Extra Utilities.

**Comment by Dream-Master** [comment]
RWtema never answermy any issues. But i can try it.

**Comment by Dream-Master** [comment]
This seems to be a Server issue because i can't reproduce it in sp.

**Comment by Alaberti** [comment]
Looks like a mismatch of entity ids between the client and server. Verify your configs in my recommendation. Might be as simple as copying then from client to server but it would be best to manually run through them.

**Comment by Dream-Master** [comment]
Ender Io config (main config) match. So it have to be another mod than where the config not match.
Yesterday i copy my whole Server to a Test Server pace and jump a dozen times to different Portals and not get any crash. Then i join on my Server and fly to the position and i get kicked again with this error. I try to using the command Butcher to kill Entities but this does not work too. My Idea is today start the Server in a Peaceful mode but not sure if this helps. If there some configs async then it not will help i guess.

**Comment by ajthemacboy** [comment]
Copy your configs from server to client. I had this same issue on my server. Even if you copy configs from client to server, sometimes the server overrides them and changes them, so you have to copy those back to client again.

**Comment by Dream-Master** [comment]
I did it copy all configs to the client but it dont work.

**Comment by Badcholo** [comment]
Start pulling mods to find out which one is having problems with it. I think he's working on it already.

**Comment by Dream-Master** [comment]
I try to downgrading all mods to the previous version but it still kick me out.
(Maybe i have to check Special Mobs because this mod gave us some wired crash on the Server before with a older version)

**Comment by Dream-Master** [comment]
@HenryLoenwind Waiting for Feedback ?

I not sure on wich end i have to searching.
Need help please.

**Comment by Dream-Master** [comment]
Now i get this error Client Side:

````
[12:06:14] [Client thread/ERROR] [FML/]: HandshakeCompletionHandler exception
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 6 at ( 62.875,100.875, 341.1875) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
`````

Serversied this:

`````
[12:05:06] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:234) [mn.class:?]
	at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:404) [EntityRegistry.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:62) [mn.class:?]
	at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:28) [mp.class:?]
	at net.minecraft.world.World.func_72923_a(World.java:1832) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1086) [mt.class:?]
	at net.minecraft.world.World.func_72868_a(World.java:3964) [ahb.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1020) [apx.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [ChunkIOProvider.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:198) ~[mn.class:?]
	... 17 more
``````

**Comment by Dream-Master** [comment]
If i remove Ender io i get this error.

Serverside:

````
DreamMasterXXL lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: String too big (was 64680 bytes encoded, max 32767)`
``````

Clientside

`````
Internal Exeption: java.io.IOExeption:Eine vorhndene Verbindung wurde vom Remotehost geschlossen.

can be translated to this

An existing connection was closed by the remote host.
``````

**Comment by HenryLoenwind** [comment]
I'm 99% sure the reference to Ender IO in the message is a red herring. If there's anyone who actually has some idea how Minecraft entities work...? @CrazyPants @tterrag1098
