### ISSUE TITLE
my LunatriusCore keeps crashing my game help pls

### ISSUE THREAD

**Issue by TravisWillis112** [SleepyTrousers/EnderIO#3053]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/5/15 7:54 AM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/fml/client/GuiIngameModOptions
	at com.github.lunatrius.core.handler.GuiHandler.onGuiOpen(GuiHandler.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_GuiHandler_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:912)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:501)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.client.GuiIngameModOptions
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.lunatrius.core.handler.GuiHandler.onGuiOpen(GuiHandler.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_GuiHandler_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:912)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:501)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 49824208 bytes (47 MB) / 397856768 bytes (379 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJA	LunatriusCore{1.1.2.29} [LunatriusCore] (LunatriusCore-1.8-1.1.2.29-universal (4).jar) 
	UCHIJA	Schematica{1.7.7.139} [Schematica] (Schematica-1.8-1.7.7.139-universal (2).jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 8.15.10.2372' Renderer: 'Intel(R) HD Graphics Family'
	Launched Version: 1.8-forge1.8-11.14.4.1577
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics Family GL version 3.1.0 - Build 8.15.10.2372, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [BlazePvP.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by wlhlm** [comment]
Hi,

this is the repository for EnderIO and not Lunatrius Core. Please report the issue at [their repository](https://github.com/Lunatrius/LunatriusCore/). BTW your particular issue should already be fixed. See Lunatrius/LunatriusCore#12

Also, I recommend updating your Java (this has nothing to with your crash, but is just general advice).

**Comment by TravisWillis112** [comment]
so what should i do?

**Comment by wlhlm** [comment]
> For 1.8 set B:replaceInGameConfig=false in the config file.

**Comment by TravisWillis112** [comment]
so what should i do?
