### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Horneat** [SleepyTrousers/EnderIO#3091]
just updated Agricraft to the 1.4.6 Version.

 

java.lang.ClassCastException: crazypants.enderio.machine.crafter.TileCrafter cannot be cast to crazypants.enderio.machine.light.TileLightNode
	at crazypants.enderio.machine.light.BlockLightNode.func_149695_a(BlockLightNode.java:71)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:648)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.world.World.func_72939_s(World.java:1950)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by HenryLoenwind** [comment]
1) You world is corrupted

2) #2835

**Comment by Horneat** [comment]
okey

**Comment by Horneat** [comment]
that means that i must delet it 
?
