### ISSUE TITLE
Crash after start the server

### ISSUE THREAD

**Issue by Zoom4ikDan4ik** [SleepyTrousers/EnderIO#3093]
Hello, there was this crash that occurs when starting the server:
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.network.NetHandlerPlayServer.<init>(NetHandlerPlayServer.java:185)
	at crazypants.enderio.machine.farm.FakeNetHandlerPlayServer.<init>(FakeNetHandlerPlayServer.java:34)
	at crazypants.enderio.machine.FakePlayerEIO.<init>(FakePlayerEIO.java:25)
	at crazypants.enderio.machine.killera.TileKillerJoe$Attackera.<init>(TileKillerJoe.java:533)
	at crazypants.enderio.machine.killera.TileKillerJoe.getAttackera(TileKillerJoe.java:350)
	at crazypants.enderio.machine.killera.TileKillerJoe.doUpdate(TileKillerJoe.java:134)
	at com.enderio.core.common.TileEntityEnder.func_145845_h(TileEntityEnder.java:45)
	at net.minecraft.world.World.func_72939_s(World.java:2512)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)
Details:
	Name: blockKillerJoeTileEntity // crazypants.enderio.machine.killera.TileKillerJoe
	Block type: ID #1009 (tile.blockKillerJoe // crazypants.enderio.machine.killera.BlockKillerJoe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-7176,88,3805), Chunk: (at 8,5,13 in -449,237; contains blocks -7184,0,3792 to -7169,255,3807), Region: (-15,7; contains chunks -480,224 to -449,255, blocks -7680,0,3584 to -7169,255,4095)
	Actual block type: ID #1009 (tile.blockKillerJoe // crazypants.enderio.machine.killera.BlockKillerJoe)
	Actual block data value: 0 / 0x0 / 0b0000

**Comment by MatthiasMann** [comment]
Did you get any messages in the logs about unsupported mods?

**Comment by HenryLoenwind** [comment]
see #3069
