### ISSUE TITLE
Crash with Optifine 

### ISSUE THREAD

**Issue by Horneat** [SleepyTrousers/EnderIO#3097]
I switch from default to Smooth and than that happen

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at com.enderio.core.client.render.RenderUtil.renderBackground(RenderUtil.java:660)
	at com.enderio.core.client.render.RenderUtil.drawBillboardedText(RenderUtil.java:633)
	at com.enderio.core.client.render.RenderUtil.drawBillboardedText(RenderUtil.java:612)
	at crazypants.enderio.machine.farm.FarmingStationSpecialRenderer.renderFarmStationAt(FarmingStationSpecialRenderer.java:26)
	at crazypants.enderio.machine.farm.FarmingStationSpecialRenderer.func_147500_a(FarmingStationSpecialRenderer.java:34)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:766)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MatthiasMann** [comment]
Optifine is not supported - try without and if it still crashes then report that.

**Comment by Horneat** [comment]
also it works fine .But when i switch to smooth than it crashes

**Comment by wlhlm** [comment]
A lot of mods break when switching to Smooth. This is not something EnderIO can fix. Either use default, or remove Optifine entirely.
