### ISSUE TITLE
There was a bug does not know what is (Machine translation)

### ISSUE THREAD

**Issue by 52d52d** [SleepyTrousers/EnderIO#3141]
Description: Ticking block entity

java.lang.NoClassDefFoundError: Lriskyken/armourersWorkshop/client/render/MannequinFakePlayer;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at buildcraft.api.core.JavaTools.getAllFields(JavaTools.java:59)
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55)
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46)
	at crazypants.enderio.power.PowerHandlerUtil.create(PowerHandlerUtil.java:20)
	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:475)
	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:421)
	at crazypants.enderio.conduit.AbstractConduit.updateConnections(AbstractConduit.java:410)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:385)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:212)
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: riskyken.armourersWorkshop.client.render.MannequinFakePlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more

Can help me solve this problem?(☄⊙ω⊙)☄

**Comment by MatthiasMann** [comment]
Try posting this to the Armourers Workshop too. I don't think this is caused by EnderIO.

Also you seem to use a very old version? Upload the crash log.

**Comment by HenryLoenwind** [comment]
Most probable you are using an ancient version of Ender IO that still uses BuildCraft MJ together with mods that were build against a version of BuildCraft that doesn't have MJ anymore but uses RF.

**Comment by 52d52d** [comment]
Logs can't coming I don't know why...
The solution is to update version?

**Comment by RealKC** [comment]
Probably. Nobody uses MJ anymore. What version is that?
