### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by reinder-s** [SleepyTrousers/EnderIO#3229]
not sure if i need to post it here
but i could not find a way to do it on jenkins

#### Issue Description:
I had just downloaded the 1.8.9 version of enderio from jenkins
and when i pressed play i just crashed

here is the report file

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.8.9-3.6.5.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.1-beta.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 16-3-16 14:36
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: com.enderio.core.common.BlockEnder.<init>(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;Lnet/minecraft/block/material/Material;)V
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: com.enderio.core.common.BlockEnder.<init>(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;Lnet/minecraft/block/material/Material;)V
	at crazypants.enderio.BlockEio.<init>(BlockEio.java:35)
	at crazypants.enderio.machine.AbstractMachineBlock.<init>(AbstractMachineBlock.java:61)
	at crazypants.enderio.machine.AbstractMachineBlock.<init>(AbstractMachineBlock.java:83)
	at crazypants.enderio.machine.generator.stirling.BlockStirlingGenerator.<init>(BlockStirlingGenerator.java:34)
	at crazypants.enderio.machine.generator.stirling.BlockStirlingGenerator.create(BlockStirlingGenerator.java:28)
	at crazypants.enderio.EnderIO.preInit(EnderIO.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 257010736 bytes (245 MB) / 602869760 bytes (574 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1761 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1761.jar) 
	UCH	Forge{11.15.1.1761} [Minecraft Forge] (forge-1.8.9-11.15.1.1761.jar) 
	UCH	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCH	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCH	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCH	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCH	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCH	bookshelfapi{2.3.6} [Bookshelf] (Bookshelf-API-1.8.9-2.3.6.jar) 
	UCH	Thaumcraft{5.2.2} [Thaumcraft] (Thaumcraft-1.8.9-5.2.2.jar) 
	UCH	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCH	BuildCraft|Core{7.2.0-pre12} [BuildCraft] (buildcraft-7.2.0-pre12.jar) 
	UCH	BuildCraft|Transport{7.2.0-pre12} [BC Transport] (buildcraft-7.2.0-pre12.jar) 
	UCH	BuildCraft|Energy{7.2.0-pre12} [BC Energy] (buildcraft-7.2.0-pre12.jar) 
	UCH	BuildCraft|Factory{7.2.0-pre12} [BC Factory] (buildcraft-7.2.0-pre12.jar) 
	UCH	BuildCraft|Silicon{7.2.0-pre12} [BC Silicon] (buildcraft-7.2.0-pre12.jar) 
	UCH	BuildCraft|Robotics{7.2.0-pre12} [BC Robotics] (buildcraft-7.2.0-pre12.jar) 
	UCH	BuildCraft|Builders{7.2.0-pre12} [BC Builders] (buildcraft-7.2.0-pre12.jar) 
	UCH	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal.jar) 
	UCH	chiselsandbits{8.3} [Chisels & Bits] (chiselsandbits-8.3.jar) 
	UCH	ComputerCraft{1.79pr1} [ComputerCraft] (ComputerCraft1.79pr1.jar) 
	UCH	ElecCore{1.4.240} [ElecCore] (ElecCore-1.8.9-1.4.240.jar) 
	UCH	deepresonance{1.1.4beta17} [DeepResonance] (deepresonance-1.8.9-1.1.4beta17.jar) 
	UCH	endercore{1.8.9-0.3.0.1-beta} [EnderCore] (EnderCore-1.8.9-0.3.0.1-beta.jar) 
	UCE	EnderIO{1.8.9-3.0.0.10_alpha} [Ender IO] (EnderIO-1.8.9-3.0.0.10_alpha.jar) 
	UCH	exnihilo2{0.28} [Ex Nihilo 2] (ExNihilo2-0.28.jar) 
	UCH	flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8.jar) 
	UCH	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCH	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCH	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCH	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCH	mantle{1.8.9-0.9.0.jenkins97} [Mantle] (Mantle-1.8.9-0.9.0.jar) 
	UCH	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCH	tconstruct{1.8.9-2.2.0.jenkins133} [Tinkers' Construct] (TConstruct-1.8.9-2.2.0a.jar) 
	UCH	neotech{2.4.1} [NeoTech] (NeoTech-1.8.9-2.4.1.jar) 
	UCH	PneumaticCraft{1.13.8-12} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
	UCH	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UCH	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCH	randomthings{3.6.5} [Random Things] (RandomThings-MC1.8.9-3.6.5.jar) 
	UCH	rftools{4.22beta31} [RFTools] (rftools-1.8.9-4.22beta31.jar) 
	UCH	rftoolsdim{4.22beta27} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta27.jar) 
	UCH	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.8.9-3.6.5.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)
  
EnderCorePlugin (EnderCore-1.8.9-0.3.0.1-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.EnderCoreTransformerClient
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	EnderIO: No known problems detected.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.8.9-3.0.0.10_alpha
- EnderCore:1.8.9-0.3.0.1-beta
- Minecraft: 1.8.9
- Forge:1.8.9-forge1.8.9-11.15.1.1761

**Comment by srs-bsns** [comment]
try: [EnderCore-1.8.9-0.3.0.10-beta.jar](http://ci.tterrag.com/job/EnderCore-1.8/lastSuccessfulBuild/artifact/build/libs/EnderCore-1.8.9-0.3.0.10-beta.jar)

**Comment by Xiaminou** [comment]
should I be reporting bugs/crashes for the 1.8.9 branch or wait until release?

**Comment by HenryLoenwind** [comment]
I'd prefer them in our IRC channel. ATM there's more that's not working because it wasn't adapted for 1.8.9 yet than there is stuff that should work.

**Comment by Xiaminou** [comment]
Works fine so far, only 1 crash, I'll join IRC.

**Comment by reinder-s** [comment]
ok thanks
