### ISSUE TITLE
[1.8.9] ConcurrentModificationException while rendering conduit bundle

### ISSUE THREAD

**Issue by codewarrior0** [SleepyTrousers/EnderIO#3266]
#### Issue Description:

Client crash while rendering conduits. Playing on an online server. Seems to be a concurrency/multithreading issue. 

#### Steps to reproduce:

Unknown. Crashed spontaneously when idling in an area with a handful of machines and conduits.

#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.8.9-3.0.0.22_alpha
- EnderCore: EnderCore-1.8.9-0.3.0.13-beta
- Minecraft: 1.8.9
- Forge: forge-1.8.9-11.15.1.1808-universal.jar

#### Your most recent log file where the issue was present: 

```
Description: Tesselating block in world

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderConduits(ConduitBundleRenderer.java:139)
	at crazypants.enderio.conduit.render.ConduitBundleRenderer.getGeneralQuads(ConduitBundleRenderer.java:126)
	at crazypants.enderio.conduit.render.ConduitRenderMapper.mapBlockRender(ConduitRenderMapper.java:35)
	at crazypants.enderio.render.pipeline.BlockStateWrapperBase.bakeBlockLayer(BlockStateWrapperBase.java:180)
	at crazypants.enderio.render.pipeline.BlockStateWrapperBase.bakeModel(BlockStateWrapperBase.java:161)
	at crazypants.enderio.conduit.BlockConduitBundle.getExtendedState(BlockConduitBundle.java:163)
```

**Comment by mindforger** [comment]
please add a full crashlog via pastebin or as an attachment

**Comment by HenryLoenwind** [comment]
I know what this is. thx
