### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by androx102** [SleepyTrousers/EnderIO#3292]
#### What happens:
My server crashed after placeing any item from Ender IO on ground.
crash report : 
[16:13:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
	at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196) ~[MjAPI.class:?]
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85) ~[MjAPI.class:?]
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:55) ~[MjAPI.class:?]
	at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:46) ~[MjAPI.class:?]
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:159) ~[PowerHandler.class:?]
	at buildcraft.api.power.PowerHandler.<init>(PowerHandler.java:145) ~[PowerHandler.class:?]
	at crazypants.enderio.power.PowerHandlerUtil.createHandler(PowerHandlerUtil.java:62) ~[PowerHandlerUtil.class:?]
	at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:86) ~[AbstractMachineEntity.class:?]
	at crazypants.enderio.machine.AbstractMachineEntity.<init>(AbstractMachineEntity.java:185) ~[AbstractMachineEntity.class:?]
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.<init>(AbstractPoweredTaskEntity.java:26) ~[AbstractPoweredTaskEntity.class:?]
	at crazypants.enderio.machine.crusher.TileCrusher.<init>(TileCrusher.java:25) ~[TileCrusher.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_95]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_95]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_95]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_95]
	at java.lang.Class.newInstance(Class.java:383) ~[?:1.7.0_95]
	at crazypants.enderio.machine.AbstractMachineBlock.func_149915_a(AbstractMachineBlock.java:89) ~[AbstractMachineBlock.class:?]
	at net.minecraft.block.Block.createTileEntity(Block.java:1446) ~[aji.class:?]
	at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:850) ~[apx.class:?]
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:660) ~[apx.class:?]
	at net.minecraft.world.World.func_147465_d(World.java:451) ~[ahb.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206) ~[abh.class:?]
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103) ~[abh.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:454) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128) ~[add.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389) ~x.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.0.6.216
- EnderCore: 0.1.0.18_beta
- Minecraft: 1.7.10
- Forge: 10.13.2.1230 (i can't change version because host don't have any newer version) 

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Why are you trying to use a pre-historic version of Ender IO together with current EnderCore/Forge/...?

**Comment by androx102** [comment]
what version of Ender IO should i use ?

**Comment by HenryLoenwind** [comment]
Try either the latest release or the the latest beta: http://minecraft.curseforge.com/projects/ender-io (I'd recommend the beta)

**Comment by HenryLoenwind** [comment]
And btw, that question wasn't rhetoric. I'm really interested what lead to you using that version. If there's some page listing that version as "current", we may be able to get that information corrected.
