### ISSUE TITLE
[1.9.4] Placing conduit next to quite clear glass crashes the game

### ISSUE THREAD

**Issue by Kazzamkablam** [SleepyTrousers/EnderIO#3353]
#### Issue Description:

Placing energy conduit next to quite clear glass crashes the game

#### What happens:

I get this:

Time: 31.5.2016 23:50
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at crazypants.enderio.material.fusedQuartz.BlockFusedQuartz.func_176225_a(BlockFusedQuartz.java:92)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185894_c(BlockStateContainer.java:418)
	at crazypants.enderio.render.pipeline.BlockStateWrapperBase.func_185894_c(BlockStateWrapperBase.java:395)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:113)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:84)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:952)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1039)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

#### What you expected to happen:

Not crash?

#### Steps to reproduce:

1. place quite clear glass
2. place energy conduit next to it
3. profit
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 0.4.0.21-alpha
- EnderCore: 1.9.4-3.0.0.35_alpha
- Minecraft: 1.9.4
- Forge: 1936

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tterrag1098** [comment]
https://github.com/SleepyTrousers/EnderIO/blob/1.9/src/main/java/crazypants/enderio/material/fusedQuartz/BlockFusedQuartz.java#L92

Conduits must be returning null from IFacade which is illegal behavior. Remind me to add `@Nonnull` to that method later.
