### ISSUE TITLE
Crash when opening inventory search tab in creative mode

### ISSUE THREAD

**Issue by Flapjacks** [SleepyTrousers/EnderIO#3383]
#### Issue Description:
Opening Search tab in Creative Mode Inventory crashes the game

#### Steps to reproduce:

1. /gamemode c
2. Open inventory
3. Click the compass to get to search gab
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.9.4-3.0.0.37_alpha
 - EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
- Minecraft: 1.9.4
- Forge: FML: MCP 9.28 Powered by Forge 12.17.0.1954

#### Your most recent log file where the issue was present: 

ava.lang.NullPointerException: Updating screen events
	at crazypants.enderio.capacitor.CapacitorHelper.addCapData(CapacitorHelper.java:69)
	at crazypants.enderio.material.ItemCapacitor.func_150895_a(ItemCapacitor.java:69)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:342)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:523)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:539)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1699)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Alrawn** [comment]
This also happens when you click the EnderIO Tab in the creative inventory.

**Comment by Cat-McCatface** [comment]
This doesn't happen with EIO 3.0.0.36 so it might be a bug in the _Specialty Capacitors to Loot Tables_ commit

**Comment by tkdberger** [comment]
Sooo....is this getting fixed?

**Comment by tkdberger** [comment]
@Past me: it is: #3372

**Comment by HenryLoenwind** [comment]
oops, seems I forgot to link the main one in here. sry
