### ISSUE TITLE
item.null.name

### ISSUE THREAD

**Issue by JorVaCoding** [SleepyTrousers/EnderIO#3559]
#### Issue Description:
Right clicking with item.null.name crashes the client... when put into a fake player (ExtraUtils2's User in this case), it will crash the server...

#### What you expected to happen:
Not crash, I'm assuming its a WIP since it's registry name is "null" and lang file not containing a key

#### Steps to reproduce:
1. Craft
2. Right-click
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.0.1.75 (beta)
- EnderCore: 1.10.2-0.4.1.41 (beta)
- Minecraft: 1.10.2
- Forge: 2011

#### Your most recent log file where the issue was present: 
I don't have console access to the server

Also: If the item is a WIP (which I'm assuming it is), It shouldn't have a crafting recipe...

**Comment by AnrDaemon** [comment]
And the crash log is - ?…

**Comment by Keridos** [comment]
Rightclicking does not crash it for me on 
-     EnderIO: 1.10.2-3.0.1.81_beta
-     EnderCore: 1.10.2-0.4.1.46-beta
-     Minecraft: 1.10.2
-     Forge: 1.10.2-12.18.1.2022

**Comment by Nire46** [comment]
I did it, here's my error report:

`Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.enderio.core.common.util.BlockCoord.readFromNBT(BlockCoord.java:125)
	at crazypants.enderio.teleport.telepad.ItemCoordSelector.getCoords(ItemCoordSelector.java:217)
	at crazypants.enderio.teleport.telepad.ItemCoordSelector.rayTraceCoords(ItemCoordSelector.java:156)
	at crazypants.enderio.teleport.telepad.ItemCoordSelector.onItemUseFirst(ItemCoordSelector.java:88)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:398)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1517)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1748)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`
