### ISSUE TITLE
Don't load saved game after normally exit game

### ISSUE THREAD

**Issue by Uroboros65** [SleepyTrousers/EnderIO#3564]
[1.10.2]
Minecraft 1.10.2
PS: Sorry. My English language is bad. 

#### What happens:
When entering the game after the normal end of the previous session gives an error. 
If delete this mod then game starts and runs normally.

#### Steps to reproduce:
I don't know
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.77_beta.
- EnderCore: EnderCore-1.10.2-0.4.1.43-beta
- Minecraft: 1.10.2
- Forge:1.10.2-12.18.1.2011

#### Your most recent log file where the issue was present: 
The log files in zip:
https://yadi.sk/d/BFLHJcpNtmgtN

**Comment by HenryLoenwind** [comment]
Here's the crash:

```
io.netty.channel.ChannelException: connection refused
	at io.netty.channel.local.LocalChannel$LocalUnsafe.connect(LocalChannel.java:373)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199)
	at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:187)
	at io.netty.channel.local.LocalEventLoop.run(LocalEventLoop.java:33)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by HenryLoenwind** [comment]
and here's the reason for that:

```
[02:02:23] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.StackOverflowError
	at net.minecraft.world.World.func_189509_E(World.java:216) ~[aid.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:834) ~[aid.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.canMineBlock(TileMiner.java:108) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:273) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:294) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:294) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:294) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:294) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:294) ~[TileMiner.class:?]
	at com.vanhal.progressiveautomation.entities.miner.TileMiner.getNextBlock(TileMiner.java:294) ~[TileMiner.class:?]
```

**Comment by HenryLoenwind** [comment]
So, please report this to progressiveautomation.

Feel free to link this ticket in.
