### ISSUE TITLE
Farming Station not validating planting location

### ISSUE THREAD

**Issue by ShadowDrakken** [SleepyTrousers/EnderIO#3610]
#### Issue Description:
The Farming Station attempts to plant saplings on invalid blocks, even trying to plant them floating in air if there's no block below them at all.

#### What happens:
The Farming Station attempts to plant saplings on invalid blocks, even trying to plant them floating in air if there's no block below them at all.

#### What you expected to happen:
Expect the farming station to skip invalid locations and not toss saplings to the wind :)

#### Steps to reproduce:

1. Setup a farming station as normal
2. Remove some blocks from the farming area or replace them with invalid blocks (such as stone)
3. Activate farming station with saplings.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.0.1.92
- EnderCore: 0.4.1.47
- Minecraft: 1.10.2
- Forge: 12.18.1.2061

#### Your most recent log file where the issue was present: 

N/A, this is not a crash

**Comment by HenryLoenwind** [comment]
![image](https://cloud.githubusercontent.com/assets/1485873/17683404/da8d0aea-6352-11e6-89b3-a8357abe08bd.png)

Sorry, can not reproduce this.

**Comment by ShadowDrakken** [comment]
:\ that's odd... it's definitely happening on my server

I've tried it with a default farming station, as well as with chest drop capacitors and crafted capacitors trying to see if the chest drop capacitor was the cause, but it exhibits the problem regardless.

I guess it must be a mod interaction issue maybe? BOP, Quark, Forestry and Pam's Harvestcraft are the mods I have that might be modifying saplings, pretty sure none of the others I use do.

Exported Curse Profile: https://www.dropbox.com/s/g2vduqv16f65fip/Tech%20Pack%20-%201.10.2-20160815.zip?dl=0

**Comment by ShadowDrakken** [comment]
Interesting... made a creative test world and as soon as I plopped down a farming station I got this error:

java.lang.ArrayIndexOutOfBoundsException: 8
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:135)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:163)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.canPlant(CustomSeedFarmer.java:232)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.plantFromInventory(CustomSeedFarmer.java:141)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.prepareBlock(CustomSeedFarmer.java:128)
	at crazypants.enderio.machine.farm.farmers.FarmersCommune.prepareBlock(FarmersCommune.java:60)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:476)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:429)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:114)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:284)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:414)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

So yeah, mod interaction bug with BOP apparently... should I cross-post this issue?

**Comment by HenryLoenwind** [comment]
That crash is a known bug in BoP, I reported it there a while ago. You should be able to find it on their bugtracker, last I checked it was about halfway down the first page.

**Comment by HenryLoenwind** [comment]
This fix is for replanting after a harvest and over an invalid block there should be no harvest. But maybe it helps anyway...
