### ISSUE TITLE
[1.10.2] Server crash Farm on Biomes o plenty grass.

### ISSUE THREAD

**Issue by ProsperCraft** [SleepyTrousers/EnderIO#3834]
https://gist.github.com/ProsperCraft/bda47a4fb9a7fa2a3fd321b5944d57f7

EnderIO{1.10.2-3.0.1.125_beta}
Minecraft Forge: 12.18.2.2123
EnderCore-1.10.2-0.4.1.58-beta.jar

ava.lang.ArrayIndexOutOfBoundsException: 8
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:135)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:163)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.canPlant(CustomSeedFarmer.java:232)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.plantFromInventory(CustomSeedFarmer.java:141)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.prepareBlock(CustomSeedFarmer.java:128)
	at crazypants.enderio.machine.farm.farmers.FarmersCommune.prepareBlock(FarmersCommune.java:60)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:486)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:438)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:114)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:290)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:423)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:211)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjk000(WorldServer.java:1298)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MrNinja93** [comment]
Try with Version 2092+ of Biomes o Plenty.
