### ISSUE TITLE
1.10.2 crash during world startup

### ISSUE THREAD

**Issue by croftyraider** [SleepyTrousers/EnderIO#3928]
#### Issue Description:
I was restarting my world after taking a break and it crashed during initial world load. I had not made any changes to my EnderIO equipment in quite awhile, so I'm suspecting that this is one of those unfortunate intermittent bugs. This is in a personally made modpack.
[crash-2016-12-18_15.31.17-server.txt](https://github.com/SleepyTrousers/EnderIO/files/659771/crash-2016-12-18_15.31.17-server.txt)

#### What happens:

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(SourceFile:1233)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:95)
	at net.minecraft.inventory.ContainerPlayer.<init>(ContainerPlayer.java:90)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:161)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:142)
	at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:42)
	at crazypants.enderio.machine.FakePlayerEIO.<init>(FakePlayerEIO.java:19)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:482)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:438)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:114)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:288)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:423)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

#### What you expected to happen:
World load up like it normally does.

____
#### Affected Versions (Do *not* use "latest"):
EnderIO-1.10.2-3.0.1.121_beta.jar
EnderCore-1.10.2-0.4.1.56-beta.jar
Minecraft 1.10.2
Forge: 1.10.2-12.18.2.2179

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
Some other mod added a crafting recipe while the game was already running. That is just evil...
