### ISSUE TITLE
errors in code (i think it is enderIO)

### ISSUE THREAD

**Issue by woodyjm** [SleepyTrousers/EnderIO#4027]
i don't know why i am getting errors in my modpack, here is the crash report:
 
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3
Time: 02/02/17 18:21
Description: There was a severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeDirection
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeDirection
    at crazypants.enderio.GuiHandler.<clinit>(GuiHandler.java:23)
    at crazypants.enderio.EnderIO.<clinit>(EnderIO.java:83)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.ForgeDirection
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 194082768 bytes (185 MB) / 342507520 bytes (326 MB) up to 10724048896 bytes (10227 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 36 mods loaded, 36 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UC    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UC    Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UC    AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
    UC    appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
    UC    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UC    mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
    UC    gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util (1).jar) 
    UC    AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
    UC    arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
    UC    ReiMinimap{1.7.10} [Rei's Minimap] (14139741712_ReiMinimap-1.7.10-3.6.jar) 
    UC    IC2{2.2.628-experimental} [IndustrialCraft 2] (14174917714_Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UC    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (_Inventory-Tweaks-Mod-1.7.10.jar) 
    UC    aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
    UC    appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
    UC    CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
    UC    BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
    UC    BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
    UC    BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
    UC    BuildCraft|Core{7.1.19} [BuildCraft] (buildcraft-7.1.19.jar) 
    UC    BuildCraft|Energy{7.1.19} [BC Energy] (buildcraft-7.1.19.jar) 
    UC    BuildCraft|Silicon{7.1.19} [BC Silicon] (buildcraft-7.1.19.jar) 
    UC    BuildCraft|Builders{7.1.19} [BC Builders] (buildcraft-7.1.19.jar) 
    UC    BuildCraft|Robotics{7.1.19} [BC Robotics] (buildcraft-7.1.19.jar) 
    UC    BuildCraft|Transport{7.1.19} [BC Transport] (buildcraft-7.1.19.jar) 
    UC    BuildCraft|Factory{7.1.19} [BC Factory] (buildcraft-7.1.19.jar) 
    UC    DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
    UC    endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
    UE    EnderIO{1.0.2} [Ender IO] (EnderIO-1.6.4-1.0.2.363.jar) 
    UC    ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
    UC    flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
    UC    lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
    UC    Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
    UC    TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
    UC    witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
    UC    IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.49' Renderer: 'GeForce GTX 960/PCIe/SSE2'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.3-327
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
 
please help.

#### What happens:
my game initialises all the mods then crasheswhen launching the game

#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1614

**Comment by HenryLoenwind** [comment]
EnderIO-1.6.4-1.0.2.363. Minecraft Version: 1.7.10. EnderIO-*1.6.4*-1.0.2.363. Minecraft Version: *1.7.10*. EnderIO-**1.6.4**-1.0.2.363. Minecraft Version: **1.7.10**.
