### ISSUE TITLE
unkown crash

### ISSUE THREAD

**Issue by artemOP** [SleepyTrousers/EnderIO#4068]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

during loading of the game it crashes before hitting the minecraft world select page

#### What you expected to happen:

game to initialise

#### Steps to reproduce:

1.instal EnderIO-1.10.2-3.1.170 and EnderCore-1.10.2-0.4.1.65-beta from curse
2.open minecraft
3.run game
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:1.10.2-3.1.170
- EnderCore:1.10.2-0.4.1.65-beta
- Minecraft: 1.10.2
- Forge:1.10.2-forge1.10.2-12.18.3.2239

#### Your most recent log file where the issue was present: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 02/03/17 18:20
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO (EnderIO)
Caused by: com.enderio.core.client.EnderCoreModConflictException: =======================================================================
	at crazypants.enderio.ClientProxy.stopWithErrorScreen(ClientProxy.java:237)
	at crazypants.enderio.config.recipes.RecipeLoader.recipeError(RecipeLoader.java:38)
	at crazypants.enderio.config.recipes.RecipeLoader.addRecipes(RecipeLoader.java:32)
	at crazypants.enderio.CommonProxy.init(CommonProxy.java:80)
	at crazypants.enderio.ClientProxy.init(ClientProxy.java:162)
	at crazypants.enderio.EnderIO.load(EnderIO.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException
	at com.enderio.core.client.EnderCoreModConflictException.<init>(EnderCoreModConflictException.java:17)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1563352496 bytes (1490 MB) / 3058049024 bytes (2916 MB) up to 3980394496 bytes (3796 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn3000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2239 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2239.jar) 
	UCHI	Forge{12.18.3.2239} [Minecraft Forge] (forge-1.10.2-12.18.3.2239.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHE	EnderIO{1.10.2-3.1.170} [Ender IO] (EnderIO-1.10.2-3.1.170.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4425' Renderer: 'Intel(R) HD Graphics'
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.EnergyStorage)
                  * RF API class 'IEnergyConnection' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyConnection)
                  * RF API class 'IEnergyContainerItem' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem)
                  * RF API class 'IEnergyHandler' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyHandler)
                  * RF API class 'IEnergyProvider' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyProvider)
                  * RF API class 'IEnergyReceiver' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyReceiver)
                  * RF API class 'IEnergyStorage' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyStorage)
                  * RF API class 'ItemEnergyContainer' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.ItemEnergyContainer)
                  * RF API class 'TileEnergyHandler' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.TileEnergyHandler)
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)
=======================================================================
== ENDER IO FATAL ERROR ==
=======================================================================
Cannot register recipes as configured. This means that either
your custom config file has an error or another mod does bad
things to vanilla items or the Ore Dictionary.
=======================================================================
== Bad file ==
recipe_aliases_core.xml or recipe_aliases_user.xml
=======================================================================
== Error Message ==
File has malformed XML:ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
=======================================================================

=======================================================================
Note: To start the game anyway, you can disable recipe loading in the
Ender IO config file. However, then all of Ender IO's crafting recipes
will be missing.
=======================================================================

[pastebin/gist/etc link here]

**Comment by mindforger** [comment]
sorry for simply quoting for this answer
>== ENDER IO FATAL ERROR ==
Cannot register recipes as configured. This means that either
your custom config file has an error or another mod does bad
things to vanilla items or the Ore Dictionary.
== Bad file ==
recipe_aliases_core.xml or recipe_aliases_user.xml

**Comment by artemOP** [comment]
i don't have a custom item file and do not recognize that file

**Comment by artemOP** [comment]
i also retried downloading forge and both ender files and got the same crash

**Comment by HenryLoenwind** [comment]
You either do have a ´recipe_aliases_user.xml´ or you have a completely different problem. Please post it here (attach it, don't copy the content).

**Comment by ktole1999** [comment]
i get the same error even on a clean mod install. 
[crash-2017-03-04_15.15.50-server.txt](https://github.com/SleepyTrousers/EnderIO/files/818942/crash-2017-03-04_15.15.50-server.txt)

any suggestions?

**Comment by artemOP** [comment]
if you have ever installed a modpack from somewhere like curse you have to delete everything in the file in .minecraft called configs, this solved all of my problems with crashing and instability

**Comment by HenryLoenwind** [comment]
BTW, the latest build will write the content of the offending file into the crash.

**Comment by ktole1999** [comment]
will update and try. this only happens on server, client is fine.
