### ISSUE TITLE
Transferred from the Endercore

### ISSUE THREAD

**Issue by malyarevich** [SleepyTrousers/EnderIO#4069]
#### Issue Description:
Note: in version 1.10.2 launcher crashed with forge and only EnderIO mods on vanilla 1.10.2

#### What happens:
3/7 phase of forge when complete just close minecraft and show msg about crash

#### What you expected to happen:
7/7 phase of forge run minecraft with mods EnderIO & EnderStorage

#### Steps to reproduce:

1. download clean 1.10.2
2. install forge 2185 or above
3. input mods in folder /mods/:
 - CodeChickenCore-1.10.2-2.4.0.100-universal
 - CodeChickenLib-1.10.2-2.5.0.178-universal
 - EnderCore-1.10.2-0.4.1.60-beta
 - EnderIO-1.10.2-3.1.156
 - EnderStorage-1.10.2-2.2.0.96-universal
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft: 1.10.2
- Forge:

#### Your most recent log file where the issue was present: 

`---- Minecraft Crash Report ----

WARNING: coremods are present:
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.224-universal.jar)
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 3/2/17 1:13 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO (EnderIO)
Caused by: java.lang.NullPointerException
at net.minecraftforge.client.model.ModelLoader.setCustomStateMapper(ModelLoader.java:1072)
at crazypants.enderio.material.fusedQuartz.EnderIOGlassesStateMapper.create(EnderIOGlassesStateMapper.java:20)
at crazypants.enderio.ClientProxy.init(ClientProxy.java:104)
at crazypants.enderio.EnderIO.preInit(EnderIO.java:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.10.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_121, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 187127176 bytes (178 MB) / 373354496 bytes (356 MB) up to 3207856128 bytes (3059 MB)
JVM Flags: 5 total; -Xmx3072M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.32 Powered by Forge 12.18.3.2185 10 mods loaded, 10 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar)
UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar)
UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.224-universal.jar)
UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar)
UCH	CodeChickenLib{2.5.6.224} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.224-universal.jar)
UCH	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar)
UCH	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar)
UCE	EnderIO{1.10.2-3.1.171} [Ender IO] (EnderIO-1.10.2-3.1.171.jar)
UCH	EnderStorage{2.2.0.96} [EnderStorage] (EnderStorage-1.10.2-2.2.0.96-universal.jar)
Loaded coremods (and transformers):
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.224-universal.jar)
codechicken.lib.asm.ClassHeirachyManager
codechicken.lib.asm.CCL_ASMTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
com.enderio.core.common.transform.EnderCoreTransformer
GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4568' Renderer: 'Intel(R) HD Graphics 4600'
CodeChickenLib Invalid Fingerprint Reports:
CodeChickenCore Invalid Fingerprint Reports:
EnderIO: No known problems detected.
Detailed RF API diagnostics:
* RF API class 'EnergyStorage' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.EnergyStorage)
* RF API class 'IEnergyConnection' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyConnection)
* RF API class 'IEnergyContainerItem' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem)
* RF API class 'IEnergyHandler' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyHandler)
* RF API class 'IEnergyProvider' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyProvider)
* RF API class 'IEnergyReceiver' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyReceiver)
* RF API class 'IEnergyStorage' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyStorage)
* RF API class 'ItemEnergyContainer' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.ItemEnergyContainer)
* RF API class 'TileEnergyHandler' could not be loaded (reason: java.lang.ClassNotFoundException: cofh.api.energy.TileEnergyHandler)
Detailed Tesla API diagnostics:
* Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
* Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
* Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
* Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
* Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
* Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
* Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
* Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
* Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
* Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
* Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

EnderStorage Invalid Fingerprint Reports: `

**Comment by HenryLoenwind** [comment]
Which launcher are you using to start the game?

**Comment by malyarevich** [comment]
"tLauncher" for example in this case for this crash-report, but I tried different launchers.

Do u need something another logs?

**Comment by HenryLoenwind** [comment]
tLauncher? um, yeah, I thought so.

Sorry, no support for pirated clients. Feel free to open a new ticket if you can reproduce this with the vanilla launcher, the curse launcher or multimc.
