### ISSUE TITLE
Console Spam: World constructed without a WorldInfo!

### ISSUE THREAD

**Issue by Sir-Will** [SleepyTrousers/EnderIO#4271]
```
[11:26:43] [Server thread/WARN] [Sponge/]: World constructed without a WorldInfo! This will likely cause problems. Subsituting dummy info.
java.lang.RuntimeException: Stack trace:
	at net.minecraft.world.World.handler$onConstructed$zjp000(World.java:4776) [aid.class:?]
	at net.minecraft.world.World.<init>(World.java:133) [aid.class:?]
	at crazypants.enderio.machine.farm.PickupWorld.<init>(PickupWorld.java:75) [PickupWorld.class:?]
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:494) [TileFarmStation.class:?]
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:462) [TileFarmStation.class:?]
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:116) [AbstractPoweredTaskEntity.class:?]
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:227) [AbstractMachineEntity.class:?]
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73) [AbstractPoweredMachineEntity.class:?]
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:447) [TileFarmStation.class:?]
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40) [TileEntityBase.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231) [TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2401]
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2808) [ls.class:?]
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2795) [ls.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6049) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2162) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
EnderIO-1.10.2-3.1.190
EnderCore-1.10.2-0.4.1.66-beta

**Comment by HenryLoenwind** [comment]
#4265
