### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by drock71101** [SleepyTrousers/EnderIO#4293]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 7/26/17 8:52 PM
Description: Initializing game

java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.common.blocks.ChaosShardAtmos.setTickRandomly(Z)Lnet/minecraft/block/Block;
	at com.brandon3055.draconicevolution.common.blocks.ChaosShardAtmos.<init>(ChaosShardAtmos.java:18)
	at com.brandon3055.draconicevolution.common.ModBlocks.<clinit>(ModBlocks.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.brandon3055.draconicevolution.common.blocks.ChaosShardAtmos.<init>(ChaosShardAtmos.java:18)
	at com.brandon3055.draconicevolution.common.ModBlocks.<clinit>(ModBlocks.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165715064 bytes (158 MB) / 469606400 bytes (447 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D8 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UC	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	mcpml{10.1} [Partial Modification Loader [for Minecraft]] (PML_MinecraftApp.jar) 
	UC	Pistronics2{0.6.3} [Pistronics 2] (1.7.10-Pistronics2-v0.6.4.jar) 
	UC	securitycraft{v1.8.2.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.2.1.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) 
	UC	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UC	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UC	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UC	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UC	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12-deobf.jar) 
	UC	BuildCraft|Core{7.1.22} [BuildCraft] (buildcraft-7.1.22.jar) 
	UC	BuildCraft|Transport{7.1.22} [BC Transport] (buildcraft-7.1.22.jar) 
	UC	BuildCraft|Factory{7.1.22} [BC Factory] (buildcraft-7.1.22.jar) 
	UC	BuildCraft|Silicon{7.1.22} [BC Silicon] (buildcraft-7.1.22.jar) 
	UC	BuildCraft|Robotics{7.1.22} [BC Robotics] (buildcraft-7.1.22.jar) 
	UC	BuildCraft|Energy{7.1.22} [BC Energy] (buildcraft-7.1.22.jar) 
	UC	BuildCraft|Builders{7.1.22} [BC Builders] (buildcraft-7.1.22.jar) 
	UC	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UC	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UC	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UC	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
	UC	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
	UC	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
	UC	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
	UC	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
	UC	darkcore{0.3} [Dark Core] (darkcore-0.3-86.jar) 
	UC	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UC	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UC	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h-deobf.jar) 
	UC	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UC	EnderIO{2.0_beta} [Ender IO] (enderio-2.0_beta.147.jar) 
	UC	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UC	hbm{1.0.24} [Hbm's Nuclear Tech Mod] (hbm1.0.24.jar) 
	UC	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UC	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UC	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UC	minecolonies{1.7.10-0.0.15} [MineColonies] (minecolonies-universal-1.7.10-0.0.15.jar) 
	UC	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UC	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UC	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar) 
	UC	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	RTG{1.7.10-1.1.1.4} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.4.jar) 
	UC	SirenMod{2.2.01} [TheRealMcrafter's Siren Mod (Version 3.0.0)] (SirenMod-3.0.0.jar) 
	UC	StorageDrawers{1.7.10-1.7.0} [Storage Drawers] (StorageDrawers-1.7.10-1.7.0.jar) 
	UC	TardisMod{0.994} [Tardis Mod] (tardismod-1.7.10-0.994-124-DS.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UC	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UC	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UC	TooMuchTNT{2.9} [TooMuchTNT] (Too-Much-TNT-Mod-1.7.10.jar) 
	UC	VeinMiner{0.35.2_1.7.10-e134bd4} [Vein Miner] (VeinMiner-1.7.10-0.35.2.487+e134bd4.jar) 
	UC	VeinMinerModSupport{0.35.2_1.7.10-e134bd4} [Mod Support] (VeinMiner-1.7.10-0.35.2.487+e134bd4.jar) 
	UC	voxelmap{1.7.10} [VoxelMap No Radar] (VoxelMap-No-Radar-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce GTX 950M/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 950M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge,pml'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.53
	OpenGlRenderer: GeForce GTX 950M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by mindforger** [comment]
com.brandon3055.**draconicevolution**.common.blocks.ChaosShardAtmos.setTickRandomly(Z)Lnet/minecraft/block/Block;

**Comment by HenryLoenwind** [comment]
as mindforger said...

**Comment by drock71101** [comment]
@HenryLoenwind  But what do i do

**Comment by HenryLoenwind** [comment]
Talk to the Draconic Evolution guys instead of the Ender IO people...

**Comment by drock71101** [comment]
ok
