### ISSUE TITLE
Crash Upon entering private server. Any ideas?

### ISSUE THREAD

**Issue by Tylerun** [SleepyTrousers/EnderIO#4315]
#### Issue Description:
Crash on private server. We do not know why it is happening but on login it crashes the server. 

#### What happens:
Crash on Login and in logs it states enderio is having a problem.

#### What you expected to happen:
Login and have fun!

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.10.2-3.1.193
- EnderCore: 1.10.2-4.1.66
- Minecraft: 1.10.2
- Forge: 12.18.3.2422

#### Your most recent log file where the issue was present: 

[crash-2017-08-17_15.41.12-server.txt](https://github.com/SleepyTrousers/EnderIO/files/1232574/crash-2017-08-17_15.41.12-server.txt)

**Comment by HenryLoenwind** [comment]
That's in sponge, but if I had to guess, I'd say that your spongeapi and sponge don't match.

**Comment by Tylerun** [comment]
ARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.1.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  literalascension (literalascension-1.10.2-1.0.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.2.23.jar)
  SpongeCoremod (forge-1.10.2-12.18.3.2422-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.11.127-universal.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.3.239.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 8/17/17 4:06 PM
Description: Ticking block entity

java.lang.IncompatibleClassChangeError: vtable stub
	at org.spongepowered.mod.tracker.FluidTracker.fill(FluidTracker.java:54)
	at crazypants.enderio.conduit.liquid.LiquidConduit.redirectConduitTank$fill(LiquidConduit.java)
	at crazypants.enderio.conduit.liquid.LiquidConduit.pushLiquid(LiquidConduit.java:247)
	at crazypants.enderio.conduit.liquid.LiquidConduit.doExtract(LiquidConduit.java:138)
	at crazypants.enderio.conduit.liquid.LiquidConduit.updateEntity(LiquidConduit.java:97)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:251)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2831)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2818)
	at net.minecraft.world.World.func_72939_s(World.java:6063)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.spongepowered.mod.tracker.FluidTracker.fill(FluidTracker.java:54)
	at crazypants.enderio.conduit.liquid.LiquidConduit.redirectConduitTank$fill(LiquidConduit.java)
	at crazypants.enderio.conduit.liquid.LiquidConduit.pushLiquid(LiquidConduit.java:247)
	at crazypants.enderio.conduit.liquid.LiquidConduit.doExtract(LiquidConduit.java:138)
	at crazypants.enderio.conduit.liquid.LiquidConduit.updateEntity(LiquidConduit.java:97)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:251)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:40)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2831)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2818)

-- Block entity being ticked --
Details:
	Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
	Block type: ID #1268 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-312,27,-224), Chunk: (at 8,1,0 in -20,-14; contains blocks -320,0,-224 to -305,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #1268 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6063)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Tylerun** [comment]
Yeah that isnt sponge.

**Comment by GuntherDW** [comment]
Where do you from those crashlogs deduct that it's happening due to AA and Ender IO? You can clearly see that sponge is partially to cause.
I don't know the stance on Sponge support from EIO but that is clearly not something between AA and EIO.

**Comment by Tylerun** [comment]
1st screenshot link

**Comment by Tylerun** [comment]
If I am completely nutters and that doesnt say Actually Additions Fermenting Barrel let me know so I can go get some therapy.

**Comment by GuntherDW** [comment]
That statement would make sense if the crashlog didn't mention sponge on top of the stacktrace there.

Sponge changes a ton of stuff. That's why modders want you to test  the bug "cleanly". And not with mods installed like Sponge or Optifine.

**Comment by Tylerun** [comment]
We are on the most recent sponge for 1.10 so I am basically screwed for that entire area?

**Comment by Tylerun** [comment]
aight ill get out of here

**Comment by GuntherDW** [comment]
Like I said, bug the Sponge developers, not the EIO ones.

**Comment by HenryLoenwind** [comment]
BTW, this:

```
at org.spongepowered.mod.tracker.FluidTracker.fill(FluidTracker.java:54)
at crazypants.enderio.conduit.liquid.LiquidConduit.redirectConduitTank$fill(LiquidConduit.java)
```

is NOT part of Ender IO. Some other mod is using ASM to modify Ender IO on the fly.

**Comment by HenryLoenwind** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1732

**Comment by HenryLoenwind** [comment]
PS: I had a look at what they are doing. Seems to be one of those "throwing a burning match into a water tank to find out if it is empty works fine. Let's do the same for all tanks, water, gasoline, ..." moments. ;)

Downgrade to sponge 1.10.2-2281-5.2.0-BETA-2567.

**Comment by Tylerun** [comment]
I did already sorry

**Comment by HenryLoenwind** [comment]
np. With the severity of this I expect more people to turn up here looking for a solution.

**Comment by ryantheleach** [comment]
@Tylerun in general, post on (our) SpongeForge issue tracker *first*. If modders are willing to give time to investigate, create an issue on their tracker 2nd, linking back to the SpongeForge issue.

We acknowledge that SpongeForge can be the source of bugs that only appear when adding other mods, due to the large surface area of SpongeForges coremod. Occasionally we will kick back a bug to mod authors, as there isn't a direct way we can be compatible, or classes get loaded too early by core mods too tightly coupled to their mods.

 Also, the fluid tracking is brand new, it was to be expected that there would be some teething issues on the first usage of the new tracking system designed to hook into mod methods.

:-) Thanks for being patient with us EnderIO devs.

**Comment by HenryLoenwind** [comment]
@ryantheleach No problem. While SpongeForge does some weird stuff and from time to time causes weird issues, you are (a) open source, (b) respond to interaction issues and (c) work on fixing them. Unlike some other mods on our "not supported" list...
