### ISSUE TITLE
 [1.10.2] Crash with malformed JSON creating SP World

### ISSUE THREAD

**Issue by Morpheus1101** [SleepyTrousers/EnderIO#4348]
Crash @ https://puu.sh/y8jUz/cc70da6fe6.txt

- EnderIO: 3.1.193
- EnderCore: 0.4.1.66
- Minecraft: 1.10.2
- Forge: *.2511

**Comment by mindforger** [comment]
why is there a broken looking imgur picture link?

**Comment by Morpheus1101** [comment]
Beats me,  i thought it odd as well, but its in a pack which up untill recent update was working fine, an its tasken sdome digging just to get to the bottom of things

**Comment by mindforger** [comment]
updated my comment just now with more details

**Comment by HenryLoenwind** [comment]
```
Caused by: java.lang.NullPointerException
	at net.darkhax.eplus.item.ItemScroll.enchantScroll(ItemScroll.java:58) ~[ItemScroll.class:?]
	at net.darkhax.eplus.item.ItemScroll.createScroll(ItemScroll.java:47) ~[ItemScroll.class:?]
	at net.darkhax.eplus.item.ItemScroll.func_150895_a(ItemScroll.java:119) ~[ItemScroll.class:?]
	at crazypants.enderio.integration.jei.ItemHelper.getValidItems(ItemHelper.java:24) ~[ItemHelper.class:?]
```

This is the actual game crash. It seems Enchanting Plus has an item crashes the game when it is created.

**Comment by Morpheus1101** [comment]
Thankyou.  This has been a nightmare bug to try an track down the actual mod causing the inital issue
