### ISSUE TITLE
I believe this is a bug?

### ISSUE THREAD

**Issue by Beric88** [SleepyTrousers/EnderIO#4513]
#### Issue Description:
Minecraft server errors but not fatal.

#### What happens:
[16:24:36] [Server thread/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_161]
        at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:73) [ModContainerFactory.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:114) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:139) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:401) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:541) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: The modId EnderIO must be all lowercase.
        at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:143) ~[FMLModContainer.class:?]
        at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:127) ~[FMLModContainer.class:?]
        ... 16 more

#### What you expected to happen:
Not error.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 3.1.183
- EnderCore: 0.5.18
- Minecraft: 1.12.2
- Forge: 14.23.2.2651

#### Your most recent log file where the issue was present: 
Not sure which you need so I sent both
[debug-1.log.gz](https://github.com/SleepyTrousers/EnderIO/files/1869257/debug-1.log.gz)
[2018-04-02-5.log.gz](https://github.com/SleepyTrousers/EnderIO/files/1869258/2018-04-02-5.log.gz)

[pastebin/gist/etc link here]

**Comment by HenryLoenwind** [comment]
That a mod for Minecraft 1.10.2 doesn't work on Minecraft 1.12.2 is not considered a bug.
