### ISSUE TITLE
Crash when opening Wired Charger

### ISSUE THREAD

**Issue by DoctorZoe** [SleepyTrousers/EnderIO#4547]
#### Issue Description:
Crash to Desktop when using the Wired Charger.

#### What happens:
Crash to Desktop

#### What you expected to happen:
Open the Wired Charger GUI.

#### Steps to reproduce:

1. Place a Wired Charger on the World.
2. Right-Click it, whether or not it is charged or connected.
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.20.0
- EnderCore - 1.12.2-0.5.18 
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

#### Your most recent log file where the issue was present: 

---- Minecraft Crash Report ----
WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.2.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.5.5.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 4/12/18 11:31 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at crazypants.enderio.util.ShadowInventory.func_70301_a(ShadowInventory.java:29)
	at crazypants.enderio.machines.machine.wired.GuiWiredCharger.func_146976_a(GuiWiredCharger.java:57)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at com.enderio.core.client.gui.GuiContainerBase.func_73863_a(GuiContainerBase.java:356)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at crazypants.enderio.util.ShadowInventory.func_70301_a(ShadowInventory.java:29)
	at crazypants.enderio.machines.machine.wired.GuiWiredCharger.func_146976_a(GuiWiredCharger.java:57)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at com.enderio.core.client.gui.GuiContainerBase.func_73863_a(GuiContainerBase.java:356)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: crazypants.enderio.machines.machine.wired.GuiWiredCharger
	Mouse location: Scaled: (320, 179). Absolute: (960, 540)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['YamiFowl'/191, l='MpServer', x=1473.97, y=4.00, z=1235.05]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1431,4,1131), Chunk: (at 7,0,11 in 89,70; contains blocks 1424,0,1120 to 1439,255,1135), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
	Level time: 16581 game time, 34394 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityVillager['Villager'/129, l='MpServer', x=1393.69, y=4.94, z=1230.58], EntityZombieVillager['Zombie Villager'/135, l='MpServer', x=1406.49, y=4.00, z=1222.50], EntitySkeleton['Skeleton'/2215, l='MpServer', x=1411.50, y=7.00, z=1221.50], EntityPlayerSP['YamiFowl'/191, l='MpServer', x=1473.97, y=4.00, z=1235.05], EntitySheep['Sheep'/142, l='MpServer', x=1491.55, y=4.00, z=1217.74], EntitySheep['Sheep'/145, l='MpServer', x=1506.15, y=4.00, z=1234.85], EntityCow['Cow'/146, l='MpServer', x=1504.14, y=4.00, z=1251.15], EntityAuspiciousPoint['entity.auspicious_point.name'/147, l='MpServer', x=1502.00, y=10.00, z=1279.00], EntitySheep['Sheep'/150, l='MpServer', x=1509.32, y=4.00, z=1222.79], EntityFairyCircle['entity.fairy_circle.name'/151, l='MpServer', x=1515.00, y=8.00, z=1246.00], EntitySheep['Sheep'/154, l='MpServer', x=1526.50, y=4.00, z=1210.50], EntitySheep['Sheep'/155, l='MpServer', x=1535.34, y=4.00, z=1198.79], EntitySheep['Sheep'/156, l='MpServer', x=1522.69, y=4.00, z=1217.20], EntitySheep['Sheep'/157, l='MpServer', x=1525.78, y=4.00, z=1217.23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by EpicSquid** [comment]
Fixed in dev version
