### ISSUE TITLE
[1.12.2] Conduit Connector

### ISSUE THREAD

**Issue by TheSnowyChickens** [SleepyTrousers/EnderIO#4583]
#### Issue Description:
Hello,
Energy Conduits change to "Conduit connector" (like the picture) after relog / first login / load the world.

#### What happens:
- Conduit change.
- 
![2018-04-22_20 52 12](https://user-images.githubusercontent.com/29357962/39098703-13050034-466f-11e8-90ea-6aa452a4ef52.png)

#### What you expected to happen:
- It dont change to it.

#### Steps to reproduce:
0. Maybe it is a coordinate problem.
1. Place conduits.
2. relog.
3. tada

____
#### Affected Versions:

- EnderIO: EnderIO-1.12.2-5.0.22
- EnderCore: EnderCore-1.12.2-0.5.20
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.3.2670

#### Your most recent log file where the issue was present: 

[I dont know, if MC create a "log" after joining the world]

**Comment by tyler489** [comment]
Did  you recently update?

**Comment by tyler489** [comment]
Doesnt matter tbh.. was just wondering as i knew sone things changed in between versions that causes connectors to disapear on update. Does it happen if you break and replace?

**Comment by TheSnowyChickens** [comment]
I can break it (very fast without a tool), but then its just gone (No item drop) and the other conduits on the left and right side do not update themselves.

If I replace a new conduit, then energy flow is stable and it work again.

**Comment by tyler489** [comment]
And if you log out and back in after that is it gone again?

**Comment by TheSnowyChickens** [comment]
A new buggy conduit appear. (same like the picture)

**Comment by tyler489** [comment]
What mekanism machine is that?

**Comment by TheSnowyChickens** [comment]
Basic smelting factory, but it occures on pulverizer as well.

**Comment by tyler489** [comment]
Does it always occur on the top face? What mekanism version you using

**Comment by TheSnowyChickens** [comment]
From the 4 places, they are all on the top side, atm. I have no places on the side of a machine.

Mekanism-1.12.2-9.4.3.330
MekanismGenerators-1.12.2-9.4.3.330

ThermalDynamics-1.12.2-2.3.11.7-universal
ThermalExpansion-1.12.2-5.3.12.17-universal
ThermalFoundation-1.12.2-2.3.12.10-universal
CoFHCore-1.12.2-4.3.11.6-universal
CoFHWorld-1.12.2-1.1.1.12-universal

**Comment by EpicSquid** [comment]
Can you try without optifine and using the latest stable forge? (2655). I am unable to reproduce this error without optifine and with a stable forge version.

**Comment by TheSnowyChickens** [comment]
Okay, with Forge 2655 and no Optifine, BUT also with only 18 up tp 33 mods installed, the bug is disappeared. (some mods are may not compatible with 2655, thats why the lower)

And I tested it with Optifine, BetterFPS, FoamFix, TexFix, Sampler together and no bug occures.

So I think its a forge bug, do you have a account for the forge bug tracker, so that you can report this kind of issue there? (bc I dont have a acc. for it)

**Comment by tyler489** [comment]
https://github.com/MinecraftForge/MinecraftForge Forge Github

**Comment by TheSnowyChickens** [comment]
Ehm, dont work :D 
The support bot wrote: 
"👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the Forge Support Forums. Please create a new topic on the support forum with this issue, and the conversation can continue there."

Im in a discord Server with alot of persons, who are more implemented in MC cooding, maybe one of them has a Account, for Forge tracker, so they can post it.

**Comment by TheSnowyChickens** [comment]
A new example, the conduits dont like IE energy inputs :D 
![2018-04-26_21 24 41](https://user-images.githubusercontent.com/29357962/39327508-81b90f08-4998-11e8-9377-8e84d4a07550.png)

**Comment by tterrag1098** [comment]
Is there anything in the logs about errors while loading the TE data? That's about all I can think of that would cause this.

**Comment by Ommina** [comment]
My turn running into this. Adding to what @TheSnowyChickens has already said:

- I'm on SMP.  Client has reloaded, the server had not been restarted.
- The conduit was at the base of the machine.  The connection and the next two blocks were affected.  The subsequent two blocks were both corners.
- Forge 2655, no Optifine.
- The bounding box took up the full block of the affected conduit.
- I used a wrench to remove a conduit (via sneak rt-click).  The conduit _did_ drop and the remaining conduits _did_ render correctly after.  
- No sign in the logs about errors loading TE data.  I'll save them if there is a particular phrase for which I should search.

**Comment by idgarad** [comment]
I am seeing a similar related effect. Cannot break RS conduits and if they connect to an RS system all hell breaks loose. I traced the problem back to a run of RS conduits when I try to break them nothing happens and I am starting to see similar ghost conduit markers if I try to replace conduits I had removed earlier.

**Comment by WebDragon** [comment]
seeing the same thing here on FTB Revelation (latest) 
Java 1.8.0_151
Forge 14.23.4.2729
EnderIO 5.0.29

in my case the block is unbreakable and un-replaceable -- it appears to break when broken with a fist, but the block remains anyway.

It appeared below a TE Fluid Transposer

```[08:46:53] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerEvent$BreakSpeed@1bf9c115:
java.lang.ClassCastException: slimeknights.tconstruct.smeltery.tileentity.TileSmelteryComponent cannot be cast to crazypants.enderio.base.conduit.IConduitBundle
	at crazypants.enderio.conduits.handler.ConduitBreakSpeedHandler.onBreakSpeed(ConduitBreakSpeedHandler.java:24) ~[ConduitBreakSpeedHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_446_ConduitBreakSpeedHandler_onBreakSpeed_BreakSpeed.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:174) [ForgeEventFactory.class:?]
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:836) [aed.class:?]
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:249) [ForgeHooks.class:?]
	at net.minecraft.block.Block.func_180647_a(Block.java:559) [aow.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408) [awu$a.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:201) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:691) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[08:46:53] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[08:46:53] [Server thread/ERROR] [FML]: 0: NORMAL
[08:46:53] [Server thread/ERROR] [FML]: 1: ASM: class WayofTime.bloodmagic.util.handler.event.LivingArmourHandler onMiningSpeedCheck(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 2: ASM: class crazypants.enderio.conduits.handler.ConduitBreakSpeedHandler onBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 3: ASM: crafttweaker.mc1120.events.CommonEventHandler@219a2b3f onPlayerBreakSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 4: ASM: BlockSkyStone[unregistered] breakFaster(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 5: ASM: BlockSkyStone[unregistered] breakFaster(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 6: ASM: BlockSkyStone[unregistered] breakFaster(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 7: ASM: BlockSkyStone[unregistered] breakFaster(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 8: ASM: vazkii.quark.tweaks.feature.AxesBreakLeaves@23a839b1 calcBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 9: ASM: teamroots.embers.EventManager@44289829 onBlockBreak(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 10: ASM: com.rwtema.extrautils2.items.ItemDestructionWand@30011e7a adjustDigSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 11: ASM: com.rwtema.extrautils2.items.ItemDestructionWand@12e0421b adjustDigSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 12: ASM: crazypants.enderio.base.item.darksteel.ItemDarkSteelAxe@3021e73b onBreakSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 13: ASM: crazypants.enderio.base.item.darksteel.ItemDarkSteelShears@2d39f994 onBreakSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 14: ASM: crazypants.enderio.base.item.darksteel.ItemDarkSteelAxe@159de5c5 onBreakSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 15: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerServer@19695ea4 onHarvestSpeedCheck(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 16: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerCapeEffects@64da2baa onWaterBreak(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 17: ASM: blusunrize.immersiveengineering.common.EventHandler@61c0a49b digSpeedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 18: ASM: class reborncore.common.blocks.BlockWrenchEventHandler getDigSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 19: ASM: slimeknights.tconstruct.tools.TraitEvents@2a093 mineSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 20: ASM: slimeknights.tconstruct.library.tools.DualToolHarvestUtils@7bfd60e3 offhandBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/ERROR] [FML]: 21: LOW
[08:46:53] [Server thread/ERROR] [FML]: 22: ASM: com.brandon3055.draconicevolution.handlers.DEEventHandler@6c21d600 getBreakSpeed(Lnet/minecraftforge/event/entity/player/PlayerEvent$BreakSpeed;)V
[08:46:53] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: slimeknights.tconstruct.smeltery.tileentity.TileSmelteryComponent cannot be cast to crazypants.enderio.base.conduit.IConduitBundle
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassCastException: slimeknights.tconstruct.smeltery.tileentity.TileSmelteryComponent cannot be cast to crazypants.enderio.base.conduit.IConduitBundle
	at crazypants.enderio.conduits.handler.ConduitBreakSpeedHandler.onBreakSpeed(ConduitBreakSpeedHandler.java:24) ~[ConduitBreakSpeedHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_446_ConduitBreakSpeedHandler_onBreakSpeed_BreakSpeed.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:174) ~[ForgeEventFactory.class:?]
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:836) ~[aed.class:?]
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:249) ~[ForgeHooks.class:?]
	at net.minecraft.block.Block.func_180647_a(Block.java:559) ~[aow.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408) ~[awu$a.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:201) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:691) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more```

**Comment by mindforger** [comment]
@HenryLoenwind @EpicSquid 

would it be an problem to make a check with instanceof on TEs before actually (an implicitely) casting them to soemthing else?! You can then throw a nicer message or even invalidate the conduit to not have such conduit zombies flying around

or display a broken but removable block instead that ahs somethign written on it like "check you log when breaking this" and write to the log when this block is broken to have better insight?!

**Comment by HenryLoenwind** [comment]
mindforger, yes and no. depends which of the 500 different issues that were posted here you're talking about...

The last stack trace that was posted today show a corrupted world. Nothing much we can do about it but trying to not be the one that is involved in the eventual crash...

**Comment by mindforger** [comment]
i picked out via search all lines i found suspicious
some of them might not appear to be able to fail as they are called via callchains that are not supposed to fail but as you said and as i learned from immersive the world tends to corrupt or desync due to sponge and some sanity checks won't hurt to pretty print the issue so people do not report with cryptic crashes they can't identify themself ... maybe soemthing like "this isn't right, world maybe corrupt or get rid of sponge" :P

the most obvious :

https://github.com/SleepyTrousers/EnderIO/blob/37629ade042e9372c1d6df0852db775e7cb7a5f8/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/BlockConduitBundle.java#L445
https://github.com/SleepyTrousers/EnderIO/blob/37629ade042e9372c1d6df0852db775e7cb7a5f8/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/BlockConduitBundle.java#L485
https://github.com/SleepyTrousers/EnderIO/blob/3699aef7c588ba7d9a86fdd55145c8c3622c7364/enderio-conduits/src/main/java/crazypants/enderio/conduits/handler/ConduitBreakSpeedHandler.java#L24
https://github.com/SleepyTrousers/EnderIO/blob/37629ade042e9372c1d6df0852db775e7cb7a5f8/enderio-machines/src/main/java/crazypants/enderio/machines/machine/vacuum/xp/BlockXPVacuum.java#L163
https://github.com/SleepyTrousers/EnderIO/blob/c97c3cc0081b5be5d4594d67620c48d5c1db0b49/enderio-conduits/src/main/java/crazypants/enderio/conduits/conduit/AbstractItemConduit.java#L96
https://github.com/SleepyTrousers/EnderIO/blob/86fa7a2e5f107c286eda21901fedf1b70c802eae/enderio-base/src/main/java/crazypants/enderio/base/power/PowerDistributor.java#L68
https://github.com/SleepyTrousers/EnderIO/blob/86fa7a2e5f107c286eda21901fedf1b70c802eae/enderio-base/src/main/java/crazypants/enderio/base/power/PowerDistributor.java#L68

and some more complex, where you might already have a check inside that i can't see from first glance:

https://github.com/SleepyTrousers/EnderIO/blob/37629ade042e9372c1d6df0852db775e7cb7a5f8/enderio-base/src/main/java/crazypants/enderio/base/conduit/facade/ItemConduitFacade.java#L88
https://github.com/SleepyTrousers/EnderIO/blob/86fa7a2e5f107c286eda21901fedf1b70c802eae/enderio-machines/src/main/java/crazypants/enderio/machines/machine/solar/TileSolarPanel.java#L87

and as you already have a blockstate wrapper, how about makin the getTileEntity a bit more checking?

https://github.com/SleepyTrousers/EnderIO/blob/50f82f89307045c7f7d7c22c69e17cd3c160dc2e/enderio-base/src/main/java/crazypants/enderio/base/render/pipeline/BlockStateWrapperBase.java#L143
