### ISSUE TITLE
Intermittent crash at boot

### ISSUE THREAD

**Issue by LemADEC** [SleepyTrousers/EnderIO#4714]
#### Issue Description:
Client crash on launch intermittently.

#### What happens:
Start the game => crash

#### What you expected to happen:
No crash

#### Steps to reproduce:
1. start the game

____
#### Affected Versions (Do *not* use "latest"):
- EnderIO: 1.12.2-5.0.26
- EnderCore: 1.12.2-0.5.31
- Minecraft: 1.12.2
- Forge: 14.23.4.2707

#### Your most recent log file where the issue was present: 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(Unknown Source)
	at com.enderio.core.common.util.NNList$ItrImpl.next(NNList.java:193)
	at com.enderio.core.common.util.stackable.Things.getItemStacks(Things.java:369)
	at com.enderio.core.common.util.stackable.Things.getItemStack(Things.java:384)
	at crazypants.enderio.base.config.recipes.ShapedRecipe.func_77571_b(ShapedRecipe.java:41)
	at net.minecraft.stats.StatList.func_75918_d(StatList.java:138)
	at net.minecraft.stats.StatList.reinit(StatList.java:348)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:559)
```
https://gist.github.com/LemADEC/fb677232a5cf393a3a4fff8fbb80bac5

**Comment by HenryLoenwind** [comment]
#4691
