### ISSUE TITLE
Logic error in conduit---no bundle set

### ISSUE THREAD

**Issue by MrNinja93** [SleepyTrousers/EnderIO#4806]
#### Issue Description:
Game is telling me to report so here you go...

Recently started spamming console with the stacktrace:-
```
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: java.lang.NullPointerException: Houston we have a problem: 'Logic error in conduit---no bundle set'. Please report that on our bugtracker unless you are using some old version. Thank you.
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at com.enderio.core.common.util.NullHelper.notnull(NullHelper.java:14)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.conduits.conduit.AbstractConduit.getBundle(AbstractConduit.java:212)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.conduits.conduit.power.PowerConduit$ConnectionSide.receiveEnergy(PowerConduit.java:694)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.base.power.forge.PowerInterfaceForge.receiveEnergy(PowerInterfaceForge.java:21)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.conduits.conduit.power.NetworkPowerManager.doApplyRecievedPower(NetworkPowerManager.java:168)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.conduits.conduit.power.NetworkPowerManager.applyRecievedPower(NetworkPowerManager.java:116)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.conduits.conduit.power.PowerConduitNetwork.tickEnd(PowerConduitNetwork.java:111)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at crazypants.enderio.base.handler.ServerTickHandler.onServerTick(ServerTickHandler.java:56)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_254_ServerTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[05:30:16] [Server thread/INFO] [STDERR]: [crazypants.enderio.conduits.conduit.power.NetworkPowerManager:applyRecievedPower:120]: 	at java.lang.Thread.run(Thread.java:745)

```
#### What happens:
Bunch of console spam

#### What you expected to happen:
No spam/stacktraces

#### Steps to reproduce:

No Idea
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.29
- EnderCore: 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2708
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
https://gist.github.com/MrNinja93/ed0ff9747b1904ee072ceb89afae1db2 (Truncated because gist hates the file size from a separate error...)

**Comment by EpicSquid** [comment]
Please update ender io.
