### ISSUE TITLE
World was broken in refined storage 1.66/1.67

### ISSUE THREAD

**Issue by Uptobillion** [SleepyTrousers/EnderIO#4910]
#### Issue Description:

world was broken in refined storage 1.66/1.67

#### What happens:
I fail to enter my world

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.0.36
- EnderCore:0.5.41
- Minecraft:1.12.2
- Forge:2770
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? SP

#### Your most recent log file where the issue was present: 
Time: 10/20/18 10:01 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: com.raoulvdberge.refinedstorage.api.autocrafting.ICraftingManager.request(Lnet/minecraft/item/ItemStack;I)Lcom/raoulvdberge/refinedstorage/api/autocrafting/task/ICraftingTask;
	at crazypants.enderio.conduits.refinedstorage.conduit.ConduitRefinedStorageNode.updateDirItems(ConduitRefinedStorageNode.java:276)
	at crazypants.enderio.conduits.refinedstorage.conduit.ConduitRefinedStorageNode.updateDir(ConduitRefinedStorageNode.java:128)
	at crazypants.enderio.conduits.refinedstorage.conduit.ConduitRefinedStorageNode.update(ConduitRefinedStorageNode.java:114)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_320_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

[pastebin/gist/etc link here]

**Comment by Uptobillion** [comment]
I entered my world by deleting RScontroller in the MCedit. but when I put it back, it was broken again.

**Comment by raoulvdberge** [comment]
Fixed for RS 1.6.8

https://github.com/raoulvdberge/refinedstorage/commit/f17f31acec7770b7e74c80803738aff707d5b0c0

**Comment by HenryLoenwind** [comment]
Thanks
