### ISSUE TITLE
Loads on Server, Won't Load on Client

### ISSUE THREAD

**Issue by ghost** [SleepyTrousers/EnderIO#4918]
#### Issue Description:

Won't start on client. 

#### What happens:

Have tried a few configurations, and various versions, I thought I had this running earlier with some *other* version of EnderIO but forgot which one, and now it just crashes when loading EnderIO. The "fix" with the other version seems to load, if I can remember which versions, but I had SEVERE issues connecting to the server (timeouts, having to remove NBT data, most of the time they just can't connect due to the same error as this crash on startup now etc). Please help.

#### What you expected to happen:

For it to load.

#### Steps to reproduce:

Use these mods + Forge 2760 or 2768: 

https://github.com/worldautomation/WA-Launcher-Pack/blob/master/app/assets/distribution.json

I had a pair of versions working, but when connecting to the server (new world or old) there were NBT issues, lag, timeouts, and failures. The server would error about fileIO something, but I didn't capture it as I was so upset at that point. Might try again later, but for now having to completely remove EnderIO unfortunately.
____
#### Affected Versions (Do *not* use "latest"):

https://github.com/worldautomation/WA-Launcher-Pack/blob/master/app/assets/distribution.json
(EnderCore-1.12.2-0.5.41)
(EnderIO-1.12.2-5.0.36)
(Forge 2760 or 2768 (both stable))

#### Your most recent log file where the issue was present: 

https://hastebin.com/enegavomad.rb

`|UE|enderio|5.0.36|EnderIO-base-1.12.2-5.0.36.jar|None|`

`net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: info/loenwind/autosave/util/NBTAction
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: info/loenwind/autosave/util/NBTAction
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:93)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: info.loenwind.autosave.util.NBTAction
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: java.lang.NullPointerException`

**Comment by system-operator** [comment]
I can get the client to load with:
EnderCore-1.12.2-0.5.39
EnderIO-1.12.2-5.0.33
Forge 2768 or Forge 2760

I will now test with the same versions on the server, to see if I suffer the can't login issue, NBT and fileIO errors. Will also wipe the world etc. Start on a fresh server to verify and capture the error if any. My apologies. I should have documented this, but thought it was a typical forge/mod version conflict from the beginning.

**Comment by system-operator** [comment]
All goes to poo. Server side when a client connects with the above versions it spams:
`        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:34) ~[ge.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:241) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:219) [aye.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[18:15:51] [File IO Thread/ERROR] [minecraft/AnvilChunkLoader]: Failed to save chunk
java.lang.NullPointerException: null
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:469) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:34) ~[ge.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:241) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:219) [aye.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[18:15:52] [File IO Thread/ERROR] [minecraft/AnvilChunkLoader]: Failed to save chunk
java.lang.NullPointerException: null
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:469) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:34) ~[ge.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:241) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:219) [aye.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[18:15:53] [File IO Thread/ERROR] [minecraft/AnvilChunkLoader]: Failed to save chunk
java.lang.NullPointerException: null
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:469) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagList.func_74734_a(NBTTagList.java:34) ~[ge.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_150298_a(NBTTagCompound.java:474) ~[fy.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74734_a(NBTTagCompound.java:35) ~[fy.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_150663_a(CompressedStreamTools.java:112) ~[gi.class:?]
        at net.minecraft.nbt.CompressedStreamTools.func_74800_a(CompressedStreamTools.java:102) ~[gi.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:241) ~[aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:219) [aye.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37) [bgx.class:?]
        at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30) [bgx.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

On the client: https://i.postimg.cc/SxggdLjv/screenshot-2018-10-25-at-02-33-27.png

**Comment by HenryLoenwind** [comment]
Ender IO is compatible with Forge 2705 or newer.

**Comment by tterrag1098** [comment]
These errors mean that AutoSave (a dependency of EnderIO that is shipped inside the jar) was not loaded properly. To see why you will need to look at the full log. Also check inside the `memory_repo` folder for its presence.
