### ISSUE TITLE
Ender IO dont work ingame

### ISSUE THREAD

**Issue by emike3d** [SleepyTrousers/EnderIO#4935]
Hi, I have install a Little FTB Server with SpongeForge

This mods a running

[1.12]MoVillages-1.5.4.jar
Chameleon-1.12-4.1.3.jar
EnderCore-1.12.2-0.5.43.jar
EnderIO-1.7.10-2.3.0.429_beta.jar
EnderStructures-1.7.10-0.0.1.14_alpha.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar
StorageDrawers-1.12.2-5.3.7.jar
StructuresCreator-1.7.10-0.0.1.7_alpha.jar

But Ender IO dont work ingamen, and in the logs i have this Error.

#### What happens:
[Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/PlayerOpenContainerEvent
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.enderio.core.common.Handlers.registerHandler(Handlers.java:271)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.enderio.core.common.Handlers.register(Handlers.java:230)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.enderio.core.EnderCore.init(EnderCore.java:140)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[02:10:44] [Server thread/INFO] [STDERR]: [com.enderio.core.common.Handlers:register:234]: 	at java.lang.Thread.run(Thread.java:748)
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.PlayerOpenContainerEvent
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 43 more
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[02:10:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 45 more

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:
- EnderCore:
- Minecraft:
- Forge:
- SpongeForge? yes/no
- Optifine? yes/no
- Single Player and/or Server?

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]

**Comment by tyler489** [comment]
Your mixing 1.12 and 1.7 versions of mods... that isnt going to work
