### ISSUE TITLE
Ender io and Refined Storage Crafting Crash

### ISSUE THREAD

**Issue by SirAron111** [SleepyTrousers/EnderIO#4959]
#### Issue Description:The Game Crashes when trying to hook up advanced ender io machines with the automatic crafting system from refined storage the moment you put the needed materials in the storage system that the machine wants to use.

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first. If you are using an unreleased version of Ender IO (a.k.a development/nightly version), please don't open an issue for features that have not been announced as "finished" or "working". Expect to be ignored if you ignore this template.

#### What happens:
Game Crash

#### What you expected to happen:
Automatic crafting of X item tested with Sand to Glass

#### Steps to reproduce:

1..Set up the machines how the refined storage wiki tells you to for using external machines with an ender io advanced machine like the advanced alloy smelter.
2.Put the pattern where it needs to be and put the materials in the storage
3.Game crashes when you try to let it craft
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.0.37
- EnderCore:1.12.2 0.5.43
- Minecraft:1.12.2
- Forge:14.23.5.2768
- Single Player and/or Server?
Single and server both

#### Your most recent log file where the issue was present: 

https://pastebin.com/ZYhHFVpe

**Comment by LumberWizard** [comment]
Can you send the actual crash report and not the entire log, which doesn't seem to contain a crash report?

**Comment by SirAron111** [comment]
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
        at java.util.AbstractList$Itr.next(AbstractList.java:358)
        at com.enderio.core.common.util.stackable.OreThing.is(OreThing.java:48)
        at com.enderio.core.common.util.stackable.Things.contains(Things.java:274)
        at crazypants.enderio.base.recipe.ThingsRecipeInput.isInput(ThingsRecipeInput.java:87)
        at crazypants.enderio.base.recipe.ManyToOneRecipeManager.isValidInput(ManyToOneRecipeManager.java:131)
        at crazypants.enderio.base.recipe.ManyToOneMachineRecipe.isValidInput(ManyToOneMachineRecipe.java:35)
        at crazypants.enderio.base.recipe.MachineRecipeRegistry.getRecipesForInput(MachineRecipeRegistry.java:77)
        at crazypants.enderio.machines.machine.alloy.TileAlloySmelter.isMachineItemValidForSlot(TileAlloySmelter.java:20
3)

**Comment by SirAron111** [comment]
that one?

**Comment by tyler489** [comment]
That is not a crash report. That is simply he server sayinf enderio was doing somehing when  it stalled.

**Comment by SirAron111** [comment]
sry for the bother but it seems the newst version of ender io that jsut came out fixed the problem anyway the 5.0.38
