### ISSUE TITLE
net.minecraft.util.ReportedException: Tesselating block in world CCL render error with refined storage conduit

### ISSUE THREAD

**Issue by maicol07** [SleepyTrousers/EnderIO#5158]
#### Issue Description:

CCL render error with refined storage conduit

#### What happens:

Conduit is transparent and it gives an error in the log (see below) but it's fully working

#### What you expected to happen:

Conduit is visible and no error

#### Steps to reproduce:

1. Place a refined storage conduit

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.44
- EnderCore: 1.12.2-0.5.57
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

```
[Chunk Batcher 1/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:218, y:68, z:115
  Block Class:   class crazypants.enderio.conduits.conduit.BlockConduitBundle
  Registry Name: enderio:block_conduit_bundle
  Metadata:      0
  State:         enderio:block_conduit_bundle[opaque=false]
 Tile at position
  Tile Class:    class crazypants.enderio.conduits.conduit.TileConduitBundle
  Tile Id:       enderio:tile_conduit_bundle
  Tile NBT:      {conduits:{size:0},paintSource-:1b,x:218,y:68,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},facadeType:0,z:115,id:"enderio:tile_conduit_bundle"}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlock(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at mrtjp.projectred.relocation.MovingBlockRenderDispatcher.renderBlock(renders.scala:275) [MovingBlockRenderDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: crazypants.enderio.conduit.refinedstorage.conduit.RefinedStorageConduit cannot be cast to com.tfar.stellarfluidconduits.common.conduit.stellar.StellarFluidConduit
	at com.tfar.stellarfluidconduits.common.conduit.stellar.StellarFluidConduitRenderer.addConduitQuads(StellarFluidConduitRenderer.java:35) ~[StellarFluidConduitRenderer.class:?]
	at crazypants.enderio.conduits.render.DefaultConduitRenderer.addBakedQuads(DefaultConduitRenderer.java:80) ~[DefaultConduitRenderer.class:?]
	at crazypants.enderio.conduits.render.ConduitBundleRenderer.addConduitQuads(ConduitBundleRenderer.java:161) ~[ConduitBundleRenderer.class:?]
	at crazypants.enderio.conduits.render.ConduitBundleRenderer.getGeneralQuads(ConduitBundleRenderer.java:137) ~[ConduitBundleRenderer.class:?]
	at crazypants.enderio.conduits.render.ConduitRenderMapper.mapBlockRender(ConduitRenderMapper.java:34) ~[ConduitRenderMapper.class:?]
	at crazypants.enderio.base.render.pipeline.BlockStateWrapperBase.bakeBlockLayer(BlockStateWrapperBase.java:213) ~[BlockStateWrapperBase.class:?]
	at crazypants.enderio.base.render.pipeline.BlockStateWrapperBase.bakeModel(BlockStateWrapperBase.java:187) ~[BlockStateWrapperBase.class:?]
	at crazypants.enderio.conduits.conduit.BlockConduitBundle.getExtendedState(BlockConduitBundle.java:173) ~[BlockConduitBundle.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:79) ~[bvm.class:?]
	... 6 more
```

**Comment by HenryLoenwind** [comment]
`at com.tfar.stellarfluidconduits.common.conduit.stellar.StellarFluidConduitRenderer.addConduitQuads(StellarFluidConduitRenderer.java:35) ~[StellarFluidConduitRenderer.class:?]`

**Comment by Tfarcenim** [comment]
I fixed that bug already https://github.com/Tfarcenim/StellarFluidConduits/commit/ec822a5cef1b631d153eff9afe41a8ed4dccaece
