### ISSUE TITLE
Skyfactory4 wont work with EnderIO

### ISSUE THREAD

**Issue by aussie4** [SleepyTrousers/EnderIO#5169]
Issue Description:
Tried installing enderIO back into skyfactory. I have it working client side but seems my server wont let me connect when its installed.

What happens:
Wont let me connect but runs fine in an offline world

Steps to reproduce:
1. Uninstalled Ender IO
2. Says its out of date
3. Reload Ender IO
4. Wont connect
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.46
- EnderCore: 1.12.2-0.5.59
- Minecraft: 1.12.2
- Forge: ForgeMultipart-1.12.2-2.6.1.81-universal
- SpongeForge? no
- Optifine? yes
- Server

#### Your most recent log file where the issue was present: 
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_big_advanced_item_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_existing_item_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_mod_item_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_power_item_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_fluid_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_not_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_or_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_and_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_nor_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_nand_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_xor_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_xnor_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_toggle_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_counting_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_sensor_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.item_redstone_timer_filter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_conduit_bundle
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_simple_furnace
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_simple_alloy_smelter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_alloy_smelter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_enhanced_alloy_smelter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_buffer
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_enchanter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_farm_station
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_combustion_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_enhanced_combustion_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_simple_stirling_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_stirling_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_zombie_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_franken_zombie_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_ender_generator
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_killer_joe
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_attractor_obelisk
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_aversion_obelisk
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_inhibitor_obelisk
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_relocator_obelisk
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_weather_obelisk
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_experience_obelisk
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_painter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_simple_sag_mill
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_sag_mill
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_enhanced_sag_mill
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_slice_and_splice
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_soul_binder
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_powered_spawner
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_vat
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_enhanced_vat
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_wired_charger
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_enhanced_wired_charger
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_simple_wired_charger
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_tank
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_transceiver
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_vacuum_chest
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_xp_vacuum
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_travel_anchor
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_tele_pad
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_dialing_device
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_impulse_hopper
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_crafter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_simple_crafter
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_cap_bank
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_power_monitor
> 
[K[15:37:45] [Server thread/INFO] [enderio]: Registered permission enderio.gui.block_advanced_power_monitor
> 
[K[15:37:45] [Server thread/INFO] [enderutilities]: Chisels and Bits compat loaded
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Recipe 'compactmachines3:energy_cell' is disabled via its json file
> 
[K[31;1m[15:37:45] [Server thread/ERROR] [compactmachines3]: Could not deserialize recipe from file: "example.energycell.json"
[39;0m> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "machine-tiny.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "redstonetunneltool.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "machine-large.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "machine-giant.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "tunneltool.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "machine-maximum.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "wallbreakable.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "machine-small.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Recipe 'compactmachines3:zombieegg' is disabled via its json file
> 
[K[31;1m[15:37:45] [Server thread/ERROR] [compactmachines3]: Could not deserialize recipe from file: "example.zombieegg.json"
[39;0m> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded recipe "machine-normal.json"
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded schema: test002 [size=TINY, blocks=3]
> 
[K[15:37:45] [Server thread/INFO] [compactmachines3]: Loaded schema: example-tree [size=NORMAL, blocks=137]
> Mixin successful? false
Mixin successful? false

[K[31;1m[15:37:46] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO Open Computers Conduits (enderioconduitsopencomputers)

Caused by: java.lang.ExceptionInInitializerError
	at crazypants.enderio.conduits.oc.EnderIOConduitsOpenComputers.init(EnderIOConduitsOpenComputers.java:71) ~[EnderIOConduitsOpenComputers.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[server.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.RuntimeException: Channel name 'enderioconduitsopencomputers' is too long for Forge. Maximum length supported is 20 characters.
	at com.enderio.core.common.network.ThreadedNetworkWrapper.<init>(ThreadedNetworkWrapper.java:58) ~[ThreadedNetworkWrapper.class:?]
	at crazypants.enderio.conduits.oc.network.PacketHandler.<clinit>(PacketHandler.java:16) ~[PacketHandler.class:?]
	at crazypants.enderio.conduits.oc.EnderIOConduitsOpenComputers.init(EnderIOConduitsOpenComputers.java:71) ~[EnderIOConduitsOpenComputers.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[server.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[server.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
[39;0m> 
[K[31;1m[15:37:46] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/minecraft-2/server/./crash-reports/crash-2019-07-08_15.37.46-server.txt
[39;0m> 
[K[15:37:46] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
> 
[K[15:37:46] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
> Exception in thread "Server thread" 
[K[15:37:46] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at appeng.core.AppEng.serverStopped(AppEng.java:271)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:847)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
> 
[K[15:37:46] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by HenryLoenwind** [comment]
> EnderIO: 5.0.46

no

**Comment by aussie4** [comment]
What do you mean no? thats the lastest verson of ender IO

**Comment by aussie4** [comment]
> > EnderIO: 5.0.46
> 
> no

What do you mean no? thats the lastest verson of ender IO

**Comment by HenryLoenwind** [comment]
I mean "No, you are not using 5.0.46"

Have a look in `/home/minecraft-2/server/./crash-reports/crash-2019-07-08_15.37.46-server.txt`, it lists all version numbers

**Comment by aussie4** [comment]
> I mean "No, you are not using 5.0.46"
> 
> Have a look in `/home/minecraft-2/server/./crash-reports/crash-2019-07-08_15.37.46-server.txt`, it lists all version numbers

Oh sorry, I was testing versions and forgot to switch it back. im booting it up now and seeing if it still wont let me connect

**Comment by aussie4** [comment]
got it working. sorry for wasting your time
