### ISSUE TITLE
Modpacks that have EnderIO wont load

### ISSUE THREAD

**Issue by Cleway** [SleepyTrousers/EnderIO#5175]
#### Issue Description:
Most modpacks from twitch launcher that has EnderIO in wont load past 4/7

#### What happens:
Minecraft keeps using ram but wont load EnderIO and start up

#### What you expected to happen:
For minecraft to open

#### Steps to reproduce:

1.Download modpack
2.Open modpack
3.Gets stuck at ender IO (4/7)

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.7.10-2.3.0.429_beta.jar
- EnderCore:EnderCore-1.7.10-0.2.0.39_beta.jar
- Minecraft:1.7.10
- Forge:forge-10.13.4.1614
- SpongeForge? No (i think im using twitch launcher)
- Optifine? no

#### Your most recent log file where the issue was present: 

[18:32:23] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:32:23] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:32:23] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[18:32:23] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[18:32:23] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 8.1:amd64:6.3, installed at C:\Users\Lenovan\Twitch\Minecraft\Install\runtime\jre-x64
[18:32:23] [main/INFO]: [AppEng] Core Init
[18:32:24] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:24] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:24] [main/INFO]: Loading tweaker fastcraft.Tweaker from fastcraft-1.23.jar
[18:32:24] [main/INFO]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.16.64.jar
[18:32:24] [main/ERROR]: Unable to read the jar file ForgeMultipart-1.7.10-1.2.0.345-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\Lenovan\Twitch\Minecraft\Instances\FTB Infinity Evolved Skyblock\mods\ForgeMultipart-1.7.10-1.2.0.345-universal.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_51]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:32:24] [main/ERROR]: Unable to read the jar file ForgeRelocation-0.0.1.4-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\Lenovan\Twitch\Minecraft\Instances\FTB Infinity Evolved Skyblock\mods\ForgeRelocation-0.0.1.4-universal.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_51]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:32:24] [main/ERROR]: Unable to read the jar file ForgeRelocationFMP-0.0.1.2-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\Lenovan\Twitch\Minecraft\Instances\FTB Infinity Evolved Skyblock\mods\ForgeRelocationFMP-0.0.1.2-universal.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_51]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:32:24] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:24] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/ERROR]: Unable to read the jar file MrTJPCore-1.1.0.33-universal.jar - ignoring
java.io.FileNotFoundException: C:\Users\Lenovan\Twitch\Minecraft\Instances\FTB Infinity Evolved Skyblock\mods\MrTJPCore-1.1.0.33-universal.jar (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[?:1.8.0_51]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_51]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_51]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:32:25] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/WARN]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:32:25] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:32:25] [main/INFO]: Loading tweak class name fastcraft.Tweaker
[18:32:25] [main/INFO]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[18:32:25] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[18:32:25] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:32:25] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:32:25] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:32:27] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Loaded library EJML-core-0.26.jar.
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Attempting to detect JVM version...
[18:32:27] [main/INFO]: Detected JVM: 1.8
[18:32:27] [main/INFO]: Starting library configuration...
[18:32:27] [main/INFO]: System attached to FML. Now intercepting all logging calls.
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class forestry.shade.javacheck.Java7Checker
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:27] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Attempting to discover integration callbacks in coremods...
[18:32:28] [main/INFO]: Beginning early config parsing...
[18:32:28] [main/INFO]: Finished config parsing.
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:32:28] [main/INFO]: Calling tweak class fastcraft.Tweaker
[18:32:28] [main/INFO]: FastCraft loaded.
[18:32:28] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[18:32:28] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[18:32:28] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[18:32:29] [main/INFO]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[18:32:29] [main/INFO]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[18:32:29] [main/INFO]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[18:32:30] [main/INFO]: Setting user: aik0hikari
[18:32:30] [main/INFO]: Patching leaves.
[18:32:30] [main/INFO]: Found leaf Class: net/minecraft/block/BlockLeavesBase
[18:32:30] [main/INFO]: Attempting to patch class net.minecraft.block.BlockOldLeaf...
[18:32:30] [main/INFO]: Successfully patched func_149720_d in net.minecraft.block.BlockOldLeaf
[18:32:31] [main/INFO]: Transforming Class [net.minecraft.entity.projectile.EntityArrow], Method [func_70071_h_]
[18:32:31] [main/INFO]: Transforming net.minecraft.entity.projectile.EntityArrow Finished.
[18:32:32] [main/INFO]: Transforming Class [net.minecraft.item.ItemStack], Method [func_77953_t]
[18:32:32] [main/INFO]: Transforming net.minecraft.item.ItemStack Finished.
[18:32:32] [main/INFO]: InvTweaks: net.minecraft.inventory.Container
[18:32:32] [main/INFO]: InvTweaks: net.minecraft.inventory.ContainerFurnace
[18:32:32] [main/INFO]: Transforming Class [net.minecraft.inventory.ContainerFurnace], Method [func_82846_b]
[18:32:32] [main/INFO]: Transforming net.minecraft.inventory.ContainerFurnace Finished.
[18:32:33] [Client thread/INFO]: LWJGL Version: 2.9.1
[18:32:34] [Client thread/INFO]: Attempting to patch class net.minecraft.world.biome.BiomeGenBase...
[18:32:34] [Client thread/INFO]: Sucessfully patched net.minecraft.world.biome.BiomeGenBase! 19 patches were applied.
[18:32:34] [Client thread/INFO]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// Oops.

Time: 6/13/19 6:32 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 393456616 bytes (375 MB) / 738197504 bytes (704 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3540' Renderer: 'Intel(R) HD Graphics 4600'
[18:32:34] [Client thread/INFO]: Attempting early MinecraftForge initialization
[18:32:34] [Client thread/INFO]: MinecraftForge v10.13.4.1614 Initialized
[18:32:34] [Client thread/INFO]: Replaced 183 ore recipies

**Comment by LumberWizard** [comment]
Issue does not seem to have anything to do with EnderIO. Nothing in the 1.7 version of EnderIO changed at all in nearly 3 years.

**Comment by zhourui123** [comment]
https://gist.github.com/zhourui123/1f4ac091ae2fda02d0c70103d55b8614
A similar question may have nothing to do with EnderIO , Did you fix it? Can you tell me how to solve it?

**Comment by mindforger** [comment]
@zhourui123 your ctm mod is breaking... Besides having a ton of seemingly invalid jar files with cryptic name (is this a language thing? )

**Comment by zhourui123** [comment]
I don't think it's broken, because I can open it using 7zip, and it passes `Examining` later in the debug log (line 1764). The name is cryptic because of it's ChineseMC

**Comment by HenryLoenwind** [comment]
Weird. looks like this file https://github.com/Chisel-Team/ConnectedTexturesMod/blob/1.12/dev/src/main/resources/META-INF/ctm_at.cfg is not there or is not loaded.

**Comment by mindforger** [comment]
>I don't think it's broken

i said it is breaking, not broken, like crashing ... more like Henry said

**Comment by zhourui123** [comment]
Sorry, I misunderstood it. From the log, it was indeed breaking. The file existed, but it got an `FileNotFoundException`,  I don't know how to solve it yet
