### ISSUE TITLE
Tinkers Construct and EnderIO Conflict

### ISSUE THREAD

**Issue by Wackywee** [SleepyTrousers/EnderIO#5176]
When loading up minecraft forge, I get a crash.

Here is the error message:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO Integration with Tinkers' Construct (enderiointegrationticlate)

And the log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
ForgelinPlugin (Forgelin-1.8.3.jar)
llibrary (llibrary-core-1.0.11-1.12.2.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
MovingWorldCore (movingworld-1.12-6.342-full.jar)
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/15/19 11:25 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO Integration with Tinkers' Construct (enderiointegrationticlate)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Invalid Alloy recipe: Result cannot be contained in inputs
at slimeknights.tconstruct.library.smeltery.AlloyRecipe.(AlloyRecipe.java:43)
at slimeknights.tconstruct.library.TinkerRegistry.registerAlloy(TinkerRegistry.java:587)
at crazypants.enderio.integration.tic.recipes.TicRegistration.registerAlloyRecipe(TicRegistration.java:55)
at crazypants.enderio.integration.tic.recipes.TicRegistration.registerAlloys(TicRegistration.java:151)
at crazypants.enderio.integration.tic.TicControl.postInitAfterTic(TicControl.java:115)
at crazypants.enderio.integration.tic.EnderIOIntegrationTicLate.init(EnderIOIntegrationTicLate.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3460600512 bytes (3300 MB) / 6643777536 bytes (6336 MB) up to 10737418240 bytes (10240 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_C7 99 mods loaded, 98 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID                                           | Version                  | Source                                                        | Signature                                |
|:----- |:-------------------------------------------- |:------------------------ |:------------------------------------------------------------- |:---------------------------------------- |
| LCHIJ | minecraft                                    | 1.12.2                   | minecraft.jar                                                 | None                                     |
| LCHIJ | mcp                                          | 9.42                     | minecraft.jar                                                 | None                                     |
| LCHIJ | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJ | forge                                        | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJ | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                                 | None                                     |
| LCHIJ | openmodscore                                 | 0.11.5                   | minecraft.jar                                                 | None                                     |
| LCHIJ | opencomputers|core                           | 1.7.3.146                | minecraft.jar                                                 | None                                     |
| LCHIJ | malisiscore                                  | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                                  | None                                     |
| LCHIJ | cubicchunks                                  | 1.12.2-0.0.809.0         | CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar | None                                     |
| LCHIJ | aether_legacy                                | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                               | None                                     |
| LCHIJ | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                                        | None                                     |
| LCHIJ | endercore                                    | 1.12.2-0.5.22            | EnderCore-1.12.2-0.5.22.jar                                   | None                                     |
| LCHIJ | jei                                          | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                                     | None                                     |
| LCHIJ | codechickenlib                               | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| LCHIJ | redstoneflux                                 | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJ | cofhcore                                     | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar                        | None                                     |
| LCHIJ | brandonscore                                 | 2.4.16                   | BrandonsCore-1.12.2-2.4.16.207-universal.jar                  | None                                     |
| LCHIJ | cofhworld                                    | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJ | thermalfoundation                            | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJ | draconicevolution                            | 2.3.23                   | Draconic-Evolution-1.12.2-2.3.23.345-universal.jar            | None                                     |
| LCHIJ | thermalexpansion                             | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJ | enderio                                      | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHIJ | enderiointegrationtic                        | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHIJ | mantle                                       | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                                      | None                                     |
| LCHIJ | tconstruct                                   | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                              | None                                     |
| LCHIJ | mmdlib                                       | 1.0.0-rc2                | MMDLib-1.12-1.0.0-rc2.36.jar                                  | None                                     |
| LCHIJ | thaumcraft                                   | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                              | None                                     |
| LCHIJ | basemetals                                   | 2.5.0-rc2                | BaseMetals-1.12-2.5.0-rc2.332.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
| LCHIJ | forgelin                                     | 1.8.3                    | Forgelin-1.8.3.jar                                            | None                                     |
| LCHIJ | betterfoliage                                | 2.2.0                    | BetterFoliage-MC1.12-2.2.0.jar                                | None                                     |
| LCHIJ | biomesoplenty                                | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar                 | None                                     |
| LCHIJ | botania                                      | r1.10-361                | Botania+r1.10-361.jar                                         | None                                     |
| LCHIJ | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                                      | None                                     |
| LCHIJ | chesttransporter                             | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                             | None                                     |
| LCHIJ | chickens                                     | 6.0.4                    | chickens-6.0.4.jar                                            | None                                     |
| LCHIJ | chiselsandbits                               | 14.33                    | chiselsandbits-14.33.jar                                      | None                                     |
| LCHIJ | sanlib                                       | 1.5.1                    | SanLib-1.12.2-1.5.1.jar                                       | df48348748b5e141b1d118e2302a8d5be930b708 |
| LCHIJ | claysoldiers                                 | 3.0.0-beta.1.1           | ClaySoldiersMod-1.12.2-3.0.0-beta.1.1.jar                     | None                                     |
| LCHIJ | controlling                                  | 3.0.7                    | Controlling-3.0.7.jar                                         | None                                     |
| LCHIJ | crafttweaker                                 | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                                 | None                                     |
| LCHIJ | cookingforblockheads                         | 6.4.71                   | CookingForBlockheads_1.12.2-6.4.71.jar                        | None                                     |
| LCHIJ | ctgui                                        | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                                 | None                                     |
| LCHIJ | crafttweakerjei                              | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                                 | None                                     |
| LCHIJ | dimdoors                                     | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                                | None                                     |
| LCHIJ | mocreatures                                  | 12.0.3                   | DrZharks MoCreatures Mod-12.0.3.jar                           | None                                     |
| LCHIJ | enderiobase                                  | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHIJ | enderioconduits                              | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHIJ | enderiointegrationforestry                   | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHIE | enderiointegrationticlate                    | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHI  | ftblib                                       | 5.4.3.129                | FTBLib-5.4.3.129.jar                                          | None                                     |
| LCHI  | enderiomachines                              | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHI  | enderiopowertools                            | 5.0.24                   | EnderIO-1.12.2-5.0.24.jar                                     | None                                     |
| LCHI  | enderstorage                                 | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| LCHI  | extrautils2                                  | 1.0                      | extrautils2-1.12-1.9.9.jar                                    | None                                     |
| LCHI  | opencomputers                                | 1.7.3.146                | OpenComputers-MC1.12.2-1.7.3.146.jar                          | None                                     |
| LCHI  | zerocore                                     | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                                   | None                                     |
| LCHI  | bigreactors                                  | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                           | None                                     |
| LCHI  | ferdinandsflowers                            | 1.10.1b                  | Ferdinand's+Flowers-1.10.1b-1.12.jar                          | None                                     |
| LCHI  | gravestone                                   | 1.10.1                   | gravestone-1.10.1.jar                                         | None                                     |
| LCHI  | hatchery                                     | 2.2.2                    | hatchery-1.12.2-2.2.2.jar                                     | None                                     |
| LCHI  | waila                                        | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                                     | None                                     |
| LCHI  | incontrol                                    | 3.9.12                   | incontrol-1.12-3.9.12.jar                                     | None                                     |
| LCHI  | infinitylib                                  | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                                        | None                                     |
| LCHI  | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| LCHI  | ironbackpacks                                | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                             | None                                     |
| LCHI  | ironchest                                    | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar                               | None                                     |
| LCHI  | journeymap                                   | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                                   | None                                     |
| LCHI  | jeresources                                  | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar                       | None                                     |
| LCHI  | mcjtylib_ng                                  | 3.5.3                    | mcjtylib-1.12-3.5.3.jar                                       | None                                     |
| LCHI  | mjrlegendslib                                | 1.12.2-1.1.3             | MJRLegendsLib-1.12.2-1.1.3.jar                                | b02331787272ec3515ebe63ecdeea0d746653468 |
| LCHI  | mob_grinding_utils                           | 0.3.6                    | MobGrindingUtils-0.3.6.jar                                    | None                                     |
| LCHI  | refinedstorage                               | 1.6.14                   | refinedstorage-1.6.14.jar                                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
| LCHI  | immersiveengineering                         | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
| LCHI  | morechickens                                 | 3.1.0                    | morechickens-1.12.2-3.1.0.jar                                 | None                                     |
| LCHI  | mousetweaks                                  | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                                 | None                                     |
| LCHI  | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                               | None                                     |
| LCHI  | llibrary                                     | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
| LCHI  | mowziesmobs                                  | 1.5.4                    | mowziesmobs-1.5.4.jar                                         | None                                     |
| LCHI  | natura                                       | 1.12.2-4.3.2.49          | natura-1.12.2-4.3.2.49.jar                                    | None                                     |
| LCHI  | naturescompass                               | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                               | None                                     |
| LCHI  | openmods                                     | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
| LCHI  | openblocks                                   | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
| LCHI  | harvestcraft                                 | 1.12.2u                  | Pam's+HarvestCraft+1.12.2u.jar                                | None                                     |
| LCHI  | potioncore                                   | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                                 | None                                     |
| LCHI  | rftools                                      | 7.71                     | rftools-1.12-7.71.jar                                         | None                                     |
| LCHI  | rftoolscontrol                               | 2.0.2                    | rftoolsctrl-1.12-2.0.2.jar                                    | None                                     |
| LCHI  | rftoolsdim                                   | 5.71                     | rftoolsdim-1.12-5.71.jar                                      | None                                     |
| LCHI  | roost                                        | 2.0.10                   | roost-1.12.2-2.0.10.jar                                       | None                                     |
| LCHI  | sanplayermodel                               | 1.1.1                    | SanLib-1.12.2-1.5.1.jar                                       | None                                     |
| LCHI  | simulatednights                              | 1.12-2.1.0               | simulatednights-1.12-2.1.0.jar                                | None                                     |
| LCHI  | soundfilters                                 | 0.11_for_1.12            | SoundFilters-0.11_for_1.12.jar                                | None                                     |
| LCHI  | storagedrawers                               | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                               | None                                     |
| LCHI  | thermaldynamics                              | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHI  | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                           | None                                     |
| LCHI  | toolbelt                                     | 1.9.8                    | ToolBelt-1.12.2-1.9.8.jar                                     | None                                     |
| LCHI  | treechopper                                  | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                                  | None                                     |
| LCHI  | vc                                           | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                                   | None                                     |
| LCHI  | xtones                                       | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                                      | None                                     |
| UD    | cubicchunkscore                              | @@VERSION@@              | minecraft.jar                                                 | None                                     |

Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)

llibrary (llibrary-core-1.0.11-1.12.2.jar)
net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)

IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
openmods.core.OpenModsClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
mods.betterfoliage.loader.BetterFoliageTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)

TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
li.cil.oc.common.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
com.enderio.core.common.transform.EnderCoreTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar)

GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
Pulsar/tconstruct loaded Pulses: 
	- TinkerCommons (Enabled/Forced)
	- TinkerWorld (Enabled/Not Forced)
	- TinkerTools (Enabled/Not Forced)
	- TinkerHarvestTools (Enabled/Forced)
	- TinkerMeleeWeapons (Enabled/Forced)
	- TinkerRangedWeapons (Enabled/Forced)
	- TinkerModifiers (Enabled/Forced)
	- TinkerSmeltery (Enabled/Not Forced)
	- TinkerGadgets (Enabled/Not Forced)
	- TinkerOredict (Enabled/Forced)
	- TinkerIntegration (Enabled/Forced)
	- TinkerFluids (Enabled/Forced)
	- TinkerMaterials (Enabled/Forced)
	- TinkerModelRegister (Enabled/Forced)
	- chiselsandbitsIntegration (Enabled/Not Forced)
	- wailaIntegration (Enabled/Not Forced)

Pulsar/natura loaded Pulses: 
	- NaturaCommons (Enabled/Forced)
	- NaturaOverworld (Enabled/Not Forced)
	- NaturaNether (Enabled/Not Forced)
	- NaturaDecorative (Enabled/Not Forced)
	- NaturaTools (Enabled/Not Forced)
	- NaturaEntities (Enabled/Not Forced)
	- NaturaOredict (Enabled/Forced)
	- NaturaWorld (Enabled/Not Forced)

Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
              * Optifine is installed. This is NOT supported.
             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!You are looking at the diagnostics information, not at the crash.       !!!
!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

OptiFine Version: OptiFine_1.12.2_HD_U_C7
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.6.0 NVIDIA 430.64
OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 6

**Comment by Wackywee** [comment]
Sweet. anyone care to point me to where the previous thread is? Also

**Comment by Wackywee** [comment]
Dont worry chief, I solved it by my own 2 hands. Sorry about being rude, it just brought up some new problems with my mods and I was distraught.
