### ISSUE TITLE
Mod conflicting between Galacticraft and this mod [Advancements]

### ISSUE THREAD

**Issue by snow6326** [SleepyTrousers/EnderIO#5281]
#### What happens:
The mod Galacticraft is conflicting with this mod.
Some of advancements in the galacticraft work fine but the other not
It is not urgent but I still reported the issue I found :)
Ready like this mod~~!!

#### What you expected to happen:
Advancements of two mods work fine

#### Steps to reproduce:

1. Run the Minecraft with all mods loaded
2. Check whether there is error message of the logs
3. Take away the EnderIO and EnderCore mod
4. No error message shown again.
____
#### Affected Versions (Do *not* use "latest"):
EnderCore-1.12.2-0.5.73.jar
EnderIO-1.12.2-5.1.52.jar
GalacticraftCore-1.12.2-4.0.2.238.jar
Galacticraft-Planets-1.12.2-4.0.2.238.jar
MicdoodleCore-1.12.2-4.0.2.238.jar

#### Your most recent log file where the issue was present: 
[15:40:12] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement galacticraftcore:galacticraft/moon_dungeon

[latest.log](https://github.com/SleepyTrousers/EnderIO/files/3855754/latest.log)

**Comment by HenryLoenwind** [comment]
We certainly have node code to unregister criterion trigger from the game.

**Comment by HenryLoenwind** [comment]
And we don't need to, as gc crashes when registering them: 

```
[15:39:49] [Server thread/WARN] []: java.lang.ArrayIndexOutOfBoundsException: 0
[15:39:49] [Server thread/WARN] []: 	at micdoodle8.mods.galacticraft.core.advancement.GCTriggers.registerTriggers(GCTriggers.java:23)
[15:39:49] [Server thread/WARN] []: 	at micdoodle8.mods.galacticraft.core.GalacticraftCore.init(GalacticraftCore.java:344)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:39:49] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:636)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:39:49] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:39:49] [Server thread/WARN] []: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:39:49] [Server thread/WARN] []: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[15:39:49] [Server thread/WARN] []: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
[15:39:49] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339)
[15:39:49] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:276)
[15:39:49] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599)
[15:39:49] [Server thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)
```
