### ISSUE TITLE
1.12.2 Console error

### ISSUE THREAD

**Issue by EnterFor** [SleepyTrousers/EnderIO#5317]
#### Issue Description:
An error occurred in the background of the server. The trigger reason is unknown.

#### What happens:
Console outputs duplicate error content.
I don't know if I should report it to you
Sorry, my English is not good. I'm Chinese

#### Affected Versions (Do *not* use "latest"):

- EnderIO:5.1.55
- EnderCore:0.5.73
- Minecraft:1.12.2
- Forge:2847
- SpongeForge? no
- Optifine? no
- Server.

#### Your most recent log file where the issue was present: 
`[19:38:34] [Server thread/WARN] [Minecraft]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.EntityLiving.setGoalTarget(EntityLiving.java:193) [vq.class:?]
	at net.minecraft.entity.monster.EntityEnderman.setGoalTarget(EntityEnderman.java:107) [acu.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70624_b(EntityEnderman.java:102) [acu.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.handlers.EndermanAttractionHandler.tick(EndermanAttractionHandler.java:23) [EndermanAttractionHandler.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.TileAttractor.tickTrackedEntities(TileAttractor.java:83) [TileAttractor.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.TileAttractor.processTasks(TileAttractor.java:126) [TileAttractor.class:?]
	at crazypants.enderio.base.machine.base.te.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:220) [AbstractMachineEntity.class:?]
	at crazypants.enderio.base.machine.baselegacy.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:62) [AbstractPoweredMachineEntity.class:?]
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:49) [TileEntityBase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2132) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[19:38:34] [Server thread/WARN] [Minecraft]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.EntityLiving.setGoalTarget(EntityLiving.java:193) [vq.class:?]
	at net.minecraft.entity.monster.EntityEnderman.setGoalTarget(EntityEnderman.java:107) [acu.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70624_b(EntityEnderman.java:102) [acu.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.handlers.EndermanAttractionHandler.tick(EndermanAttractionHandler.java:23) [EndermanAttractionHandler.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.TileAttractor.tickTrackedEntities(TileAttractor.java:83) [TileAttractor.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.TileAttractor.processTasks(TileAttractor.java:126) [TileAttractor.class:?]
	at crazypants.enderio.base.machine.base.te.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:220) [AbstractMachineEntity.class:?]
	at crazypants.enderio.base.machine.baselegacy.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:62) [AbstractPoweredMachineEntity.class:?]
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:49) [TileEntityBase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2132) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[19:38:38] [Server thread/WARN] [Minecraft]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
	at net.minecraft.entity.EntityLiving.setGoalTarget(EntityLiving.java:193) [vq.class:?]
	at net.minecraft.entity.monster.EntityEnderman.setGoalTarget(EntityEnderman.java:107) [acu.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70624_b(EntityEnderman.java:102) [acu.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.handlers.EndermanAttractionHandler.tick(EndermanAttractionHandler.java:23) [EndermanAttractionHandler.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.TileAttractor.tickTrackedEntities(TileAttractor.java:83) [TileAttractor.class:?]
	at crazypants.enderio.machines.machine.obelisk.attractor.TileAttractor.processTasks(TileAttractor.java:126) [TileAttractor.class:?]
	at crazypants.enderio.base.machine.base.te.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:220) [AbstractMachineEntity.class:?]
	at crazypants.enderio.base.machine.baselegacy.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:62) [AbstractPoweredMachineEntity.class:?]
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:49) [TileEntityBase.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2132) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by HenryLoenwind** [comment]
That code that is telling you to report the issue on "the" issue tracker was added by another mod. Sadly they forgot to add the information *what* issue tracker it should be reported, but it certainly isn't ours.

Sorry, feel free to yell at them once you found out who "they" are...

**Comment by EnterFor** [comment]
Thanks. Is there any other way to find the Mod that actually caused the error?

**Comment by HenryLoenwind** [comment]
You could check the startup log if any mod says that they are adding "setGoalTarget". Other than that, it's just the usual "remove coremods until it doesn't happen anymore"...

At least the number of coremods isn't that high usually. (Note: only coremods can add new methods to vanilla objects)
