### ISSUE TITLE
Hello, guys, I have the mistake. Please, help me.

### ISSUE THREAD

**Issue by AnpyHelp** [SleepyTrousers/EnderIO#5322]
#### What happens:
I have a problem. Minecraft crashed.

#### What you expected to happen:
I want to know, how I can destroy the crash's problem

This is from latest.log:
=============
java.lang.NullPointerException: Unexpected error
at eu.ha3.mc.presencefootsteps.mcpackage.implem.AcousticsManager.playStep(AcousticsManager.java:56)
at eu.ha3.mc.presencefootsteps.game.system.PFSolver.playAssociation(PFSolver.java:64)
at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.simulateFootsteps(PFReaderH.java:115)
at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.generateFootsteps(PFReaderH.java:66)
at eu.ha3.mc.presencefootsteps.game.system.PFIsolator.onFrame(PFIsolator.java:51)
at eu.ha3.mc.presencefootsteps.game.system.PFHaddon.onFrame(PFHaddon.java:359)
at eu.ha3.mc.haddon.litemod.LiteBase.onTick(LiteBase.java:99)
at com.mumfrey.liteloader.core.event.HandlerList$Tickable8.onTick(HandlerList$Tickable8.java:100)
at com.mumfrey.liteloader.client.ClientEvents.onTick(ClientEvents.java:416)
at com.mumfrey.liteloader.client.CallbackProxyClient.onTick(CallbackProxyClient.java:63)
at com.mumfrey.liteloader.core.event.EventProxy.$event00005(EventProxy.java:216)

**Comment by pupnewfster** [comment]
You have already been told this is not due to EnderIO. So why are you continuing to spam enderio's issue tracker? The stack trace you are sharing clearly points at `AcousticsManager` from `presencefootsteps`

**Comment by tyler489** [comment]
https://github.com/Sollace/Presence-Footsteps/issues
Please report that here

**Comment by AnpyHelp** [comment]
> https://github.com/Sollace/Presence-Footsteps/issues
> Please report that here

Thank you so much!
