### ISSUE TITLE
EnderIO Dimensional Transceiver error causes server crash/cant restart 

### ISSUE THREAD

**Issue by TheKFL** [SleepyTrousers/EnderIO#5380]
#### What happens: When I make the server and I join it, it works fine. When my friends join the server it kicks me and them off. I can provide the recent logs. I would prefer if I didn't have to install the mods 1 by 1, as I have 145 mods to do. The server was working fine last night when we were playing the mod pack for about 4 hours and then it did the same and kicked us off. I did not try to retry to play and went to bed. 

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: YES
- EnderCore: YES
- Minecraft:YES
- Forge:YES
- SpongeForge? NO
- Optifine? NO
- Single Player and/or Server? SERVER

**Comment by HenryLoenwind** [comment]
```
[13:06:38] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Loading NBT data
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:631) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(Unknown Source) ~[?:1.8.0_211]
	at java.util.zip.InflaterInputStream.read(Unknown Source) ~[?:1.8.0_211]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_211]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_211]
	at java.io.DataInputStream.readFully(Unknown Source) ~[?:1.8.0_211]
	at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_211]
	at java.io.DataInputStream.readUTF(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.nbt.NBTTagString.func_152446_a(NBTTagString.java:34) ~[dx.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:54) ~[dq.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398) ~[dh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52) ~[dh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398) ~[dh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52) ~[dh.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170) ~[du.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125) ~[du.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120) ~[du.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121) ~[aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) ~[MinecraftServer.class:?]
	... 4 more
[13:06:38] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Nathan Jackson\Desktop\New folder (3)\.\crash-reports\crash-2020-05-14_13.06.38-server.txt
```

One of the files your world is stored is got cut off in the middle. Nothing to Do with Ender IO.

**Comment by TheKFL** [comment]
SO what do I have to do to fix it?
