### ISSUE TITLE
Server crashes when loading Ender IO

### ISSUE THREAD

**Issue by JannickPvP** [SleepyTrousers/EnderIO#5416]
#### Issue Description:

My problem is when starting the server its booting till Ender IO is loading then it crashes and i use it with a modpack my own here the mods all are up to date:
- AgriCraft
- ArchitectureCraft
- BiblioCraft
- Buildcraft
- Buildcraft Compat
- ChickenChunks
- CodeChickenCore
- Decocraft
- EnderIO
- EnderCore
- Ex Compressum
- Ex Nihilo
- Gilded Games Util
- MalisisCore
- MalisisDoors
- The Aether II

#### What happens:
The Server crashes when Ender IO want to load

#### What you expected to happen:
The Server would start

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.429_beta
- EnderCore: 0.2.0.39_beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1558
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

---- Minecraft Crash Report ----
// There are four lights!

Time: 8/11/20 4:23 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.malisis.core.MalisisCore.replaceVanillaBlock(ILjava/lang/String;Ljava/lang/String;Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: net.malisis.core.MalisisCore.replaceVanillaBlock(ILjava/lang/String;Ljava/lang/String;Lnet/minecraft/block/Block;Lnet/minecraft/block/Block;)V
	at net.malisis.doors.Registers.registerVanillaDoors(Registers.java:114)
	at net.malisis.doors.Registers.init(Registers.java:83)
	at net.malisis.doors.MalisisDoors.preInit(MalisisDoors.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.0-1127.10.1.el7.x86_64
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 714832568 bytes (681 MB) / 1634729984 bytes (1559 MB) up to 4660396032 bytes (4444 MB)
	JVM Flags: 2 total; -Xmx5000M -Xms128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCH	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (Gilded Games Util.jar) 
	UCH	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft.jar) 
	UCH	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft.jar) 
	UCH	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft.jar) 
	UCH	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFH Core.jar) 
	UCH	BuildCraft|Core{7.1.23} [BuildCraft] (Buildcraft.jar) 
	UCH	BuildCraft|Transport{7.1.23} [BC Transport] (Buildcraft.jar) 
	UCH	BuildCraft|Builders{7.1.23} [BC Builders] (Buildcraft.jar) 
	UCH	BuildCraft|Compat{7.1.7} [BuildCraft Compat] (Buildcraft Compat.jar) 
	UCH	BuildCraft|Factory{7.1.23} [BC Factory] (Buildcraft.jar) 
	UCH	BuildCraft|Silicon{7.1.23} [BC Silicon] (Buildcraft.jar) 
	UCH	BuildCraft|Robotics{7.1.23} [BC Robotics] (Buildcraft.jar) 
	UCH	BuildCraft|Energy{7.1.23} [BC Energy] (Buildcraft.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft.jar) 
	UCH	props{2.4.2} [Decocraft] (Decocraft.jar) 
	UCH	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore.jar) 
	UCH	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (Ender IO.jar) 
	UCH	exnihilo{1.38-53} [Ex Nihilo] (Ex Nihilo.jar) 
	UCH	excompressum{1.2.0} [Ex Compressum] (Ex Compressum.jar) 
	UCH	malisiscore{1.7.10-0.14.3} [MalisisCore] (MalisisCore.jar) 
	UCE	malisisdoors{1.7.10-1.3.0} [Malisis' Doors] (MalisisDoors.jar) 
	UCH	aether{1.7.10-1.6} [Aether II] (The Aether II.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles.jar) 
	CoFHCore: -[1.7.10]3.1.4-329
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from Ex Compressum.jar).
                    It is a supported version, but that difference may lead to problems.
                  * Our API got loaded from Ender IO.jar. That's unexpected.
                  * Our API got loaded from Ender IO.jar. That's unexpected.
                  * Our API got loaded from Ender IO.jar. That's unexpected.
                  * Our API got loaded from Ender IO.jar. That's unexpected.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by CitiesXL2815** [comment]
sorry we don't support 1.7 anymore we moved on to 1.12
