### ISSUE TITLE
NullPointer spamming logs when looking at GalacticraftBlock using HWYLA Mod

### ISSUE THREAD

**Issue by pomtom44** [SleepyTrousers/EnderIO#5516]
#### What happens:

NullPointer exception when looking at a galaticraft wire using HeresWhatYourLookingAt Mod
Only happend when EnderIO is installed, when its removed problem doesnt happen
Look at the block long enough and you time out

(Note, have cross posted on the other mods support threads as well, as no idea which mod is causing it)

#### Steps to reproduce:

1. Install Galatricraft mods, EnderIO mods, and HWYLA Mod
2. Place aluminium wire from GC
3. Look at block to bring up HWYLA GUI and errors appear in logs

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2-5.2.66
- EnderCore: 1.12.2-0.5.76
- Minecraft: 1.12.2
- Forge:  14.23.5.2854
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? server

#### Your most recent log file where the issue was present: 
`[11:49:12] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at micdoodle8.mods.galacticraft.api.vector.BlockVec3.getTileEntityOnSide(BlockVec3.java:439) ~[BlockVec3.class:?]
        at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalConductor.getCapability(TileBaseUniversalConductor.java:457) ~[TileBaseUniversalConductor.class:?]
        at mcp.mobius.waila.addons.capability.HUDHandlerEnergy.getNBTData(HUDHandlerEnergy.java:46) ~[HUDHandlerEnergy.class:?]
        at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:93) ~[MessageRequestTile$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more`
        
 Full Log: https://pastebin.com/pBb6JyuF

**Comment by tyler489** [comment]
As far as I can tell from the log, this does not relate to enderio in any way.
