### ISSUE TITLE
Crash when placing wireless/enhanced wireless charger on charged capacitor

### ISSUE THREAD

**Issue by 1a310** [SleepyTrousers/EnderIO#5521]
#### Issue Description:
Crash when placing wireless/enhanced wireless charger on charged capacitor
#### What happens:
1.game freezing and crashing to launcher when placed
2.when I relaunch minecraft and reopen the world it appears to have saved the part where I placed the block and is on crash loop
#### What you expected to happen:
1.placing the wireless charger ontop of a charged capacitor(I tried vibrant and Creative)
2.the block charging my items and powering up powered lights in the area
3.not crashing :)
#### Steps to reproduce:
1.new world creative cheats on
2.creative mode search menu grab charged capacitor(any) and either Wireless Charging Antenna or Enhanced Variant
3.place capacitor down place Antenna on top
____
#### Affected Versions (Do *not* use "latest"):

- EnderIO:EnderIO-1.12.2-5.3.68.jar
- EnderCore:EnderCore-1.12.2-0.5.76.jar
- Minecraft:1.12.2
- Forge:forge-14.23.5.2855
- SpongeForge? no
- Optifine? no
- Single Player

#### Your most recent log file where the issue was present: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 5/26/21 12:54 PM
Description: Ticking player

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to crazypants.enderio.base.power.wireless.IWirelessCharger$ExcludedItem
	at crazypants.enderio.machines.machine.wireless.TileWirelessCharger.chargeItems(TileWirelessCharger.java:78)
	at crazypants.enderio.base.power.wireless.WirelessChargerController.chargePlayersItems(WirelessChargerController.java:93)
	at crazypants.enderio.base.power.wireless.WirelessChargerController.chargePlayersItems(WirelessChargerController.java:86)
	at crazypants.enderio.base.power.wireless.WirelessChargerController.onPlayerTick(WirelessChargerController.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_WirelessChargerController_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at crazypants.enderio.machines.machine.wireless.TileWirelessCharger.chargeItems(TileWirelessCharger.java:78)
	at crazypants.enderio.base.power.wireless.WirelessChargerController.chargePlayersItems(WirelessChargerController.java:93)
	at crazypants.enderio.base.power.wireless.WirelessChargerController.chargePlayersItems(WirelessChargerController.java:86)
	at crazypants.enderio.base.power.wireless.WirelessChargerController.onPlayerTick(WirelessChargerController.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_96_WirelessChargerController_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1478
	Entity Name: 1a310
	Entity's Exact location: -218.50, 87.00, 40.50
	Entity's Block location: World: (-219,87,40), Chunk: (at 5,5,8 in -14,2; contains blocks -224,0,32 to -209,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4b0f5141
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1620504248 bytes (1545 MB) / 3079667712 bytes (2937 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version       | Source                        | Signature                                |
	|:------ |:--------------------------------- |:------------- |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2        | minecraft.jar                 | None                                     |
	| LCHIJA | mcp                               | 9.42          | minecraft.jar                 | None                                     |
	| LCHIJA | FML                               | 8.0.99.99     | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2855  | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | endercore                         | 1.12.2-0.5.76 | EnderCore-1.12.2-0.5.76.jar   | None                                     |
	| LCHIJA | enderio                           | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderiobase                       | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderioconduits                   | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderiomachines                   | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |
	| LCHIJA | enderiopowertools                 | 5.3.68        | EnderIO-1.12.2-5.3.68.jar     | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: No known problems detected.
	Authlib is : /D:/mc2/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['1a310'/1478, l='New World', x=-218.50, y=87.00, z=40.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by HenryLoenwind** [comment]
Fixed version will be released later today

**Comment by bigenergy** [comment]
> Fixed version will be released later today

pls upload new version on curseforge
