### ISSUE TITLE
Crash on startup EnderIO-1.10.2-3.1.193

### ISSUE THREAD

**Issue by Losiqpl** [SleepyTrousers/EnderIO#5586]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.11.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.1.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  literalascension (literalascension-1.10.2-1.0.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.14.137-universal.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.5.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.7.5.245.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.3.239.jar)
  AppleCore (AppleCore-mc1.10.2-3.1.4.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 1/17/24 9:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO (EnderIO)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.client.model.ModelLoader.setCustomStateMapper(ModelLoader.java:1083)
	at crazypants.enderio.material.fusedQuartz.EnderIOGlassesStateMapper.create(EnderIOGlassesStateMapper.java:20)
	at crazypants.enderio.ClientProxy.init(ClientProxy.java:106)
	at crazypants.enderio.EnderIO.preInit(EnderIO.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
I have this problem, have anyone fix to this or cause of this error?

**Comment by CitiesXL2815** [comment]
We don't support 1.10.2 anymore
